### ISSUE TITLE
Cannot read local artifacts with useCachedArtifacts=true flag

### ISSUE THREAD

**Issue by fdingiit** [kubescape/kubescape#1008]
# Describe the bug
Cannot read the local artifacts files when scanning k8s cluster. In fact kubescape will download all the files from github even if they are already there.

See the code here:

https://github.com/kubescape/kubescape/blob/master/httphandler/handlerequests/v1/datastructuremethods.go#L35

```
if scanRequest.UseCachedArtifacts != nil {
		if useCachedArtifacts := cautils.NewBoolPtr(scanRequest.UseCachedArtifacts); useCachedArtifacts.Get() != nil && !*useCachedArtifacts.Get() {
			scanInfo.UseArtifactsFrom = getter.DefaultLocalStore // Load files from cache (this will prevent kubescape fom downloading the artifacts every time)
		}
}
```

I think the problem maybe in the second if statament:
`!*useCachedArtifacts.Get()` 
which means does not use cached artifacts. If I remove the `!`, I will almost get what I want, but check this out:

https://github.com/kubescape/kubescape/blob/master/core/core/initutils.go#L250

there is no local file loader for attack-tracks, so at last it will trigger a download process.

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

/usr/bin $ ./kubescape version
Your current version is: v2.0.180

# Steps To Reproduce
1. trigger a scan request to kubescape http handler, with `useCachedArtifacts` set to `true`
2. wait for kubescape to scan 

# Expected behavior
A scan without any download process

# Actual Behavior
A scan with full download

# Additional context
I have copy all the artifacts file (but no attack-tracks) into image by modifying Dockerfile.

**Comment by dwertent** [comment]
@Moshe-Rappaport-CA Regarding the attack-tracks, isn't this implemented?

@fdingiit KS will not download the artifacts if you run with this flag `--use-artifacts-from=/path/to/dir`.
This is what we do with the KS image, we download the artifacts as part of the [image build process](https://github.com/kubescape/kubescape/blob/master/build/Dockerfile#L34) so the container can run in an offline mode.

We might have an issue with the `useCachedArtifacts` flag, thank you for reporting this.

**Comment by danielqsj** [comment]
@dwertent #1009 already fix this issue. What's the estimated time of next release ?

**Comment by dwertent** [comment]
@danielqsj  Should be released in the close few days
