### ISSUE TITLE
Killercoda build playground has go 1.18 and needs go 1.19

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1019]
https://killercoda.com/suhas-gumma/scenario/kubescape-build-for-development fails when opened, because it has Go 1.18 installed and Kubescape now requires Go 1.19.

```
github.com/olekukonko/tablewriter
github.com/owenrumney/go-sarif/v2/sarif
github.com/kubescape/opa-utils/score
github.com/kubescape/opa-utils/resources
github.com/kubescape/kubescape/v2/core/pkg/containerscan
github.com/kubescape/kubescape/v2/core/pkg/registryadaptors/registryvulnerabilities
make: *** [Makefile:17: build] Error 2

$ make build
go build -v -tags="static" .
github.com/kubescape/opa-utils/gitregostore
# github.com/kubescape/opa-utils/gitregostore
../go/pkg/mod/github.com/kubescape/opa-utils@v0.0.223/gitregostore/gitstoreutils.go:66:19: undefined: url.JoinPath
note: module requires Go 1.19
make: *** [Makefile:17: build] Error 2

$ go version
go version go1.18 linux/amd64
```

A possible fix is to [install a newer Golang from a backports PPA](https://github.com/zchee/golang-wiki/blob/master/Ubuntu.md#using-ppa).

**Comment by suhasgumma** [comment]
Hi @craigbox, thank you for pointing out the issue. I have updated the playground to always use the latest version of Go (Currently 1.19). The playground is working as expected now.

**Comment by craigbox** [comment]
(We have a kubescape account now: we should talk about transferring the scenario into that.)

**Comment by suhasgumma** [comment]
> (We have a kubescape account now: we should talk about transferring the scenario into that.)

HI @craigbox , I can't find the killercoda scenarios repository in kubescape. Is it public? Anyways, [This is the code for building the scenario.](https://github.com/suhasgumma/killercoda-playgrounds/tree/master/kubescape-build-for-development)

**Comment by craigbox** [comment]
I haven't set a repo up yet.  We could possibly just move https://github.com/suhasgumma/killercoda-playgrounds under the kubescape org?

**Comment by suhasgumma** [comment]
> I haven't set a repo up yet. We could possibly just move https://github.com/suhasgumma/killercoda-playgrounds under the kubescape org?

Yes, that is a good idea but I need to have `permission to create public repositories in Kubescape` to transfer the repository. 

However, when I transfer to a user, the user just has to give permission and the transfer will be done. 
How about I try transferring it to your account and you could move it to Kubescape org?

**Comment by craigbox** [comment]
LGTM!
