### ISSUE TITLE
Don't do CI unless code changes

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1021]
https://github.com/kubescape/kubescape/pull/1020 changed a bunch of Markdown files, but nothing that required recompiling.  It still waited on doing CI builds for all three platforms.  Is there a way to detect that the changed files aren't code, and skip this step?

**Comment by fredbi** [comment]
@craigbox  yes github actions provide a way to filter on the type of file that trigger the action

**Comment by vladklokun** [comment]
@craigbox We already skip CI for Markdown files. It’s definitely possible to control what globs we skip CI on.

Regarding filetype filtering, we should consider that we `//go:embed` a PNG into our binary to include into a PDF document when we produce a PDF report. If this PNG corrupts or gets removed, our code will break, too. In an ideal world where we have tests for that, our tests would fail, too. Same thing with HTML. So it seems like we should run CI not only for code changes.

Maybe we should consider adding not necessarily filetype filtering, but rather filter by location? So we would not run CI when changing `docs` or something? Or, maybe, go the other way and exclude certain filetypes, except when they are used as resources and reside in pre-defined locations.
