### ISSUE TITLE
Docs page 404

### ISSUE THREAD

**Issue by TeamDman** [kubescape/kubescape#1023]
# Describe the bug
Getting the following output

```
+----------+--------------------------------+---------------------------------------+----------------------------------------------------------------------------+
| SEVERITY |          CONTROL NAME          |                 DOCS                  |                           ASSISTANT REMEDIATION                            |
+----------+--------------------------------+---------------------------------------+----------------------------------------------------------------------------+
| High     | Apply Security Context to Your | https://hub.armosec.io/docs/cis-5-7-3 | spec.template.spec.containers[0].securityContext.capabilities.drop=NET_RAW |
|          | Pods and Containers            |                                       |                                                                            |
+----------+--------------------------------+---------------------------------------+----------------------------------------------------------------------------+

```

but the docs link gives a 404
![image](https://user-images.githubusercontent.com/9356891/211651728-0ee68565-66b0-48b7-8237-7cf0ab3de9ee.png)

Bing links to the same page when I google "cis 5.7.3" so maybe it got moved or deleted?

**Comment by dwertent** [comment]
Thank you for reporting, this is due to changes in the control IDs and some issues we found that required us to revert the latest change.
@kooomix , @YiscahLevySilas1 we reverted here the changes but did not re-generate the documentation with the older controls IDs. 
Please fix it ASAP.

**Comment by YiscahLevySilas1** [comment]
fixed by [new release in regolibrary](https://github.com/kubescape/regolibrary/releases/tag/v1.0.241)
