### ISSUE TITLE
Can't scan with custom framework

### ISSUE THREAD

**Issue by yf-odyssey** [kubescape/kubescape#1028]
# Describe the bug
can't scan with custom framework

# Environment
OS version : Centos7
Kubescape version :  v2.0.174

# Steps To Reproduce
1. I log into cloud.armosec.io and create a custom framework named _test_ which included 9 controls. Below the screepshot.
![image](https://user-images.githubusercontent.com/33337184/211965774-101d0e24-e585-4cee-ba8c-8a14de7d91c7.png)

2. I have read the similiar issue(https://github.com/kubescape/kubescape/discussions/516?sort=top), so I run the scan which with the account flag and specified framework, just as the below. But it said the framework 'test' not found.

![image](https://user-images.githubusercontent.com/33337184/211966383-1645aeb5-0400-4271-89d8-45be3862ec12.png)

3. I also try to run the list frameworks with the account flag.But it still no my custom framework ,only showing the 
standard frameworks. Below  is the screenshot.
![image](https://user-images.githubusercontent.com/33337184/211967068-3a924027-9b97-4a50-8266-b6905bfd6218.png)

  I'm sure the account id is correct and I copy it from the cloudplatform.
![image](https://user-images.githubusercontent.com/33337184/211967240-3fe2710b-f808-425b-881f-c30d87cdf54d.png)
Could you help me to find out the problems? Thanks a lot!

**Comment by matthyx** [comment]
@yf-odyssey thanks for your report.
Can you try the latest version of kubescape and tell me if it persists?
https://github.com/kubescape/kubescape/releases/

**Comment by yf-odyssey** [comment]
> @yf-odyssey thanks for your report. Can you try the latest version of kubescape and tell me if it persists? https://github.com/kubescape/kubescape/releases/

Thanks matthyx！ I just downloaded the latest version and it works. So it may be a bug? Anyway, Thanks you all ! Kubescape is a wonderful opensource K8s security product!
![image](https://user-images.githubusercontent.com/33337184/212228192-9c8dacf5-c7f3-4434-a0c6-c2bc78e571f6.png)

**Comment by matthyx** [comment]
@yf-odyssey thanks for the kind words, yes it was a bug and it sounded like something we had solved already, hence my question.
I'm closing this issue, please feel free to reopen it if you need to.

**Comment by rawkode** [comment]
@matthyx This is actually still a bug. I'm running `kubescape list frameworks --account BLAH` and it's not including my custom frameworks.

I've tried 2.0.182 and the latest 183

**Comment by rawkode** [comment]
@matthyx I had to run a `kubescape scan --account X` first, before `list frameworks` would work.

I'm assuming that the list command doesn't use the account ID and relies on the cached account, which isn't set until a scan?

**Comment by matthyx** [comment]
> I'm assuming that the list command doesn't use the account ID and relies on the cached account, which isn't set until a scan?

I think it's more the token that is not retrieved unless you perform a scan.
Maybe @dwertent  can confirm?
