### ISSUE TITLE
Make image scanning feature work with --enable-host-scan flag

### ISSUE THREAD

**Issue by MMquant** [kubescape/kubescape#1035]
**Is your feature request related to a problem? Please describe.**</br>

It would be nice if image scanning feature could be run as follows

```
kubescape scan --enable-host-scan \
          --kubeconfig /mnt/config-k8s-cls-test \
          --submit \
          --account=<account_id> \
          --client-id=<client_id> \
          --secret-key=<secret_key>
```

Currently according the the documentation at https://hub.armosec.io/docs/configuration-of-image-vulnerabilities you have to install the kubescape helm chart in the scanner cluster in order to get image scanning to work.

If I execute the command above without installing the helm chart in the cluster I get an error
```
* failed to pull image scanning data: no vulnerabilities found for any of the images. for more information: https://hub.armosec.io/docs/configuration-of-image-vulnerabilities
```
and controls related to image vulnerabilities are skipped
```
...
| High     | Workloads with Critical vulnerabilities exposed to external traffic                                                       |        0         |         0          |       0       |   skipped*   |
...
```

No data are submitted to the Armo dashboard
![image](https://user-images.githubusercontent.com/20891620/212287030-08021261-e385-423e-ac31-91fd70d3f15c.png)

**Describe the solution you'd like.**</br>
I would expect this command
```
kubescape scan --enable-host-scan \
          --kubeconfig /mnt/config-k8s-cls-test \
          --submit \
          --account=<account_id> \
          --client-id=<client_id> \
          --secret-key=<secret_key>
```
to create proper kubescape deployment in the target cluster set up with given credentials so that the image scan can be performed.

**Comment by matthyx** [comment]
@MMquant do you mean like if `kubescape` command could install all components as `helm install` would do?

**Comment by MMquant** [comment]
@MMquant yes - if it is even possible.

**Comment by matthyx** [comment]
We'll discuss that with @yossi77 and @dwertent to check if that makes sense, I cannot promise anything.
Thanks for the suggestion 👍

**Comment by vladklokun** [comment]
Just for posterity, this is a topic that frequently comes up.

We have brought it up previously, and the consensus was that the Kubescape CLI tool scans clusters for misconfigurations, not vulnerabilities. When you want to scan for vulnerabilities, we offer a separate set of tools — the Kubescape Helm chart, also known as the in-cluster components. Kubescape CLI does not communicate with in-cluster components, and does not submit vulnerability data to the ARMO Platform. However, the Helm chart does.

**Comment by vladklokun** [comment]
> do you mean like if kubescape command could install all components as helm install would do?

> yes - if it is even possible.

@MMquant 

Would you expect this to happen during `kubescape scan` or like a separate command, as  in `kubescape deploy-components && kubescape scan`? Or something else?

**Comment by MMquant** [comment]
@vladklokun It could be integrated in the `scan` subcommand. The user could just provide additional flag `--enable-image-scan` which would deploy components and perform the image scan.

Currently I'm using something like this

```
kubescape scan \
          --enable-host-scan \
          --enable-image-scan \
          --cluster-name "${cluster}" \
          --kubeconfig /configs/${cluster}/root/.kube/config \
          --disable-color \
          --format pretty-printer \
          --output "/kubescape/${cluster}" \
          --submit \
          --account=<account_id>
```

**Comment by dwertent** [comment]
We can approach this issue in 2 ways - 
1. Kubescape CLI will scan for misconfigurations and deploy the helm chart components for scanning the images 
2. Kubescape CLI will scan for misconfigurations and for CVEs in images.
  
I think the solution here is to add in the Kubescape CLI the ability to scan images, and not deploy the helm charts.
This is in our backlog for a while now but we do not yet have an estimation of when we will develop this capability 

/cc @amirkCA , @yossi77 

This has been requested multiple times in the past: #598 , #287 , #668

**Comment by dwertent** [comment]
This will be supported once we release the #1320.
