### ISSUE TITLE
Slack integration in https://cloud.armosec.io doesn't work

### ISSUE THREAD

**Issue by MMquant** [kubescape/kubescape#1038]
# Description

The Slack integration in https://cloud.armosec.io doesn't work. The Slack settings at https://cloud.armosec.io/settings/integrations/3rd-party-apps/slack _cannot be set_.

# Environment

Tested in
* Firefox 108.0.2 (64-bit) OS X
* Chrome Version 108.0.5359.124 (Official Build) (x86_64) OS X
 
# Steps To Reproduce

1. Create a Slack app according to the instructions at https://cloud.armosec.io/settings/integrations/3rd-party-apps/slack  
Token scopes
![image](https://user-images.githubusercontent.com/20891620/212464370-3e372fb8-725f-48b9-951a-475daf10dbd8.png)
Bot User OAuth Token
![Screenshot 2023-01-14 at 9 57 46](https://user-images.githubusercontent.com/20891620/212464413-c0d5bb60-c306-4864-ad02-77259d08803e.png)

2. Insert the token into the _Insert Token_ field at https://cloud.armosec.io/settings/integrations/3rd-party-apps/slack and click _Set Notifications_.
![Screenshot 2023-01-14 at 10 00 03](https://user-images.githubusercontent.com/20891620/212464516-6a5026a3-fd09-487b-8e7a-105a0a2eddd6.png)
Token gets saved successfully.

3. Now If you want to set the Slack channel in _Scan notification_ or _Risk scan increasing_ fields the backend returns error 400.
![image](https://user-images.githubusercontent.com/20891620/212464585-139d36cc-2097-4b67-bed4-a322fee0ede5.png)
After clicking Set Notifications the settings are not saved and if you inspect the browser console output you get
![Screenshot 2023-01-14 at 10 16 58](https://user-images.githubusercontent.com/20891620/212465090-cb037402-89ce-43e2-b630-88cb4b6bffc8.png)
![Screenshot 2023-01-14 at 10 18 20](https://user-images.githubusercontent.com/20891620/212465101-3782a792-3a45-4e55-831f-2e691f5ce7ac.png)

Note that #devops-bot channel exists already, it's a private channel and it has the _devops-bot_ app integrated
![image](https://user-images.githubusercontent.com/20891620/212464746-8795b75b-acdf-4697-8887-47be5f134acc.png)

# Expected behavior
I would expect the web app at https://cloud.armosec.io/settings/integrations/3rd-party-apps/slack to save settings successfully without errors.

# Actual Behavior
Settings will not get saved due to the HTTP 400 error.

**Comment by MMquant** [comment]
The error 400 message is quite confusing because the **Channel ID** is a string in a form of C03J55UFGD2 mapped to each Slack channel. The **Channel name** is the actual name of the channel ie. _devops-bot_. However the channel ID is an invalid input in _Scan notifications_ and _Risk scan increasing_ fields.

**Comment by dwertent** [comment]
Thank you for reporting.
@Bezbran Can you please take a look?

**Comment by Bezbran** [comment]
Hi @MMquant, thanks for reporting this.
We will check it and will let you know.

**Comment by craigbox** [comment]
This is an issue relating to ARMO Platform, which is now a separate project to Kubescape.  If you're still having this issue, there is a chat box in the ARMO application where it can be raised.  Thanks!
