### ISSUE TITLE
Kubescape errors when scanning with `--use-artifacts-from`

### ISSUE THREAD

**Issue by vladklokun** [kubescape/kubescape#1040]
# Description

Kubescape aborts with an error when scanning with the `--use-artifacts-from` flag.

# Environment
OS: `Ubuntu 22.04` 
Version: `Your current version is: v2.0.183 [git enabled in build: true]` 
 
# Steps To Reproduce
1. Install Kubescape
2. Download artifacts by running `kubescape download artifacts`
3. Launch a scan of a file / cluster / anything by running `kubescape scan --use-artifacts-from="~/.kubescape"`
4. Observe

# Expected behavior
Kubescape scans the input with the provided artifacts.

# Actual Behavior
Kubescape exits with the following error:
```
$ ./kubescape-ubuntu-latest scan --use-artifacts-from="$HOME/.kubescape"
[info] Kubescape scanner starting
[warning] Kubernetes cluster nodes scanning is disabled. This is required to collect valuable data for certain controls. You can enable it using the --enable-host-scan flag
[info] Downloading/Loading policy definitions
[fatal] missing required input framework name
```

**Comment by fredbi** [comment]
@vladklokun @dwertent  I strongly suspect that this behavior was introduced by my PR #1013,
as the behavior is stricter.
I can try to fix this.

I believe that in the absence of a legit framework, some default value should be adopted. What do you think?

**Comment by fredbi** [comment]
ok I've nailed it. I'll push a PR shortly. Just need to write up some additional unit test. cc: @vladklokun @dwertent

**Comment by vladklokun** [comment]
@fredbi thank you! You can assign me as a reviewer and I will follow the PR.

**Comment by fredbi** [comment]
@vladklokun  yes sure. Apologies for having introducing this regression. Not an easy decision to introduce more strictness ...

**Comment by fredbi** [comment]
@vladklokun I cannot assign reviewers, just cc-ed you in #1046

**Comment by vladklokun** [comment]
@fredbi It’s all good! Regressions are just a fact of life :man_shrugging: 

And considering your great contribution when you refactored that code and provided commendable test coverage, I should rather thank you for making this difficult decision :)
