### ISSUE TITLE
perf: kubernetes resources scanning in parallel

### ISSUE THREAD

**Issue by fredbi** [kubescape/kubescape#1047]
## Overview
Parallel scanning - part 1: k8s resources

## Problem
When scanning my cluster, even if it's small, it takes quite some time to wait on the k8s resources to scan.

## Solution
We may instead easily run such resource retrieval in parallel.

## Alternatives
Making a fancier spinner :).

## Additional context
* k8s resources are not the only object that could benefit from a similar approach.
* for the moment, all resources are buffered in memory structures - perhaps later we'll have to rework this interface and stream results rather than keeping everything in memory
* again, requires more testing (in particular, using the -race option becomes useful)

**Comment by fredbi** [comment]
I've tested locally and the speed-up is nice with my clusters sitting on the other side of the Atlantic Ocean...
cc: @dwertent @matthyx @vladklokun

**Comment by matthyx** [comment]
You can scan this repo and see how painfully slow that is: git@bitbucket.org:matthyx/ks-testing-public.git

**Comment by fredbi** [comment]
@matthyx I did not run formal benchmarks. Just scanning my far-away clusters and exploring the different steps of the scan process sequentially. Not saying this part is the slowest, but I felt it was a low-hanging fruit for // operations.
I am not so much focused on gc for now, but more on API calls to the cluster.

**Comment by matthyx** [comment]
Hmm, I fear this is a premature optimization... so far our biggest problem comes from memory consumption with big clusters.
Also the recommended way to scan your clusters is to run kubescape in-cluster with a [helm](https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-cloud-operator/README.md) install, so the network latency is mostly irrelevant.
If you do a proper benchmark, you'll see that GC during `OPAProcessor.updateResults` is responsible for more than half the time of running a scan of that [repo]([git@bitbucket.org](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=git@bitbucket.org):matthyx/ks-testing-public.git), and that work is single-threaded.

**Comment by matthyx** [comment]
To be discussed with @dwertent but I fear introducing parallel processing blindly might make things more difficult to debug and maintain.

**Comment by fredbi** [comment]
Interesting. OK, I'll take a look at that part, just out of curiosity.
Anyhow, you may take some inspiration from my PR and see how errgroup makes it easy to perform API calls in parallel.
Ok with you explanation. You may well close this and the associated PR. No worries.

**Comment by fredbi** [comment]
@matthyx I've taken a quick look at the problem you described above OPAProcessor.updateResults
I did not test your big stuff yet, but just locally.
With a quick optimization on how exceptions are detected, I could divide by 10 the allocated space and by more than 20 the number of allocs.  Next week, I am going to to try a bit harder. We should be able to alleviate most of this pain. Hang on!

**Comment by matthyx** [comment]
Awesome, thanks for looking at this... I wish I had time dedicated in sprints to help you, but that might come in Q1.

**Comment by dwertent** [comment]
We have ended up reverting this because of the high memory usage we encountered.
