### ISSUE TITLE
Make nicer table output

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1059]
## Overview

```
+-------------------+
| I look like this. |
+-------------------+
```

## Problem
I would rather use Unicode characters to draw nicer lines.

## Solution
https://github.com/olekukonko/tablewriter/pull/207

**Comment by matthyx** [comment]
cc @slashben

**Comment by sassukeuchiha** [comment]
hey can I work on this issue?

**Comment by matthyx** [comment]
hi @sassukeuchiha sure, but it depends on a change not yet merged...
I know @fredbi was working on a fork (https://github.com/fredbi/tablewriter) you might want to sync with him

**Comment by sassukeuchiha** [comment]
Sure will connect with @fredbi 
Certainly @craigbox . 
Trying to find my first issue....but it seems many folks are already working on things

**Comment by craigbox** [comment]
A good way to get involved is to run the software and look for something you would like fixed for yourself.   For example, when I run `kubescape scan`, I get a spinning wheel between the output lines.  Sometimes it gets stuck!

```
[success] Accessed to Kubernetes objects
[info] Requesting images vulnerabilities results
[success] Requested images vulnerabilities results
[info] Requesting Host scanner data
◐[info] Scanning. Cluster: docker-desktop
```

If I was going to start hacking on Kubescape that's the first thing I would figure out.  You figure out the thing that you think might be interesting 😊

**Comment by craigbox** [comment]
Another possible solution: https://github.com/jedib0t/go-pretty

**Comment by ramettan** [comment]
Hi, is anyone still working on this issue? I would like to contribute.

**Comment by craigbox** [comment]
Until there is code or a design on the table, all contributions are welcome :)

**Comment by ramettan** [comment]
Hi @craigbox , can you give me the path inside the code base where current table design is implemented. I am pretty new to kubescape code. Thanks.

**Comment by matthyx** [comment]
@ramettan if you search for `tablewriter` in the code:
https://github.com/search?q=repo%3Akubescape%2Fkubescape+tablewriter&type=code

**Comment by kiratsingh98** [comment]
I will take the lead in achieving the request. // @craigbox @matthyx

**Comment by matthyx** [comment]
Awesome, thanks @kiratsingh98 !

**Comment by kiratsingh98** [comment]
What are your thoughts on using this one?

https://github.com/aquasecurity/table

**Comment by craigbox** [comment]
I think we would want to see a prototype before changing implementation.  Why this over one of the others, for example?  Is it actively maintained?

**Comment by kiratsingh98** [comment]
1. aquasecurity/table -> is under regular maintenance and can be easily customized. 
2. olekukonko/tablewriter is not currently being actively maintained and has not been released yet. It is related to the [PR](https://github.com/olekukonko/tablewriter/pull/207) that you mentioned in the issue description.
3. jedib0t/go-pretty -> is actively maintained, although some of the tables may have issues with boxing.

We have the option to proceed with either option 1 or 3. I will share a prototype shortly to demonstrate how the table will appear.
