### ISSUE TITLE
LFX opportunity: Implement security controls based on penetration testing best practices

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1072]
Kubescape covers different hardening guidelines around Kubernetes: NSA-CISA, MITRE and CIS. Detection capabilities of potential security issues could be even more enriched by researching pen-testing tools and practices regarding Kubernetes and implementing these as controls. An example pen-test writeup is [here](https://hacktricks.boitatech.com.br/pentesting/pentesting-kubernetes). This and others could help define a set of “offensive” controls to complement the “defensive” controls we have today.

(This issue is being submitted for the 2023 Mar-May [LFX Mentorship program](https://github.com/cncf/mentoring/tree/main/lfx-mentorship).)

**Comment by tiger-yash** [comment]
Hey @craigbox!
I am interested in this and would like to potentially contribute. I don't have a lot of idea on this, but I would like to learn. Please guide and confirm the pre-requisites.

**Comment by sunstonesecure-robert** [comment]
The most recent K8s audit was completed and is just going through the final
SGC and CNCF reviews - a couple of the CVEs were already released - but the
many other suggestions/findings could be rolled into this effort. I am
hoping we will be able to release the findings +/- before Kubecon EU. Once
the report is approved for release, I'm happy to host a focused debrief for
this effort.  We will certainly do a general debrief at sig-security, but
an offense oriented focus would be very interesting.

I will note that in investigating many of the more obscure parts of K8s
touched by the audit - there be many dragons. I didn't have time to
research all of them further but had some anxiety about some of the code I
reviewed, and issues going back to 2017 that were closed for seemingly no
reason, or no one remembered to remove lifecycle-rotten...many of these can
also be added to the offensive research/control discovery.  We hope to
continue smaller, more targeted, iterative audits going forward and I think
informing those with real world offensive intel is the most effective way
to zero in on real vs. academic concerns.

If the LFX mentorship goes forward, and a slack channel opens up on this
count me in.

**Comment by craigbox** [comment]
@sunstonesecure-robert  Thanks Robert! This would be a really interesting tree to shake.  As a complementary CNCF project, we could look to get Kubescape and its control library to the point where it's a bit like https://sonobuoy.io/ for conformance testing.

@tiger-yash This is our first time as a mentoring organization, but I would hope to find a candidate who had some experience with security (hacking, if you like) and using Kubernetes, and possibly developing Go code.

**Comment by pranav767** [comment]
Hey @craigbox I do have a security (hacking) background and would love to work on this if you haven't found a candidate yet.

**Comment by craigbox** [comment]
@pranav767 The applications closed last week, and Ben is busy sifting through them!

**Comment by pranav767** [comment]
Ohh cool thanks for the update 😄

**Comment by ananthulasrikar** [comment]
@craigbox : May I please know when can we expect the results?
