### ISSUE TITLE
Regular Expression support for exclude namespaces and/or include-namespaces

### ISSUE THREAD

**Issue by adamjk-dev** [kubescape/kubescape#1076]
## Overview
It would be great to have regex support (sorry if it is today, I didn't see it in any issues or docs), for the include and exclude namespaces options. For clusters with large amounts of namespaces or known patterns for app-specific namespace vs. k8s-provided namespaces etc.

## Problem
Let's say I want to scan all namespaces on a cluster except for a pattern like "internal-*"

## Solution
I would want kubescape to scan all namespaces that didn't match "internal-*" on the cluster

## Alternatives
N/A

## Additional context
I am happy to explain further, but I wanted to verify that this wasn't possible today first. Then, I hope the request makes sense for regex support on namespace inclusion/exclusion.

**Comment by Bezbran** [comment]
Hi @adamjk-dev, kubescape has the [exceptions mechanism](https://github.com/kubescape/kubescape/tree/master/examples/exceptions), which supports regex out of the box.
Is it fits your needs?

**Comment by adamjk-dev** [comment]
Actually, looking at this... I would prefer to have the ability to "exclude namespaces" on a RegEx, so that those namespaces aren't scanned at all or part of the report.

The exceptions mechanism (still trying to get it to run with mine), seems to ignore them in the scoring, but the way I read it, it would still scan those namespaces.

I, for example, want to scan all namespaces on a cluster except for those named "openshift-.*" (it is a RedHat OpenShift cluster, and all of those namespaces are upstream controlled, so I am more interested in skipping those namespaces altogether on my cluster).

Does that make sense?

**Comment by dwertent** [comment]
Hi @adamjk-dev yes, this makes sense but this is exactly why we added the exception mechanism. With the exceptions, the resources will be scanned but also ignored.
In any case, we will definitely consider your request. 

You mentioned that it is not working for you, please feel free to share more about it here or on our Slack channel.

/cc @yossi77 @giblix

**Comment by adamjk-dev** [comment]
Sure thing, I grabbed latest and it looks like it worked as follows (I don't see anything about namespaces following openshift-* in my output report):

Exclusions file:
```
⇒  cat kubescape-exclusions.json                                                           [8/02/23| 7:50AM]
[
    {
        "name": "ignore-kube-namespaces",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "namespace": "openshift-.*"
                }
            }
        ]
    }
]
```

Command run:
```
⇒  kubescape scan --enable-host-scan --verbose --exceptions kubescape-exclusions.json --format html --output kubescape-report.html
```

**Comment by Bezbran** [comment]
@adamjk-dev it it worked for you, can we close this issue?

**Comment by adamjk-dev** [comment]
Yes, will do.
