### ISSUE TITLE
Host Scanners can't run on locked down cluster with standard CLI flow

### ISSUE THREAD

**Issue by thejosephstevens** [kubescape/kubescape#1091]
## Overview
I downloaded the kubescape CLI to try scanning my cluster with `kubescape scan --enable-host-scan` and ran into issues, specifically with the host portion of the scan because the scanner pods failed to create.

## Problem
We've already locked down our cluster with OPA Gateway, so when a new namespace was created by the CLI it didn't have any exemptions applied to it to allow extra security permissions. Specifically the daemonset pods failed to create on:
* host-filesystem
* hostPath
* privileged
* seccomp
* host-namespace
* host-network-ports
* capabilities

## Solution
We do have specific namespaces that are protected and allowed to use certain high-sensitivity permissions (e.g. kube-system). If you add a `--host-scanner-namespace` flag to the CLI (or whatever name) to override the install namespace of the scanners then we can easily select a trusted namespace and run in that one.

## Alternatives
There are probably other solutions, not sure offhand what they would be. Overriding the namespace seemed easiest

## Additional context
n/a

**Comment by Bezbran** [comment]
Hi @thejosephstevens,
Thanks for bringing this up.
Can you take a look on [this flag](https://hub.armosec.io/docs/host-sensor#customize-the-host-scanner) and see if it fits your needs?
Anyways, I suggest not running the host sensor at the same namesapce as other workloads, since kubescape is deleting the host-sensor namespace by the end of the scan.

**Comment by yuleib** [comment]
hey @thejosephstevens , did the above solution worked for you ?

**Comment by thejosephstevens** [comment]
> Can you take a look on [this flag](https://hub.armosec.io/docs/host-sensor#customize-the-host-scanner) and see if it fits your needs?

Ah, I hadn't seen this, yeah, I think this should work fine. This should even let me customize the namespace annotations to exclude it from admission webhook requirements, which would make it work.

> Anyways, I suggest not running the host sensor at the same namesapce as other workloads, since kubescape is deleting the host-sensor namespace by the end of the scan.

Does this apply even if you use the template file to deploy the host scanner to a different namespace? Is the script just applying the template and then deleting the template? Because if it's doing that it's totally fine, if it's determining the namespace of the scanner as it applies and then deleting the namespace regardless of whether it's managed that seems risky.

I can work around it now that I know about it, but I'd be pretty frustrated if that caught me by surprise.
