### ISSUE TITLE
can‘t get the scan result when using submit or keep-local option

### ISSUE THREAD

**Issue by yf-odyssey** [kubescape/kubescape#1092]
# Description
<Dear all， I find a strange problem when I launch a scan with submit or keep-local option>

# Environment
OS version : Centos7
Kubescape version : v2.0.182/183
 
# Steps To Reproduce

1. I login into the centos and lanuch a kubescape scan without **submit** or **keep-local** option, it works normally and generate the scan result. The screenshot is as below.
![image](https://user-images.githubusercontent.com/33337184/217712327-8bbf9ef0-1faf-4aea-b83e-1a86114fc9d7.png)

2. I lanuch a kubescape scan again with the submit or keep-local option, it said "**Kubescape did not scan any of the resources, make sure you are scanning valid kubernetes manifests** ". The screenshot is as below.
![image](https://user-images.githubusercontent.com/33337184/217712822-45a2fd60-2a8c-441d-9d6f-bee8200b2402.png)

![image](https://user-images.githubusercontent.com/33337184/217714347-1b77039c-d0fa-4b8f-a4f3-31c07dcf52e9.png)

3. The result is the same whether I run the  scan using standard or custom framwork. The custom framework scan screenshot is as below.
![image](https://user-images.githubusercontent.com/33337184/217714445-28168495-2a79-4052-9086-c4ba761efc06.png)

Could you help me to find out the problems? Thanks a lot!

**Comment by yf-odyssey** [comment]
I have read the documents about the options(https://hub.armosec.io/docs/options). I noticed that according the documents. kubescape will not submit the result to SaaS platform defaultly. But I find that if you don't use the submit options , it will submit the result. And I never use the **--submit true** option.
![image](https://user-images.githubusercontent.com/33337184/217727716-1249bd31-d4de-4c29-9ad5-ec62fd99a289.png)

![image](https://user-images.githubusercontent.com/33337184/217727816-5b255c1f-bd97-4bb1-a66f-48c7255f1a04.png)
![image](https://user-images.githubusercontent.com/33337184/217727890-3fdd47c0-81b5-4e4b-a9ee-237667232426.png)

I also try to use the **--keep-local** options and it seems doesn't work

**Comment by dwertent** [comment]
@yf-odyssey The `submit` and `keep-local` flags are boolean flags, meaning, you should not add `true`/`false` when using the flag.
When the flag is in use, the value is `true`, and when it is not in use the value is `false`.

**Comment by yf-odyssey** [comment]
> @yf-odyssey The `submit` and `keep-local` flags are boolean flags, meaning, you should not add `true`/`false` when using the flag. When the flag is in use, the value is `true`, and when it is not in use the value is `false`.

@dwertent  Thanks for your quick and patient reply. I test as you said  and it works. It seems I misunderstand these two options. Thanks a lot!
