### ISSUE TITLE
Do not set OTEL_COLLECTOR_SVC in host-scanner DaemonSet if otel is not enabled

### ISSUE THREAD

**Issue by matthyx** [kubescape/kubescape#1106]
# Description

Since we added otel options to the Helm chart, I hardcoded `OTEL_COLLECTOR_SVC` in host-scanner's `hostsensor.yaml` file.
This causes errors in host-scanner's logs confusing users.

# Environment
OS: ` ` 
Version: ` ` 
 
# Steps To Reproduce

# Expected behavior

`OTEL_COLLECTOR_SVC` should only be set for host-scanner if present inside kubescape's env vars.

# Actual Behavior

# Additional context

https://github.com/kubescape/kubescape/blob/master/core/pkg/hostsensorutils/hostsensor.yaml#L41-L43

**Comment by dwertent** [comment]
@matthyx I think Kubescape should add this environment variable if it is set and not have it by default. What do you think?

**Comment by matthyx** [comment]
As of today it's removed... should we dynamically add it when applying the daemonset YAML?
