### ISSUE TITLE
Go all

### ISSUE THREAD

**Issue by Turuk3100** [kubescape/kubescape#1109]

**Comment by craigbox** [comment]
Hi @Turuk3100, I'm not sure what you're meaning to do here, but I can't tell it apart from malicious behaviour and your GitHub profile looks suspicious.  I'm going to close this issue for now but please feel free to reach out on [our Slack channel](https://www.armosec.io/blog/join-the-conversation-on-kubescapes-slack-channel/) if I can help you get going.

**Comment by craigbox** [comment]
Your messages are coming through on a bug report on some software hosted on GitHub.  I can't see an obvious reason as to why sorry. Perhaps someone might have used your phone number or e-mail address by mistake or fraudulently?  You should have a look at the account https://github.com/havardj900 and see if you can ask GitHub to close it down.
