### ISSUE TITLE
kubekiller scenario not work: terminal show connection lost 

### ISSUE THREAD

**Issue by essie-chiang** [kubescape/kubescape#1122]
# Description

kubekiller scenario not work: terminal show connection lost 

# Environment
OS: `Macos: Ventura 13.1 ` 
Version: `no kubescape page availableto run the command ` 
Firefox: 110.0

 
# Steps To Reproduce

1. Go to all the pages, for example https://killercoda.com/saiyampathak/scenario/kubescape
2. The terminal show connection lost

# Expected behavior

The terminal should work.

# Actual Behavior

![image](https://user-images.githubusercontent.com/3705838/221826880-59c05f55-6e1d-4a8b-aeec-c4b0b0309b86.png)

# Additional context

**Comment by nitishchauhan0022** [comment]
@essie-chiang could you please check it again,it is working fine, i just checked.
