### ISSUE TITLE
Reports: should properly authenticate before uploading reports

### ISSUE THREAD

**Issue by fredbi** [kubescape/kubescape#1132]
## Overview
Improve the security of the SaaS endpoints.

## Problem
I've noticed that the report upload process (in` core/pkg/resultshandling/reporter/v2` ) does not authenticate calls to the API to POST reports. The only access control is based on the static customer GUID, which could leak or become compromised.

## Solution
IMHO, we should POST with an Authorization token, e.g. the "invitationToken" retrieved when collecting the tenant.

Of course, an additional change is required on the server side to check the token's validity.

I am about to propose a PR to post reports with a request like that:
```` 
POST /k8s/v2/postureReport?clusterName=test&contextName=test&customerGUID=1e3ae7c4-a8bb-4d7c-9bdf-eb86bc25e6bb&reportGUID=cbabd56f-bac6-416a-836b-b815ef347647 HTTP/1.1
        Host: 127.0.0.1:42201
        Accept-Encoding: gzip
        Authorization: Bearer auth-token
        Content-Length: 49478
        Content-Type: application/json
        User-Agent: Go-http-client/1.1
```` 
## Alternatives
They is another way:
* use the "secretKey" as an API key (if compromised, it is always possible to rotate it)

**Comment by fredbi** [comment]
cc @dwertent @matthyx

**Comment by matthyx** [comment]
@Bezbran is that something to consider in the future?

**Comment by Bezbran** [comment]
Definitely

**Comment by matthyx** [comment]
this is covered by the future work on access tokens
