### ISSUE TITLE
Package manager support: RPM

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1142]
Support at least `yum` and `zypper` installations by building an RPM package with every Kubescape release and updating package indexes.

**Comment by HollowMan6** [comment]
Package installation should now be available already with dnf/zypper (according to the [guides here](https://software.opensuse.org//download.html?project=home%3Ahollowman&package=kubescape)):
```bash
zypper addrepo https://download.opensuse.org/repositories/home:hollowman/openSUSE_Tumbleweed/home:hollowman.repo
zypper refresh
zypper install kubescape
```

```bash
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:hollowman/Fedora_37/home:hollowman.repo
dnf install kubescape
```

(`yum` actually has been superseded by `dnf`)

**Comment by craigbox** [comment]
Great! The end state should be a public project called 'kubescape', taking binaries that come from our release pipeline and  automatically updating them when we do a release.

(Then we can look at [SLSA compliance](#1033) too 😁)

I suggest that you create some pages on the [GitHub wiki](https://github.com/kubescape/kubescape/wiki) that explain how the build pipeline works, from release through OpenSUSE and then to a user's installation.

kubescape.spec should be in this repo and synced to the build service if possible.

**Comment by HollowMan6** [comment]
Hi @craigbox ! Yeah, we can create an account with the user name `kubescape` as the org account (I wonder if the org admin would like to help create this account, as I guess it requires some email verification)  https://idp-portal.suse.com/univention/self-service/#page=createaccount

After we have the account, I will begin transfering the package located in my project to the org project (https://build.opensuse.org/package/show/home:hollowman/kubescape -> https://build.opensuse.org/package/show/home:kubescape/kubescape)

In addition, as you mentioned "kubescape.spec should be in this repo", I'm actually open to two options that whether to merge everything at https://github.com/HollowMan6/kubescape-deb-rpm into this kubescape main repo, or just keep it in a separate repo just like the [homebrew tap one](https://github.com/kubescape/homebrew-tap). If it's the former one, I can help submit a PR, and if it's the later, I can help transfer that repo into the kubescape org.

For SLSA compliance, I think the build process now is at least SLSA 2 and maybe already SLSA 3 compliant, as it's fully scripted and can synced to the open build service automatically with the help of the CI here: https://github.com/HollowMan6/kubescape-deb-rpm/actions/runs/4402322353

After everything above have settled down, I will create some pages on the [GitHub wiki](https://github.com/kubescape/kubescape/wiki) to explain how the build pipeline works, from release through OpenSUSE and then to a user's installation.

**Comment by craigbox** [comment]
I've registered an account named `kubescape` and I'm awaiting guidance from someone at SUSE as to how I can use this account without `home:` as a prefix.

**Comment by HollowMan6** [comment]
[GitHub wiki](https://github.com/kubescape/kubescape/wiki) is now ready to explain how the build pipeline works, from release through OpenSUSE and then to a user's installation.
- https://github.com/kubescape/kubescape/wiki/Publishing
- https://github.com/kubescape/kubescape/wiki/Installation

**Comment by craigbox** [comment]
great: lets get the packaging repo under kubescape and we can close this out!

**Comment by HollowMan6** [comment]
@craigbox Just like #1143 , I think we can close this as well.

**Comment by craigbox** [comment]
Tested OK with Fedora 37 and 38 images.
