### ISSUE TITLE
Add progress bar when downloading cloud providers resources

### ISSUE THREAD

**Issue by alegrey91** [kubescape/kubescape#1145]
## Overview
We recently implemented this [feature](https://github.com/kubescape/k8s-interface/pull/27) in order to retrieve more data from cloud providers (specifically aws). This is great, since we can have better controls on [regolibrary](https://github.com/kubescape/regolibrary) for **cis-eks** framework. By the way, this enhancement incremented the running time of scans, so for this reason we should add a progress bar in order to inform the user that **kubescape** is downloading data.

## Problem
When scanning clusters managed by cloud providers, **kubescape** take ~= 10 minutes to run, in order to retrieve all the aws policies and make logic on it.

## Solution

Adding a progress bar during the download of these data, we can properly inform the final user about the status of the run.
Here's an example:
```
kubescape scan framework cis-eks-t1.2.0
[info] Kubescape scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
[info] Downloading/Loading policy definitions
Cloud resources: 70% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                 | (708/1024, 54 it/s)         
```

**Comment by Saravana-PS** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by alegrey91** [comment]
Hi @Saravana-PS, you are more than welcome! Ping me if you need a better explanation about the problem.

**Comment by Saravana-PS** [comment]
> Hi @Saravana-PS, you are more than welcome! Ping me if you need a better explanation about the problem.

Sure @alegrey91, I will let you know. I'm new to open source and I could some help along the way. Do we have any community group or shall I ping you my queries here itself?

**Comment by alegrey91** [comment]
> 

For questions regarding **kubescape** we have **slack** channels:
* https://cloud-native.slack.com/archives/C04EY3ZF9GE
* https://cloud-native.slack.com/archives/C04GY6H082K

**Comment by Saravana-PS** [comment]
Can you please explain more about the problem?

As per my understanding, we need to only add a progress bar after the logging information "[info] Downloading/Loading policy definitions". I'm currently going through the https://github.com/kubescape/kubescape/blob/master/core/core/scan.go file. Kindly confirm me if I'm going in the right direction. Kindly advice me if I need to look into some other files apart from the ones in the core package. Thanks in advance.

**Comment by alegrey91** [comment]
Hi @Saravana-PS, yes the scope is only to add the progress bar. When we scan **eks** clusters it takes a while. So, it is important to inform the final user that kubescape is not stuck.
There are other progress bar in the code base (for example for the controls), so the idea is to check how these have been implemented and replicate the implementation here.
The file that you mentioned is correct, but probably needs more implementations in order to allow the functions for cloud providers to host the progress bar.
If you have more doubt than before, feel free to ask more 😅. I can understand this could be confusing.

**Comment by Saravana-PS** [comment]
@alegrey91 Sure, thanks for being so kind. I really needed this kind of support. If anything comes up, I will reach out to you.

**Comment by Saravana-PS** [comment]
@alegrey91 When I have gone through the code base, I got to know that the ProgressHandler struct, which is used to display progress bars for long-running tasks is present in the https://github.com/kubescape/kubescape/blob/master/core/cautils/display.go file . But there is only one place in which the NewProgressHandler() function is being called. PFB.

ctxOpa, spanOpa := otel.Tracer("").Start(ctx, "opa testing")
	deps := resources.NewRegoDependenciesData(k8sinterface.GetK8sConfig(), interfaces.tenantConfig.GetContextName())
	reportResults := opaprocessor.NewOPAProcessor(scanData, deps)
	if err := reportResults.ProcessRulesListenner(ctxOpa, **cautils.NewProgressHandler("")**); err != nil {
		// TODO - do something
		return resultsHandling, fmt.Errorf("%w", err)
	}
	spanOpa.End()

The above code block is present under the https://github.com/kubescape/kubescape/blob/master/core/core/scan.go file. Kindly let me know what did you mean by the "controls" earlier. Correct me if I'm looking in the wrong direction. Thanks

**Comment by alegrey91** [comment]
Hi @Saravana-PS , I'm not sure about this, so please make your checks before to start implementing it.
But, you should add a parameter to host the progress bar in this function: https://github.com/kubescape/kubescape/blob/master/core/pkg/policyhandler/handlenotification.go#L38
It is called in [scan.go](https://github.com/kubescape/kubescape/blob/master/core/core/scan.go) file as well as the other one. This function should be responsible of collecting information of cloud providers and other things.

**Comment by alegrey91** [comment]
> Hi @alegrey91 , Regarding https://github.com/kubescape/kubescape/blob/master/core/pkg/policyhandler/handlenotification.go#L38, Are you expecting the following kind of implementation.
> 
> func (policyHandler *PolicyHandler) CollectResources(ctx context.Context, policyIdentifier []cautils.PolicyIdentifier, scanInfo *cautils.ScanInfo, progressHandler *cautils.ProgressHandler) (*cautils.OPASessionObj, error) { opaSessionObj := cautils.NewOPASessionObj(ctx, nil, nil, scanInfo)
> 
> ```
> // validate notification
> // TODO
> policyHandler.getters = &scanInfo.Getters
> 
> // get policies
> if err := policyHandler.getPolicies(ctx, policyIdentifier, opaSessionObj); err != nil {
> 	return opaSessionObj, err
> }
> 
> err := policyHandler.getResources(ctx, policyIdentifier, opaSessionObj)
> if err != nil {
> 	return opaSessionObj, err
> }
> if (opaSessionObj.K8SResources == nil || len(*opaSessionObj.K8SResources) == 0) && (opaSessionObj.ArmoResource == nil || len(*opaSessionObj.ArmoResource) == 0) {
> 	return opaSessionObj, fmt.Errorf("empty list of resources")
> }
> 
> // update progress bar
> progressHandler.ProgressJob(1, "Collected resources")
> 
> // update channel
> return opaSessionObj, nil
> ```
> 
> }

Does it work? Did you test it?

**Comment by Saravana-PS** [comment]
Not yet. I will test it and let you know. I just wanted to understand if the above implementation is only change we need to make.

**Comment by alegrey91** [comment]
@Saravana-PS everithing ok from your side? Do you have any update?

**Comment by Saravana-PS** [comment]
@alegrey91 Yeah, everything is fine from my end. I will give you the update by today. Thanks

**Comment by alegrey91** [comment]
Great, ping me if you are blocked.
