### ISSUE TITLE
counter problem when using the exception feature

### ISSUE THREAD

**Issue by yf-odyssey** [kubescape/kubescape#1153]
# Description
Dear all， I met a strange problem when I using the exception feature

# Environment
OS version : Centos7
Kubescape version : v2.0.182/
 
# Steps To Reproduce
1. I login into the centos and lanuch a kubescape scan without exception option, the scan command and the scan result is as below.
**_kubescape scan framework neocrm --use-from /home/neocrm.json --controls-config ~/.kubescape/controls-inputs.json --format json --output clustername-03-15-1.json --keep-local_**
![image](https://user-images.githubusercontent.com/33337184/225591822-51c35b71-1cb5-4949-9b56-6f0d2f077f54.png)

2. I run scan again with  exception option, the scan command and the scan result is as below. I found that the failed resource works and counter is 0 now(control name :Host PID/IPC /privileges) . But the counter of other control changed.
**### kubescape scan framework neocrm --use-from /home/neocrm.json --controls-config ~/.kubescape/controls-inputs.json  --exceptions  /home/frank/kubescape/exceptions/exceptions.json --format json --output clustername-03-15-2.json --keep-local**
![image](https://user-images.githubusercontent.com/33337184/225592112-794269ec-10da-4db7-a5ba-cbafd99275e2.png)

  **Now I just notice why there is EXCLUDED RESOURCES counter? The first scan I not using the exceptions feature**. So I want to know the reasons. Thanks a lot!

**Comment by yf-odyssey** [comment]
I also uploaded the exception file.Pls help me find out .Thanks a lot !@dwertent @matthyx 

[
    {
        "name": "exclude-allowed-delete",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "namespace": "tigera-operator",
                    "name": "tigera-operator",
                    "kind": "ServiceAccount"
                }
            }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0031" 
            }
        ]
    }
]

**Comment by matthyx** [comment]
@yf-odyssey can you try with the latest [release](https://github.com/kubescape/kubescape/releases/tag/v2.2.5)?

**Comment by XDRAGON2002** [comment]
@yf-odyssey Hi!

Was the issue resolved or does it still persist?

**Comment by dwertent** [comment]
This is because Kubescape loads the exceptions either from a file or from the downloaded exceptions (but not both).
This behavior was not changed, therefor, you will still encounter this issue.

You can overcome it by first downloading the exceptions, and only then modifying the downloaded exceptions object.
```
kubescape download exceptions -o exceptions.json
```

**Comment by dwertent** [comment]
This is not a bug because this is the expected behavior as [explained here](https://github.com/kubescape/kubescape/issues/1153#issuecomment-1701166833)
