### ISSUE TITLE
GSoC 23 proposal: Design, build and document a generic security scan result API

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1172]
This issue relates to a **proposal** for a [Google Summer of Code](https://summerofcode.withgoogle.com/) mentorship project as [part of the CNCF organization](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md).  It has not yet been accepted. Please feel free to comment on this issue about how we might improve the proposal, but commenting here is not the same as applying to GSoC.

#### Design, build and document a generic security scan result API

- _Description_: Kubescape has the ability to submit scan results to a backend service, which can then store them and provide UIs to give insight over time as to a users' security posture. There is an implementation of this API by the commercial service that Kubescape's original creators, ARMO, runs. We would like to fully document this API, and improve it for future use cases, which may eventually have a wider scope than just Kubescape itself. If the student wants to extend the project, they could also build a sample backend to store data in-cluster using this API. (Please specify in your application if you are looking to work half or full time.)
- _Expected outcome_: An improved and fully-documented API for how to send scan results from a Kubescape client to a security backend service. 
- _Recommended Skills_: Go, OpenAPI
- _Mentor(s)_: [Craig Box](https://github.com/craigbox), [Ben Hirschberg](https://github.com/slashben)
- _Expected project size_: 175h for API only, 350h for API + sample backend
- _Difficulty_: Medium

**Comment by Tezas-6174** [comment]
Hello mentors!

I am Tejas, currently a junior at IIT Jodhpur. I am interested in working on this project. I am passionate about Cybersecurity and Open Source Development. Previously I have been working with open-source organizations like Hyperledger and 0chain. I am proficient in Python, C, C++, and JavaScript, and I also have some experience in web development and API. Recently, I have been learning Golang while working on several projects.

Regarding the project:
I understand how this API will help to improve the overall security of Kubernetes clusters by providing a way to collect, store, and analyze scan results from Kubescape. Could you provide more information on the expected features and design for the API that will be developed for submitting scan results from Kubescape to a backend service?

**Comment by shubham-singh-748** [comment]
hey i have strong foundation in html,css & have basics in javascript.
can you please what more skills i need to understand or contribute on this issue?
One more thing is that any slack or discord to interact with members?

**Comment by shubham-singh-748** [comment]
hey i have strong foundation in c++, html, css & have basics in javascript.

Can you please tell me what more skills is need to add on for understanding or contributing to the  issues?

One more thing is there any slack or discord channel to interact with you members?

**Comment by craigbox** [comment]
> What are the specific areas of improvement in the existing implementation by ARMO that are being targeted, and how can those improvements be achieved?

The format of the objects are described [here](https://github.com/kubescape/opa-utils/blob/master/reporthandling/v2/datastructures.go#L15).  The project will involve looking at what other data might conceivably need to be submitted by a security posture scanner and ensuring the API is generic enough to handle such.

> Also, could you provide more information on the expected features and design for the final API that will be developed for submitting scan results from Kubescape to a backend service?

[This is the current API](https://api.armosec.io/openapi/v2/docs).  The implementation of the backend service will have to store data such that it can retrieved as per that API, with whatever extensions are proposed above.

**Comment by craigbox** [comment]
> hey i have strong foundation in c++, html, css & have basics in javascript.
> Can you please tell me what more skills is need to add on for understanding or contributing to the issues?

As listed above, the recommended skills are [Go](https://go.dev/) and [OpenAPI](https://www.openapis.org/). 

> One more thing is there any slack or discord channel to interact with you members?

[#kubescape-dev on the CNCF Slack](https://kubescape.io/project/community/).

**Comment by 0xt3j4s** [comment]
1. What additional data is to be submitted to the security posture scanner is yet to be finalised, right?

    According to me, the data which can be added is given below (Please correct me if I am wrong):
        - User and Group information [Maintaining access control in the system]
        - Network traffic data [Monitoring network traffic flowing in and out of the system]
        - Application logs
        - Threat Intelligence data [data from external sources, such as known threat actors, malicious IP addresses, and other indicators of compromise]

2. Also, what is our priority? working on the improving the [existing API](https://api.armosec.io/openapi/v2/docs) i.e., adding one more endpoint for providing the user's security posture or building our own custom API that can be used not just for Kubescape?

**Comment by craigbox** [comment]
> 1. What additional data is to be submitted to the security posture scanner is yet to be finalised, right?
>    In my opinion, the data which can be added is given below (Please correct me if I am wrong):
>    - User and Group information [Maintaining access control in the system]
>    - Network traffic data [Monitoring network traffic flowing in and out of the system]
>    - Application logs
>    - Threat Intelligence data [data from external sources, such as known threat actors, malicious IP addresses, and other indicators of compromise]

The API has to be generic, and be able to handle more things.  That said, other things can be added later, or just be in a generic object: the goal for this project will be to tidy up the existing API and leave it open for further extension.

> 2. Also, what is our priority? Working on improving the [existing API](https://api.armosec.io/openapi/v2/docs), i.e., adding one more endpoint for providing the user's security posture or building our custom API that can be used not just for Kubescape?

I think you will do the former, and prepare for the latter, but not have enough time to do this.  What we have could act as a proposal to (say) CNCF TAG Security on a standard API that other projects could use, but getting agreement on that API will take longer than the summer.  That said, if someone wanted to stay involved later and drive this, it would be an excellent way of demonstrating to future employers that you have the ability to be influential in the industry!

**Comment by 0xt3j4s** [comment]
I got it. For developing a generic security scan API, as of now, we can't fix what additional data can be submitted to the security posture scanner; we need to be flexible regarding the kind of data related to the security posture, the types of authentication or authorization, etc.

Due to the time constraint for the approval of the CNCF TAG Security, currently, we'll be working on improving the existing API. Later, I would like to extend this project further by building a standard API for other projects as well.

**Comment by craigbox** [comment]
Hi all,

The maintainers ultimately decided not present any candidates for this project to the GSoC.  This is not a commentary on the strength of the proposals, but rather the time we have to participate and our concern that this would end up being a major rewrite that we didn't have time to properly mentor during this term.  To that end, we won't be converting it to an LFX proposal, but we're ready to post up the projects we are putting forward for LFX now.

We look forward to your applications to that!

Thanks,
Craig
