### ISSUE TITLE
GSoC 23 proposal: Fully integrate Kubescape with Backstage

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1173]
This issue relates to a **proposal** for a [Google Summer of Code](https://summerofcode.withgoogle.com/) mentorship project as [part of the CNCF organization](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md).  It has not yet been accepted. Please feel free to comment on this issue about how we might improve the proposal, but commenting here is not the same as applying to GSoC.

#### Fully integrate Kubescape with Backstage

- _Description_: Kubescape is a platform that can scan clusters for configuration and vulnerability issues. Some work has been done to integrate Kubescape with Backstage, to present the data from a cluster. This project will build on that work by making Backstage a fully-supported method for interacting with Kubescape's in-cluster components and API server. If the student is interested the project could be extended to add a Grafana dashboard to display information in a similar fashion. (Please specify in your application if you are looking to work half or full time.)
- _Expected outcome_: A production-ready Backstage plugin for Kubescape in the [plugin marketplace](https://backstage.io/plugins/)
- _Recommended Skills_: TypeScript, React, Go 
- _Mentor(s)_: [Craig Box](https://github.com/craigbox), [Ben Hirschberg](https://github.com/slashben)
- _Expected project size_: 175h for Backstage only, 350h for Backstage + Grafana
- _Difficulty_: Medium

**Comment by shubham-singh-748** [comment]
hey i have strong foundation in html,css & have basics in javascript.
can you please what more skills i need to understand or contribute on this issue?
One more thing is that any slack or discord to interact with members?

**Comment by dev-olanma** [comment]
> 

you can join with the below

[#kubescape-dev on the CNCF Slack](https://kubescape.io/project/community/).

**Comment by MdSahil-oss** [comment]
@craigbox will this project be proposed for upcoming LFX mentorship project ?

**Comment by craigbox** [comment]
Hi all,

The maintainers ultimately decided not present any candidates for this project to the GSoC.  This is not a commentary on the strength of the proposals, but rather the fact that we need to complete some backend work to properly enable a Backstage integration and this work will not be complete this term. To that end, we won't be converting it to an LFX proposal, but we're ready to post up the projects we are putting forward for LFX now.

We look forward to your applications to that!

Thanks,
Craig
