### ISSUE TITLE
how to solve statefulset-kollector Vulnerabilities ? 

### ISSUE THREAD

**Issue by HanHoRang31** [kubescape/kubescape#1182]
## Overview
I installed the kubescape operator using Helm. I'm currently checking for vulnerabilities via the web dashboard, and a vulnerability was found in the kollector component of kubescape. It seems to be caused by a low version of restful-go. Is there an updated version available?

 
![image](https://user-images.githubusercontent.com/117359361/230270555-6e6be76f-6941-40ed-8abb-e739f865686e.png)

**Comment by matthyx** [comment]
Hi @HanHoRang31 thanks for your report.
I am working on an update to fix all security issues: https://github.com/kubescape/kollector/pull/30
I will update you here when it's ready.

**Comment by matthyx** [comment]
@dwertent can we update the image in Helm charts to finally close this one?

**Comment by HanHoRang31** [comment]
I checked, thanks for the update, I am close the issue
