### ISSUE TITLE
Add fix object in Kubescape generated SARIF reports when available

### ISSUE THREAD

**Issue by HollowMan6** [kubescape/kubescape#1183]
## Overview

Add the [fix object](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317881) in Kubescape generated SARIF reports to reflect the available fixes generated by Kubescape.

The fix object represents a proposed fix for the problem indicated by the Result. It specifies a set of artifacts to modify. For each artifact, it specifies regions to remove, and provides new content to insert.

## Additional context

Although there maybe no instant benefit for this addition, hopefully there will be some in the future, as I have submitted a feature request at GitHub for supporting the fix object for their Code Scanning Tool: https://github.com/orgs/community/discussions/52156

**Comment by matthyx** [comment]
Maybe we should wait until GitHub answers your feature request?
(it's a bit like chicken and egg problem)

**Comment by HollowMan6** [comment]
> Maybe we should wait until GitHub answers your feature request? (it's a bit like chicken and egg problem)

I think we can merge it now, as the fix object is already defined in [SARIF specification](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317881). The SARIF report with fix object is still valid for GitHub Code Scanning Tool.

**Comment by craigbox** [comment]
This will also help with [GitHub Actions](https://github.com/kubescape/github-action/pull/41) integration so I don't see any reason to wait!
