### ISSUE TITLE
Moving Docs from Armo Platform Docs

### ISSUE THREAD

**Issue by rushikeshsuryawanshi** [kubescape/kubescape#1204]
## Overview

Moving Docs from Armo Platform Docs

## Problem

[kubescape](https://github.com/kubescape/kubescape)/[docs](https://github.com/kubescape/kubescape/tree/master/docs)/getting-started.md says, " Some documentation on using Kubescape is yet to move here from the [ARMO Platform docs](https://hub.armosec.io/docs?utm_source=github&utm_medium=repository)." 

## Solution

Moving the Docs from the [ARMO Platform docs](https://hub.armosec.io/docs?utm_source=github&utm_medium=repository).
If it's already been done, updating "getting-started.md" with the same.

## Alternatives

Instead of moving whole docs, provide reference and links to ARMO Platform Docs

**Comment by rushikeshsuryawanshi** [comment]
@slashben Could you please review this issue and assign me the same ?

**Comment by slashben** [comment]
This is more on @craigbox 's tabel

**Comment by craigbox** [comment]
Hi Rushikesh,

We have started writing Kubescape documentation at https://github.com/kubescape/kubescape.io.  Please feel free to collaborate there!
