### ISSUE TITLE
LFX proposal: Prometheus exporter for image vulnerabilities

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1226]
This issue relates to a **proposal** for a [LFX mentorship project](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug) for Term 2, 2023.  It has not yet been accepted. Please feel free to comment on this issue about how we might improve the proposal, but commenting here is not the same as applying to LFX.

- Description: Kubescape has a component that runs in-cluster which performs image scanning on all the container images deployed to a cluster. This function is largely used to send the data to an external service.  In this projet, you will develop a Prometheus exporter for the image vulnerability information produced by Kubescape.  This will allow users to access the data from within the cluster, as well as use it for alerting.
- Expected Outcome: Access to cluster vulnerability data through Prometheus.  For example, you should have the ability to alert on number or percentage of "Critical" level vulnerabilities in containers running in the cluster.
- Recommended Skills: Go, Prometheus
- Mentors:
  - Ben Hirschberg (@slashben, ben AT armosec.io)
  - Craig Box (@craigbox, craigb AT armosec.io)
  - David Wertenteil (@dwertent, dwertent AT armosec.io)

**Comment by hackeramitkumar** [comment]
I am Amit Kumar, and I am currently volunteering for the Cluster API v1.5 release team. I have also contributed as the release lead shadow for CAPI v1.4 release team in the past. Moreover, I was a GSoC 2022 student for AOSSIE.

I am writing to express my interest in applying for the upcoming LFX mentorship program. I have reviewed the proposal idea and would like to apply for it. However, I would appreciate it if you could inform me of any prerequisites for the proposal. I want to complete all the prerequisites before the mentoring session starts.

Thank you for your time and consideration. I look forward to hearing from you.

Best regards,
Amit Kumar

**Comment by craigbox** [comment]
There are no prerequisites, other than to be able to convince the maintainers that you have a background that will enable you do this work.

In https://github.com/kubescape/kubescape/issues/1227#issuecomment-1542157406 I had some advice:

> I would start by looking at the Kubescape project itself, and how it scans clusters and resources.  
> You're welcome to join #kubescape-dev on the CNCF Slack.

For this particular project, you should also have some understanding of how Prometheus works, and a winning proposal would probably address how the data models of Kubescape and Prometheus would come together, perhaps with some examples of how other projects export their data in Prometheus formats.

**Comment by hackeramitkumar** [comment]
@craigbox thank a lot, I will try to fullfill all the requirements and will give my best to convince the mentors.

**Comment by money8203** [comment]
Hey @craigbox ,

I'd love to work on this project under LFX mentorship. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project and add value to it.

In the meantime could you provide me with some resources to get started with so that I can get myself familiarized with the project and its needs!

**Comment by kr-2003** [comment]
Hey @craigbox @slashben @dwertent,
I am new to open source and is currently have experience with Docker, Kubernetes, Gitlab CI/CD and AWS. I am also currently learning GoLang. I would love to contribute under LFX mentorship. Can you please help me on how to contribute to this project?? For example, what should I do after cloning the project? How should I test the changes that I make??

**Comment by utkarsh-1905** [comment]
Hey guys, 👋🏽 
Excited to contribute to this issue in the mentorship. I have experience working in Go and Prometheus. I'm looking forward to contributing to this issue!!
