### ISSUE TITLE
LFX proposal: Vulnerability-based Dockerfile generator

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1227]
This issue relates to a **proposal** for a [LFX mentorship project](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug) for Term 2, 2023.  It has not yet been accepted. Please feel free to comment on this issue about how we might improve the proposal, but commenting here is not the same as applying to LFX.

- Description: Kubescape can detect vulnerabilities in a container image. Some can automatically be remediated by changing the base image version (or other package information) inside the Dockerfile which created the image. This project is to automate this remediation.
- Expected Outcome: An enhancement to Kubescape to generate a Dockerfile that proposes fixes for vulnerabilities found in a container image.
- Recommended Skills: Go
  - Ben Hirschberg (@slashben, ben AT armosec.io)
  - Craig Box (@craigbox, craigb AT armosec.io)
  - David Wertenteil (@dwertent, dwertent AT armosec.io)

**Comment by mohdaquib171** [comment]
Hello @slashben @craigbox @dwertent 

I'm Mohd Aquib and I'm really excited about participating in the LFX mentorship program from June to August. I've been learning and working with Go for some time now and also have knowledge of Docker, kubernetes, CI/CD, etc. and would love to contribute to this project. Can you please suggest some resources and IRC channels that I can refer to?

Your help would be greatly appreciated.
Thank you!

**Comment by hackeramitkumar** [comment]
@craigbox Please check the `Vulnerability-based Dockerfile generator` proposal here  -> https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md

You have missed mentors heading there. It's looking odd.

**Comment by money8203** [comment]
Hey @ramumanam I'd love to work on this project under LFX mentorship. As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.

Could you provide me with some resources to get started with initially so that I can get myself familiarized with the project and its needs!

**Comment by kr-2003** [comment]
Hey @craigbox @slashben @dwertent,
I am new to open source and is currently have experience with Docker, Kubernetes, Gitlab CI/CD and AWS. I am also currently learning GoLang. I would love to contribute under LFX mentorship. Can you please help me on how to contribute to this project?? For example, what should I do after cloning the project? How should I test the changes that I make??

**Comment by prateek041** [comment]
hello @craigbox I recently came across this issue through the LFX website. I am familiar with the tech used in the project and therefore I am interested to apply for this june session. Starting with gaining a better understanding of the project.

**Comment by Rahulkhinchi03** [comment]
Hello @craigbox,
Is the LFX Mentee selected?

**Comment by craigbox** [comment]
Not yet; we had a holiday weekend so are a couple of days behind. My apologies!

**Comment by Rahulkhinchi03** [comment]
Ok okay, no worries! 
I have submitted the in-detail 12-week plan proposal in the cover letter for `CNCF - Kubescape: Vulnerability-based Dockerfile generator` and `CNCF - Kubescape: Store Kubescape configuration scan results as CRs`.

Looking forward to hearing from you soon :)
