### ISSUE TITLE
"msg":"eval_cancel_error: caller cancelled query execution"

### ISSUE THREAD

**Issue by testwill** [kubescape/kubescape#1229]
The above log was printed when scanning the cluster. Is this an error?

**Comment by testwill** [comment]
The results of each scan are different

**Comment by dwertent** [comment]
Hi @testwill , We are working on this warning.
But you can ignore it for now :)

**Comment by kronn** [comment]
Do I read https://github.com/kubescape/kubescape/compare/v2.3.1...v2.3.2 correctly, that you solved this by increasing the number of parallel processes?
