### ISSUE TITLE
Download and Installing Wrong Binary For Apple M1

### ISSUE THREAD

**Issue by conradwt** [kubescape/kubescape#1237]
# Description

I'm getting the following message when I attempt to install it on Apple M1:

```zsh
➜ curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
Installing Kubescape...

Architecture arm64 may be unsupported, will try to install the amd64 one anyway.
######################################################################## 100.0%

Finished Installation.

Your current version is: v2.3.3 [git enabled in build: true]

Usage: $ kubescape scan --enable-host-scan

Remember to add the Kubescape CLI to your path with:
  export PATH=$PATH:/Users/conradwt/.kubescape/bin
```

After further inspection, the macOS `amd64` binary was installed instead of the macOS `arm64` binary.

```
➜ file `which kubescape`
/Users/conradwt/.kubescape/bin/kubescape: Mach-O 64-bit executable x86_64
```

# Environment
OS: `macOS 13.3.1 (a)` 
Version: `v2.3.3` 
 
# Steps To Reproduce

# Expected behavior
I expected that the macOS arm64 binary would be installed.

# Actual Behavior
The macOS amd64 binary was installed.

# Additional context

The culprit appears to be `$arch == *"aarch64"*` within the following script:

https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh:
```zsh
arch=$(uname -m)
if [[ $arch == *"aarch64"* ]]; then
    arch="-arm64"
else
    if [[ $arch != *"x86_64"* ]]; then
        echo -e "\033[33mArchitecture $arch may be unsupported, will try to install the amd64 one anyway."
    fi
    arch=""
fi
```

On my machine

```zsh
➜ uname -m               
arm64
```

Thus, I'm not sure how `arm64 == *"aarch64"*` here.

**Comment by craigbox** [comment]
@hollowman6 any thoughts?

**Comment by HollowMan6** [comment]
Okay. Since I don't have a Mac m1, I only test that for Linux. For Linux, `uname -m` is aarch64. Will add the case for macOS then.

**Comment by conradwt** [comment]
> Okay. Since I don't have a Mac m1, I only test that for Linux. For Linux, `uname -m` is aarch64. Will add the case for macOS then.

I'll be happy to test when you have something.
