### ISSUE TITLE
Is the error message around Git accurate?

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1245]
What is the difference between the `gitenabled` build and not?  I understand it's mostly a hack to make Homebrew work, and I understand git2go is used because [the native alternative is too slow](https://github.com/kubescape/kubescape/issues/1014#issuecomment-1376933521).

When running with the version in `homebrew`, with git support disabled, I am still able to scan a Git repository, see the results, and submit them to a backend.

```
$ kubescape version
Your current version is: v2.3.3 [git enabled in build: false]

$ kubescape scan https://github.com/kubescape/kubescape --submit
[info] Kubescape scanner starting
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing local objects
[info] cloning. repository url: https://github.com/kubescape/kubescape
[warning] git scan skipped. error: git scan not supported by this build. Build with tag "gitenabled" to enable the git scan feature
[success] Done accessing local objects
[info] Scanning Repo
Control: C-0058 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (65/65, 692 it/s)        
[success] Done scanning Repo

Controls: 65 (Failed: 20, Passed: 40, Action Required: 5)
Failed Resources by Severity: Critical — 0, High — 52, Medium — 343, Low — 331
```

I end up with results in the configured backend.

<img width="1512" alt="Screenshot 2023-05-26 at 4 40 45 PM" src="https://github.com/kubescape/kubescape/assets/132510/9340063c-45f6-4caa-b1a3-9428b38059b6">

I get one extra field's worth of results if I run the gitenabled build:

<img width="1512" alt="Screenshot 2023-05-26 at 4 40 48 PM" src="https://github.com/kubescape/kubescape/assets/132510/6bb49d1d-eb4a-4666-a97b-13ac927d66d3">

Is there any other practical difference?

**Comment by matthyx** [comment]
Despite the performance issue, usage and results should be exactly the same...

**Comment by craigbox** [comment]
There are also a couple of other places where behaviour is unexpected if you're submitting a repo scan and didn't have Git enabled:

* there's no link to the repo on the file name
* there's no repo name in the scan result page
* clicking "Fix" takes me to https://cloud.armosec.io/repository-scanning/undefined/files/examples%252Fonline-boutique%252Fadservice.yaml (even though the URL had a guid in it)
* there's no history of the file, though it seems the backend associates it as being the same file

(see https://cloud.armosec.io/repository-scanning/fcc2d14a-56b0-4a8d-8a01-36fb0daa30b3 for an example, I've invited you David)

This is making me think that we should do one of three things:

* not do builds without Git support,
* not allow submitting them
* tell vendors running cloud backends to reengineer them to support this case.

**Comment by dwertent** [comment]
@craigbox do you want to define "action items" out of this issue or that we can close it?

**Comment by craigbox** [comment]
@matthyx are we close to having git always be enabled?

**Comment by matthyx** [comment]
> @matthyx are we close to having git always be enabled?

yes with the caveat that if you want to see commit information on a file, you have to have `git` present in the path
(I just need to fix a bug on Windows hosts)

**Comment by craigbox** [comment]
OK, in terms of an actionable issue like @dwertent asked for:

If someone does this:
```
$ kubescape scan https://github.com/kubescape/kubescape 
```
and it causes this to happen:
```
[info] cloning. repository url: https://github.com/kubescape/kubescape
```

then this warning is scary
```
[warning] git scan skipped. error: git scan not supported by this build. Build with tag "gitenabled" to enable the git scan feature
```

and i might rewrite it along the lines of: `git not present in PATH: git metadata (author and hash) will not be available.` 

because the scan will not be skipped, it will just be a bit less verbose than it would be otherwise.

Make sense?

**Comment by matthyx** [comment]
I will update the message in
https://github.com/kubescape/kubescape/pull/1393
