### ISSUE TITLE
Automated closure of resolved issues and making other manul processes automated

### ISSUE THREAD

**Issue by nitishchauhan0022** [kubescape/kubescape#1249]
## Overview
Github action to automate the closing of resolved issues and support for other manual processes to automate them

## Problem
The current issue tracking system lacks visibility on completed features and ongoing work, causing difficulties in managing open issues and determining their priority. The manual process of assigning issues sometimes results in resolved issues being kept open, further complicating the task of prioritizing and resolving them.

To address these challenges, we can automate the assignment process for various tags such as "/assign," "/unassign," and "/bug," to perform automated actions. Additionally, introducing new features like "/triage-accepted," "/priority-description," and labels that specify the area of the problem in kubescape for maintainers can enhance issue management.
## Solution
Implementing automated assignment of tags and automatic closure of resolved issues would facilitate the involvement of new individuals in tackling unresolved issues.

**Comment by nitishchauhan0022** [comment]
If agreed, i can work on it.

**Comment by craigbox** [comment]
I'll let @matthyx weigh in on the value of Prow-like interfaces.

**Comment by matthyx** [comment]
@nitishchauhan0022 that's a cool idea, can you share a bit how you want to achieve that?
(as a long time contributor to prow and test-infra, I can only agree on this interface for OSS projects)

**Comment by XDRAGON2002** [comment]
@matthyx I believe we have two probable options here:

1. Look for an existing tool for the same and simply add that to the repo/org as a github application from the marketplace.
2. Build and maintain a "bot" ourselves using the `probot` framework in `js/ts` similar to what some other projects such as "kubearmor" and others are doing.

The first approach is an out of box solution though we would have limited to no customization available if we want to add some custom automation.

Second approach is completely customizable and would be a pure kubescape tool kind of thing, though we would have to maintain it ourselves and would live in a separate repo and be hosted separately as well.

Thoughts?

**Comment by matthyx** [comment]
> Second approach is completely customizable and would be a pure kubescape tool kind of thing, though we would have to maintain it ourselves and would live in a separate repo and be hosted separately as well.

I don't think we have enough bandwidth to maintain a tool, especially in `js/ts`... what are the existing options that might work?

**Comment by XDRAGON2002** [comment]
@matthyx there's a lot of existing options ranging from menial to advanced tasks and a great list can be found [here](https://probot.github.io/apps/).

We can add all the ones we feel like we need ;)

**Comment by matthyx** [comment]
@XDRAGON2002 I haven't seen a plugin that can close related issues, but we can start experimenting with the following:
- auto assign
- welcome

**Comment by matthyx** [comment]
Let's try and see if that brings value... imho it's always nice to be polite :)

**Comment by XDRAGON2002** [comment]
I agree! ;)

**Comment by matthyx** [comment]
@XDRAGON2002 will we try the welcome plugin?

**Comment by XDRAGON2002** [comment]
I suppose we should, but I don't think I have the required permissions to add it myself? :)

**Comment by matthyx** [comment]
what should I do then? do you have some doc to follow?
