### ISSUE TITLE
anonymous user with permissions

### ISSUE THREAD

**Issue by krol3** [kubescape/kubescape#1258]
## Overview

An admin cluster add more permission to the anonymous user.

Here the permission `kubectl create clusterrolebinding anonymous-xdemo --clusterrole=view --user=system: anonymous`

## Problem
I would like to detect this misconfiguration

## Solution
See in the report

**Comment by alegrey91** [comment]
Hi @krol3 and thanks for this nice suggestion :)
This feature request is related to [regolibrary](https://github.com/kubescape/regolibrary) repository.
@YiscahLevySilas1 do you know if we already have some similar checks already implemented?
If we don't have it, maybe we can consider adding it to one of `AllControls` or `ArmoBest` frameworks.

**Comment by YiscahLevySilas1** [comment]
@alegrey91 I see that we have [this rule](https://github.com/kubescape/regolibrary/blob/9d9099f7b2b6305446b4c04bfc56717350f47c41/rules/RBAC-enabled/raw.rego) that's not in use currently and could match the description of this request

**Comment by alegrey91** [comment]
> @alegrey91 I see that we have [this rule](https://github.com/kubescape/regolibrary/blob/9d9099f7b2b6305446b4c04bfc56717350f47c41/rules/RBAC-enabled/raw.rego) that's not in use currently and could match the description of this request

Great! @krol3 according to your request this rule seems to match. Can you double-check it? So we can move this under some framework to make it available to be used.

**Comment by krol3** [comment]
Thanks @alegrey91, It didn't work adding the rego rule, I see that you created a PR, thank you!

**Comment by krol3** [comment]
Thanks @alegrey91, It didn't work adding the rego rule, I see that you created a PR, thank you!

**Comment by alegrey91** [comment]
We are closing this issue since the control was added on the right framework.
It is now possible to check the misconfiguration running:
```
kubescape scan control C-0262
```
