### ISSUE TITLE
Kubescape compliance-threshold flag not working

### ISSUE THREAD

**Issue by matheensyedaslam** [kubescape/kubescape#1270]
# Description

Install kubescape version v2.3.5/v2.3.7 
Download controls.json > Add registry to white list

**Perform scan with argument having fail-threshold : (Failure case)**

The behaviour is as expected it returns exit code 1 on failure :

`helm template deployment/svc/ | kubescape scan control C-0001,C-0002,C-0004,C-0007,C-0009,C-0012,C-0013,C-0015,C-0016,C-0017,C-0018  -v -t 0 --controls-config controls.json`

[fatal] scan risk-score is above permitted threshold. risk-score: 12.80; fail-threshold: 0.00
echo $?
1

**Perform scan with argument having  compliance-threshold : (Failure case)**

The behaviour deviates as it returns exit code 0 on failure :

`helm template deployment/svc/| kubescape scan control C-0001,C-0002,C-0004,C-0007,C-0009,C-0012,C-0013,C-0015,C-0016,C-0017,C-0018  -v --compliance-threshold 0 --controls-config controls.json`

echo $?
0

As per document with compliance-threshold flag : https://hub.armosec.io/docs/options
It should fail and return exit code 1 
Doc should be updated as flag -t gives waring msg for depreciation for latest versions
 
# Environment
OS: ` ` 
Version: ` ` 
OS: Ubuntu 22.04
Kubescape: Your current version is: v2.3.7 [git enabled in build: true]
 

# Expected behavior

Post scan the command should return exit code 1 (with arg --compliance-threshold 0)

# Actual Behavior

Post scan the command returns exit code 0 (with arg --compliance-threshold 0)

# Additional context

**Comment by craigbox** [comment]
Hey @matheensyedaslam did you want us to do something based on this issue?  Is it just updating the docs/examples?
