### ISSUE TITLE
Grafana kubescape dashboard not updated

### ISSUE THREAD

**Issue by MarioTesoro** [kubescape/kubescape#1275]
# Description
The grafana kubescape dashboard template that in the grafana-kubescape-dashboard.json file does not allow to show the correct graphs.
It can be fixed changing the riskScore keyword in the "expr" fields to the complianceScore keyword.

# Environment
OS: `GKE cluster OS 1.24.8-gke.2000` ,
Version: `Kubescape 3.1.459` 
 
# Steps To Reproduce
Following the guide at https://hub.armosec.io/docs/prometheus-exporter

1. After installing prometheus and grafana following the guide, login grafana
2. Import the dashboard clicking the + button in the left panel, then click import
3. Copy and paste the grafana-kubescape-dashboard.json content
4. Save

NOTE: kubescape is setup to not integrate with the cloud platform:
helm upgrade --install kubescape kubescape/kubescape-cloud-operator -n kubescape --create-namespace --set clusterName=`kubectl config current-context` --set kubescape.serviceMonitor.enabled=true --set kubescape.submit=false --set kubescape.enableHostScan=false --set kubescape.downloadArtifacts=false

# Expected behavior
All graphs appear in working order from the moment of importing the dashboard

# Actual Behavior
3 graphs are not shown because the keywords used in the queries are incorrect

**Comment by XDRAGON2002** [comment]
Hi @MarioTesoro!
I believe this has already been resolved by [this](https://github.com/kubescape/kubescape/commit/84b43d2b039ebb34d134fcf8440cbeb789451c94) also confirmed by looking through the file [here](https://github.com/kubescape/kubescape/blob/master/httphandler/examples/prometheus/grafana-kubescape-dashboard.json).

**Comment by craigbox** [comment]
Closing as fixed by #1266.  Please re-open if you don't see the correct output.
