### ISSUE TITLE
Scan results are not published to the Armo Management Portal

### ISSUE THREAD

**Issue by ferhaty** [kubescape/kubescape#128]
I'm working on a custom build of `kubescape` which can be installed using `Homebrew`. The scan is working and is showing results in the cli. However, the results are not visible at https://portal.armo.cloud. 

I've also executed `kubescape config cluster set customerGUID=<guid>` beforehand. I'm using the following ldflags.

```
  def install
    ldflags = %W[
      -s -w
      -X github.com/armosec/kubescape/cmd.BuildNumber=v#{version}
      -X github.com/armosec/kubescape/cautils/getter.ArmoBEURL=api.armo.cloud
      -X github.com/armosec/kubescape/cautils/getter.ArmoERURL=report.armo.cloud
      -X github.com/armosec/kubescape/cautils/getter.ArmoFEURL=portal.armo.cloud
    ].join(" ")
```

**Comment by dwertent** [comment]
Hi @ferhaty, can you please share your Kubescape version?

**Comment by ferhaty** [comment]
Tested with version 1.0.109

**Comment by slashben** [comment]
> I'm working on a custom build of `kubescape` which can be installed using `Homebrew`. 
Have you heard we have started to release our official version in `homebrew`?

**Comment by ferhaty** [comment]
@slashben started with this when there was no homebrew tap yet. I'm now using the official `kubescape` tap so we can close this issue.
