### ISSUE TITLE
Improvements to the console UI

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1294]
Update the console display to (a) have the spinner on the same line as the currently running operation (b) replace the "Starting operation" line with an "Operation succeeded" line when it has succeeded.

before

```
[info] Kubescape scanner starting
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing Kubernetes objects
[success] Accessed to Kubernetes objects
[info] Scanning. Cluster: docker-desktop
```

after:
```
Kubescape v2.3.7 starting
 : Downloading policy definitions
 ✔ Policy definitions downloaded (line replaces the above)
 : Checking Kubernetes objects
 ✔ Kubernetes objects checked (line replaces the above)
 : Scanning cluster: docker-desktop
 ✔ Cluster scan complete: docker-desktop (line replaces the above)
Control: C-0068 100% |███████████████████████████████████████████████████████████| (63/63, 356 it/s)        
```

* "Kubescape" in bold on the first line
* `:` is [spinner 14](https://github.com/briandowns/spinner) in a dark color
* `✔️` is a check in light green
* `❌` is a cross in red

When redirecting stdout, keep the stderr output as-is:
```
$ kubescape scan > output.txt
{"level":"info","ts":"2023-07-24T21:30:44+12:00","msg":"Kubescape scanner starting"}
{"level":"info","ts":"2023-07-24T21:30:46+12:00","msg":"Downloading/Loading policy definitions"}
{"level":"info","ts":"2023-07-24T21:30:49+12:00","msg":"Downloaded/Loaded policy"}
{"level":"info","ts":"2023-07-24T21:30:49+12:00","msg":"Accessing Kubernetes objects"}
{"level":"info","ts":"2023-07-24T21:30:49+12:00","msg":"Accessed to Kubernetes objects"}
{"level":"info","ts":"2023-07-24T21:30:49+12:00","msg":"Scanning","Cluster":"docker-desktop"}
```

See `syft` output for inspiration.  Be aware this will need changes in `go-logger`.

This should be able to apply anywhere in the UI we have an action that displays a line saying "Starting", invokes a spinner, and then a line saying "Finished".  (Some cases don't have text, and we should update those.)

**Comment by XDRAGON2002** [comment]
@craigbox I'll take this up.

**Comment by craigbox** [comment]
> @craigbox I'll take this up.

Somehow I knew you would. 😉

**Comment by XDRAGON2002** [comment]
@craigbox apart from the tick and cross what icon should we use for warnings? Also are there any icons for debug statements as well?

Because this way we're completely moving away from the `[statement type]` representation.

**Comment by craigbox** [comment]
I think we should differentiate between "console output" and "log output".
I would suggest using `❗`for warning and `—` for debug if you were using them in the context of the "pretty" console output, but I would also suggest that we have more traditional log output, with times attached, available too.  Perhaps if you run with `--debug` (or `-vv`) or something.  I don't know what currently causes the output to change if you're redirecting the output.

**Comment by XDRAGON2002** [comment]
@craigbox just something that I wanted to clarify:

We want to change ALL the logging statements, in the entire repo to the prettier font right? Or is it only selective to some of the statements?

Also, this new output format which is to be made the default, should a new logger be added to the supported loggers in `go-logger`? Or are `fmt.Printf()` calls the way to go for this?

Thanks!
