### ISSUE TITLE
Failed to create SBOM key - Azure AKS v1.25.6

### ISSUE THREAD

**Issue by zohebk8s** [kubescape/kubescape#1303]
Hi Team,

Kubescape is running in Azure AKS v1.25.6. However, I see continuous errors specific to SBOM.

Please have a look.

{
  "level": "error",
  "ts": "2023-07-28T16:47:11Z",
  "msg": "Failed to create SBOM key",
  "error": "Current inputs produce an invalid slug",
  "imageTag": "",
  "imageID": ""
}

<img width="561" alt="image" src="https://github.com/kubescape/kubescape/assets/128701612/453e54ac-8eea-4935-acac-1fa866c7deed">

<img width="511" alt="image" src="https://github.com/kubescape/kubescape/assets/128701612/c2db55b9-300e-4dd6-9901-3fe74557103a">

**Comment by matthyx** [comment]
Usually this happens on the first try for a workload, when the status doesn't yet include the container status with imageID.

In your case it might be different, could you include the full pod spec causing this log?

**Comment by zohebk8s** [comment]
I've uploaded the 
[node-agent-qnqlj-logs.txt](https://github.com/kubescape/kubescape/files/12197183/node-agent-qnqlj-logs.txt)
log file as well.

<img width="947" alt="image" src="https://github.com/kubescape/kubescape/assets/128701612/0107ff8a-b33e-4462-838d-0a0890025b4b">

**Comment by zohebk8s** [comment]
The pod which I’m talking about is node-agent pod running in KubeScape namespace and I’ve attached log file for the same.

**Comment by matthyx** [comment]
@zohebk8s looking at it now, sorry for the delay...
It looks like your Pod `falco/falco-falcosidekick-ui` is crashlooping, and at the end no longer scheduled... which is causing this issue.
I guess I have to filter out Pods in this state when looking for a container image, since it's not running at the this time.

**Comment by matthyx** [comment]
> @zohebk8s looking at it now, sorry for the delay... It looks like your Pod `falco/falco-falcosidekick-ui` is crashlooping, and at the end no longer scheduled... which is causing this issue. I guess I have to filter out Pods in this state when looking for a container image, since it's not running at this time.

WDYT @slashben ?

**Comment by dwertent** [comment]
I noticed this log was printed when the container stopped running but the node-agent did not remove it from the list of containers.

The fix was released in helm version `1.14.3`

**Comment by slashben** [comment]
@zohebk8s can you please retry it with our latest release? We have replaced Falco with another eBPF engine called Inspektor Gadget and it usually works smoothly. You need to update the helm chart and upgrade the deployment

**Comment by zohebk8s** [comment]
Thank you!

I will try as suggested and will update you ASAP.

**Comment by zohebk8s** [comment]
Thank you all.

@slashben Retried as suggested and it worked.

@matthyx @dwertent Previously when the container/pod is not running, the node-agent was still looking for that container ID and throwing SBOM errors. In this release, you have handled that mechanism in an efficient way.

<img width="485" alt="image" src="https://github.com/kubescape/kubescape/assets/128701612/3300901c-aa08-4354-9ee4-0bdb4b0e1b63">

**Comment by matthyx** [comment]
I think it's fine to close
