### ISSUE TITLE
Support higher color terminal output

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1313]
Today, Kubescape uses the colours provided by the [fatih/color](https://github.com/fatih/color) library, which are the 16 basic [ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code).  Those were defined in the 1970s.  We've moved on a little![^1].

Modern terminals can support up to 24-bit color (16.7 million), with Terminal.app on the Mac lagging at only 8-bit color (256 colors)

```
$ echo $TERM
xterm-256color
```

I propose we update Kubescape to support 256 color mode. 

20 mins of research suggests that https://github.com/jwalton/gchalk is a suitable library to implement this.  In the first instance, we should be able to search/replace support in the existing colours.  Then, we will be able to implement much nicer terminal output, with fallback to supported colours if you're running an older terminal.

[tablewriter](https://github.com/olekukonko/tablewriter) uses its own colour system, but I haven't looked to see if Kubescape uses it; if so, we can see if we can just generate our own strings to put in there instead.

[^1]: Though only as far as 1987, thank you Terminal.app

**Comment by XDRAGON2002** [comment]
@craigbox since I'm already working on something eerily related to this, I'll take this up.

**Comment by craigbox** [comment]
it's like I had you in mind when writing it.. 🤭
