### ISSUE TITLE
Duplicate scan result

### ISSUE THREAD

**Issue by tymaoa2** [kubescape/kubescape#1348]
# Description
Got several same vulnerabilities in the scan report.

# Environment
OS: Ubuntu 22.04 LTS
Version: v2.3.8
 
# Steps To Reproduce
kubescape scan --verbose control C-0015 --use-artifacts-from ~/.kubescape/ --exceptions ~/.kubescape/exceptions.json

# Result
################################################################################
ApiVersion: rbac.authorization.k8s.io
Kind: Group
Name: kube-dashboard:operate:PLATFORM CONTRIBUTE CONTENT

Controls: 1 (Failed: 1, action required: 0)
......
################################################################################
ApiVersion: rbac.authorization.k8s.io
Kind: Group
Name: kube-dashboard:operate:PLATFORM CONTRIBUTE CONTENT

Controls: 1 (Failed: 1, action required: 0)
.......

**Comment by XDRAGON2002** [comment]
Hi @tymaoa2!
Could you maybe also provide a yaml manifest file that can help reproduce this? As I've been unable to reproduce this locally. Thanks!

**Comment by matthyx** [comment]
let's reopen if we get more information
