### ISSUE TITLE
After upgrade to 2.9.0 framework cis-aks-t1.2.0 not working

### ISSUE THREAD

**Issue by arvesolli** [kubescape/kubescape#1350]
# Description
After I upgraded kubescape-cli to 2.9.0 (brew upgrade), scanning with framework cis-aks-t1.2.0 is not working.

# Environment
OS: macOS 13.4
Version: Your current version is: v2.9.0 [git enabled in build: false]
 
# Steps To Reproduce
1. kubescape scan framework cis-aks-t1.2.0
2.  Initialized scanner
✅  Loaded policies
✅  Loaded exceptions
✅  Loaded account configurations
✅  Accessed to Kubernetes objects
   0% |                                                                                                                                            | (0/0, 0 it/hr) [0s:0s]
✅  Done scanning. Cluster: dev
✅  Done aggregating results

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Kubescape did not scan any of the resources, make sure you are scanning valid kubernetes manifests (Deployments, Pods, etc.)
ℹ️ Run with '--verbose'/'-v' flag for detailed resources view

# Expected behavior
Scan and output the results

# Actual Behavior
Not working and giving this output:
"Kubescape did not scan any of the resources, make sure you are scanning valid kubernetes manifests (Deployments, Pods, etc.)"

# Additional context
If i switch to other frameworks it works as aspected.

**Comment by dwertent** [comment]
@arvesolli are you scanning an AKS cluster?

**Comment by dwertent** [comment]
Yes, one if the changes introduced in the latest version is not scanning frameworks that are not related to the environment. e.g. nos scanning cis-eks on an AKS cluster. #1293 

I believe Kubescape failed to detect that it is an AKS cluster.
Can you please share the output of the following command 
```
kubectl version --short
```

**Comment by arvesolli** [comment]
```
~ kubectl version --short
error: unknown flag: --short
See 'kubectl version --help' for usage.
```
without --short
```
~ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.3
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
```

**Comment by dwertent** [comment]
@matthyx , @rcohencyberarmor how can we detect an AKS cluster is such case?
Thoughs?

**Comment by matthyx** [comment]
We detect AKS from the server address in `.kube/config` if it contains `azmk8s.io`...

**Comment by arvesolli** [comment]
```
~ grep azmk8s.io .kube/config
    server: https://***.westeurope.azmk8s.io:443
    server: https://****.westeurope.azmk8s.io:443
    server: https://*****.westeurope.azmk8s.io:443
    server: https://******.westeurope.azmk8s.io:443
```
As you can see I have 4 clusters in Azure in my .kube/config file. I scrambled the whole addresses.

**Comment by dwertent** [comment]
@arvesolli Thanks for reporting, we will fix this :)

**Comment by XDRAGON2002** [comment]
Anything I can help out with here? :)
