### ISSUE TITLE
When --format junit is used there is no result summary number

### ISSUE THREAD

**Issue by jancespivo** [kubescape/kubescape#136]
It is not possible to find out result summary number when `--format junit` is used. It is needed ie for adjusting --fail-threshold accordingly.
Please consider showing the summary number in console :pray: 

Thx!

**Comment by jancespivo** [comment]
I think there might be possibility to make items in junit xml more granular (I can imagine there could be row per resource and not per check). So there would be possible to calculate the summary number from junit file directly. WDYT?

**Comment by dwertent** [comment]
We are thinking of printing the junit/json per resource as you suggested, but for the meantime I was thinking of something like this:

![image](https://user-images.githubusercontent.com/64066841/138075582-c55831ab-faae-47e1-bc20-a622c434ceb8.png)

Notice, if you wish to calculate the score from the json/junit format, you can calculate:
```
(allResources - failedResources) / allResources * 100 
```
