### ISSUE TITLE
Error connecting to EKS cluster

### ISSUE THREAD

**Issue by corvusmod** [kubescape/kubescape#1363]
# Description
When trying to connect to an EKS cluster a panic error is shown. Looking in the code for the error, it seems related to kubescape unable to get the region from the configuration.

# Environment
OS: ` `  Mac
Version: ` ` 2.9.0
 
# Steps To Reproduce
Create eks configuration
`aws eks update-kubeconfig --region eu-west-1 --name clustername --kubeconfig configfile
`Use this configuration to connect with the cluster
`kubescape scan --kubeconfig configfile
`
# Expected behavior
A scan is run

# Actual Behavior

```
✅  Initialized scanner
✅  Loaded policies
✅  Loaded exceptions
✅  Loaded account configurations
✅  Accessed to Kubernetes objects
ℹ️ Downloading cloud resources
panic: runtime error: slice bounds out of range [:6] with capacity 4

goroutine 1 [running]:
github.com/kubescape/k8s-interface/cloudsupport/v1.(*EKSSupport).GetRegion(0x130640e40?, {0x1400165f0f8, 0x14})
	github.com/kubescape/k8s-interface@v0.0.136/cloudsupport/v1/ekssupport.go:129 +0x174
github.com/kubescape/k8s-interface/cloudsupport.GetDescriptiveInfoFromCloudProvider({0x1400165f0f8, 0x14}, {0x103e18833?, 0x14001123380?})
	github.com/kubescape/k8s-interface@v0.0.136/cloudsupport/cloudproviderconfiguration.go:62 +0x11c
github.com/kubescape/kubescape/v2/core/pkg/resourcehandler.(*K8sResourceHandler).collectCloudResources(0x1058556b8?, {0x1058556b8, 0x14002665380}, 0x1400154d0a0, 0x0?, 0x1?, {0x140014bfd80, 0x3, 0x10?}, {0x43?, ...})
	github.com/kubescape/kubescape/v2/core/pkg/resourcehandler/k8sresources.go:225 +0x534
github.com/kubescape/kubescape/v2/core/pkg/resourcehandler.(*K8sResourceHandler).GetResources(0x14001cad110, {0x1058556b8, 0x14002665380}, 0x1400154d0a0, {0x105840b38, 0x140029202b8}, 0x140013adb00)
	github.com/kubescape/kubescape/v2/core/pkg/resourcehandler/k8sresources.go:150 +0xa80
github.com/kubescape/kubescape/v2/core/pkg/resourcehandler.CollectResources({0x1058556b8, 0x14002665350}, {0x105829468, 0x14001cad110}, {0x3?, 0x0?, 0x140013adb00?}, 0x1400154d0a0, {0x105840b38, 0x140029202b8}, ...)
	github.com/kubescape/kubescape/v2/core/pkg/resourcehandler/handlerpullresources.go:32 +0x148
github.com/kubescape/kubescape/v2/core/core.(*Kubescape).Scan(0x140017ed000?, {0x105855798, 0x107e2b840}, 0x140013adb00)
	github.com/kubescape/kubescape/v2/core/core/scan.go:176 +0x790
github.com/kubescape/kubescape/v2/cmd/scan.getFrameworkCmd.func2(0x107d79a20?, {0x140015b9b80, 0x1, 0x1})
	github.com/kubescape/kubescape/v2/cmd/scan/framework.go:116 +0x5f8
github.com/kubescape/kubescape/v2/cmd/scan.GetScanCommand.func2(0x140001fb800?, {0x14000fbdfe0?, 0x4?, 0x103e198f9?})
	github.com/kubescape/kubescape/v2/cmd/scan/scan.go:62 +0x204
github.com/spf13/cobra.(*Command).execute(0x140013f7800, {0x14000fbdfc0, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x140013f7500)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/kubescape/kubescape/v2/cmd.Execute()
	github.com/kubescape/kubescape/v2/cmd/root.go:99 +0x38
main.main()
	github.com/kubescape/kubescape/v2/main.go:9 +0x1c
```

# Additional context
Looking in that file (ekssupport.go line 129) I see that it's trying to get the region from the cluster and that this could be set using this env var KS_CLOUD_REGION_ENV_VAR. So I tried and got the same error.

REDACTED KUBECONFIG CONFIGURATION
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: REDACTED
  name: REDACTED
contexts:
- context:
    cluster: REDACTED
    user: REDACTED
  name: REDACTED
current-context: REDACTED
kind: Config
preferences: {}
users:
- name: REDACTED
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - clustername
      - --output
      - json
      command: aws

**Comment by corvusmod** [comment]
More info... added -l debug to command

`🐞  Kubescape Cloud URLs. api: api.armosec.io; auth: auth.armosec.io; report: report.armo.cloud; UI: cloud.armosec.io
✅  Initialized scanner
🐞  Downloading framework. framework: allcontrols
🐞  Downloading framework. framework: nsa
🐞  Downloading framework. framework: mitre
✅  Loaded policies
✅  Loaded exceptions
✅  Loaded account configurations
🐞  Cloud metadata. provider: EKS; name: eks-treasury-dev-old
✅  Accessed to Kubernetes objects
🐞  Collecting rbac resources
🐞  cloud. cluster: eks-treasury-dev-old; clusterName: eks-treasury-dev-old; provider: eks
ℹ️ Downloading cloud resources
🐞  Collecting cloud data . resourceKind: ClusterDescribe
panic: runtime error: slice bounds out of range [:6] with capacity 4`


I test the aws describe-cluster command and it's working without problem

**Comment by dwertent** [comment]
Thanks @corvusmod , @Daniel-GrunbergerCA is working on this as we speak :)

**Comment by corvusmod** [comment]
I think that I get the problem...

🐞  Collecting rbac resources 🐞  cloud. cluster: eks-treasury-dev-old; clusterName: **eks-treasury-dev-old**; provider: eks

ClusterName is different than cluster. In my case, clusterName is eks-treasury-dev without the "-old"

**Comment by corvusmod** [comment]
@dwertent @Daniel-GrunbergerCA I will close the ticket... I identified the problem and it's in my configuration. I have two connections to this cluster with 2 auth methods and in one of them the clustername was wrong.

I detected another problem. If you already have a kube context and use the --kubeconfig option, this option is not used and the context is still active, so I was trying to override the default configuration, but still using it.

Would you like another ticket for that or it's the expected behaviour?
