### ISSUE TITLE
default sensitiveKeyNames contain non-sensitive key names

### ISSUE THREAD

**Issue by filip-zyzniewski** [kubescape/kubescape#1364]
# Description

https://hub.armosec.io/docs/configuration_parameter_sensitivekeynames#default-values contains names that do not seem sensitive, like `aws_access_key_id` for example.

We store our AWS access key IDs in our infrastructure code in plaintext so that we can find references to them easily.
I think that having `aws_secret_access_key` in `sensitiveKeyNames` should be enough.

**Comment by dwertent** [comment]
@filip-zyzniewski Thank you for raising this, @YiscahLevySilas1 we should consider changing the default. Do you remember who wrote the original list?

In the meantime, you can change the list of keys in the [ARMO portal](https://cloud.armosec.io/settings/workspace/controls):
![image](https://github.com/kubescape/kubescape/assets/64066841/840afe14-ad15-4af8-bc07-d6769a9a68db)

**Comment by filip-zyzniewski** [comment]
`azure_batchai_storage_account` and `azure_batch_account` could also be reconsidered.

**Comment by slashben** [comment]
I agree with @filip-zyzniewski

**Comment by matthyx** [comment]
@YiscahLevySilas1 when will the fix be available?

**Comment by YiscahLevySilas1** [comment]
Hi, sorry for the delay on this - I opened a [PR](https://github.com/kubescape/regolibrary/pull/599), it will be available in the next regolibrary release, I will update here

**Comment by matthyx** [comment]
fixed by https://github.com/kubescape/regolibrary/pull/599
