### ISSUE TITLE
builds not working for CentOS and RHEL

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1386]
https://build.opensuse.org/package/show/home:kubescape/kubescape

```The build can not begin, because required packages are either missing or not explicitly defined.

 Repository has been published
unresolvable: nothing provides golang```

/cc @HollowMan6

**Comment by HollowMan6** [comment]
Unfortunately, this can't be solved on our side because it's their Open Build Service (OBS) issues. We also don't need to do anything, these do happen from time to time according to my past experience and it can take some time for them to fix these similar things.

**Comment by matthyx** [comment]
Let's revisit it from time to time to check resolution...

**Comment by HollowMan6** [comment]
Unfortunately, looks like it's still broken for CentOS and RHEL. For RHEL, maybe it's because Red Hat removed access to the RHEL source code which made everything unmaintainable. For CentOS, it's not fixable by us in any case. e.g. CentOS_8_Stream:

```log
unresolvable: nothing provides golang, nothing provides libgomp = 8.5.0-15.el8 needed by gcc, (got version 8.5.0-20.el8), nothing provides gcc = 8.5.0-20.el8 needed by gcc-c++, (got version 8.5.0-15.el8)
```

While also using rpm-based package manager, Fedora and openSUSE work perfectly fine.

**Comment by matthyx** [comment]
I think with goreleaser we can build rpm, deb, etc... would it help if we provide these as release artifacts?

**Comment by HollowMan6** [comment]
> I think with goreleaser we can build rpm, deb, etc... would it help if we provide these as release artifacts?

I think it will be the same result if the user uses e.g. Fedora 36 repo for CentOS and RHEL (Fedora 36 build is OK, we don't have third-party dependencies, and they all use yum/dnf). The core issue here is that it can give out errors if those operation systems don't support the new GLIBC version, so ideally build should be done exactly on those systems and I guess Goreleaser won't help much here even if we provide release artifacts separately.

**Comment by matthyx** [comment]
We no longer build with CGO_ENABLE so we don't care about the GLIBC, do we?

**Comment by HollowMan6** [comment]
> We no longer build with CGO_ENABLE so we don't care about the GLIBC, do we?

I'm not aware of the latest change you made. If that's the case, then there should be no distinction between different Linux distributions, and using the latest Fedora repo should be fine already. Then I guess we can get this issue closed.  
https://software.opensuse.org//download.html?project=home%3Akubescape&package=kubescape

```bash
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:kubescape/Fedora_Rawhide/home:kubescape.repo
dnf install kubescape
```

**Comment by matthyx** [comment]
Do you know how I can test that? I mean without spinning up 5 different VMs?

**Comment by HollowMan6** [comment]
> Do you know how I can test that? I mean without spinning up 5 different VMs?

Well, you will need the environment for testing. Have a CentOS/RHEL machine/VM, run the following command to install, and finally run `kubescape` to see if it can run normally.

> ```shell
> dnf config-manager --add-repo https://download.opensuse.org/repositories/home:kubescape/Fedora_Rawhide/home:kubescape.repo
> dnf install kubescape
> ```

I remember I tested this some time ago last year and the result was exactly the same as this one:
https://stackoverflow.com/questions/76335067/getting-glibc-2-34-not-found-error-while-running-go-geos-package-on-ubuntu-20 Not sure how it goes now as you mentioned you no longer have CGO_ENABLED.

**Comment by matthyx** [comment]
The latest release is built without cgo. Can we try now?

**Comment by HollowMan6** [comment]
> The latest release is built without cgo. Can we try now?

Tested on RHEL 8 and looks good. Users can now use Fedora rawhide repo to get everything running already. Closing...

> > We no longer build with CGO_ENABLE so we don't care about the GLIBC, do we?
> 
> I'm not aware of the latest change you made. If that's the case, then there should be no distinction between different Linux distributions, and using the latest Fedora repo should be fine already. Then I guess we can get this issue closed. https://software.opensuse.org//download.html?project=home%3Akubescape&package=kubescape
> 
> ```shell
> dnf config-manager --add-repo https://download.opensuse.org/repositories/home:kubescape/Fedora_Rawhide/home:kubescape.repo
> dnf install kubescape
> ```
