### ISSUE TITLE
-f json outputs to a file, not stdout

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1394]
Using `-f json` in an output, such as `kubescape scan image nginx -f json`, generates a file called (by default) `report.json`.

```
✅  Scan results saved. filename: report.json
```

Adding `--output example.json` changes the output appropriately:

```
✅  Scan results saved. filename: example.json
```

I would expect that the output from `-f json` would be JSON on stdout, similar to how `kubectl` behaves if you use `-o json`.

**Comment by dwertent** [comment]
We should open this for discussion- The JSON output is extremely large, this is why by default it is saved to a file.

**Comment by rootxrishabh** [comment]
Hey @craigbox @dwertent if the JSON output is suitable I would like to take up this issue!

**Comment by craigbox** [comment]
With all `good first issue` labels, our suggestion is that you look at the code, and propose a design/implementation in a Google doc - no more than one page - for the maintainers to review.

**Comment by prady0t** [comment]
`kubescape scan image nginx -f pdf ` gives:
```                                                                                                         
✅  Successfully scanned image: nginx
❌  format "pdf"is not supported for image scanning
```
Although help section clearly shows ` -f, --format string                          Output file format. Supported formats: "pretty-printer", "json", "junit", "prometheus", "pdf", "html", "sarif"`

Same goes for `junit`, `prometheus` and `html`.

Why is that?

**Comment by craigbox** [comment]
For the first release of image scanning in the CLI, only the console output is supported.
That is another good issue to raise and fix. 🙂

**Comment by prady0t** [comment]
> With all `good first issue` labels, our suggestion is that you look at the code, and propose a design/implementation in a Google doc - no more than one page - for the maintainers to review.

Where should I share the Doc? Here or on slack?

**Comment by craigbox** [comment]
Here is fine.  Thank you!

**Comment by prady0t** [comment]
https://docs.google.com/document/d/1t2L6b3pvB5AuJ-eU6yS2IVvtp_h45TMchs0S-jq0USs/edit?usp=sharing 

Please have a look.

**Comment by craigbox** [comment]
@dwertent @vladklokun could one of you comment on @prady0t's doc please?

I would suggest that the output should be to `stdout`, and any error text can be sent to `stderr`.

**Comment by prady0t** [comment]
@craigbox  I'll try out those changes. Should I make a PR now or wait for someone to assign it to me?

**Comment by craigbox** [comment]
We don't do assignment as such unless someone who is being paid to develop the feature is working on it.

**Comment by prady0t** [comment]
Oh ok. Should I make a PR though or wait for someone to suggest changes in the doc?

**Comment by craigbox** [comment]
@prady0t: I don't think the issue has anything to do with Grype; we use it as a library and we don't use its output routines.
@HARI-124: that looks like the right place to make the change.

The issue is more with what @dwertent says: someone has to decide what the right behaviour is here.  kubectl always outputs to the terminal with `-o json`.

**Comment by prady0t** [comment]
Yes I figured it out later but forgot to remove from the doc.🙂

**Comment by slashben** [comment]
> @prady0t: I don't think the issue has anything to do with Grype; we use it as a library and we don't use its output routines. @HARI-124: that looks like the right place to make the change.
> 
> The issue is more with what @dwertent says: someone has to decide what the right behaviour is here. kubectl always outputs to the terminal with `-o json`.

@dwertent the size does not matter. 

Every "log" and "error" message has to go to `stdout` and every output to `stdout` unless specified otherwise.

In case of pdfs/jsons/htlms and other, even if they are big, they meant to be piped to another process or used to be red to a variable in bash. The volume of the data does not matter.

Please confirm the following (I am asking everyone who is working on this issue):
* default output for all printers is `stdout` (I don't mind saving to a file with `-o/--output` but even in this case it is well accepted that if someone specifies `-o -` it means `stdout`)
* All message which are "operational" and not related to the real product output are sent to `stderr`, meaning no `fmt.Print`-s will end up in the `stdout` which will break up the format. There are a few more annoying things than having some unrelated lines in a json output of a command like this `kubescape scan -o json > results.json`

**Comment by dwertent** [comment]
Now, the question is, do we want the JSON output to have the same format as the JSON that is submitted to a third-party server, or that the JSON output look like the CRDs stored in the cluster?

Honestly, I'm still struggling with the right approach, although I'm leaning towards the thought that the output should look like the objects (configuration scanning CRDs) stored in the cluster.

**Comment by craigbox** [comment]
The server format is interchange. That it's JSON is just an implementation detail.

I agree that it's best that the output format be useful to a human, which is also the goal for the cluster output. If there's little effort required to have them be the same or similar I would also recommend that.

**Comment by dwertent** [comment]
Released

**Comment by slashben** [comment]
> Released

I need to buy you a beer 😆
