### ISSUE TITLE
Add link to the Kubescape survey

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1409]
Until the Message of the Day work is complete, we should display a link to our project survey at the bottom of every time through the `kubescape` CLI.

> Please fill a 3 question survey to help the Kubescape project! https://kubescape.io/project/survey/

I suggest you use the following logic:

* if connected to a provider, display the provider text
* else, display the survey link

**Comment by prady0t** [comment]
Can I work on this?

**Comment by prady0t** [comment]
Are we supposed to put the link somewhere around here? 
![image](https://github.com/kubescape/kubescape/assets/99216956/be850d62-4f4a-40ea-8e04-37087cc401ac)

**Comment by matthyx** [comment]
Hi @prady0t Craid said instead of the provider text, so it should replace :
```
View results
────────────
Now, take your scan results to the next level with actionable insights on ARMO Platform.

Sign up for free here - https://cloud.armosec.io/repository-scanning/74ec6f9c-f2f2-47fa-b755-6b88e8a1289a
```

**Comment by prady0t** [comment]
Hey @matthyx. Can you refer to areas in the codebase from where the provider text is coming from. I found out this function https://github.com/kubescape/kubescape/blob/9e6efd04ce12bd2147d3719b18e5766e2eb2ad2f/core/pkg/resultshandling/reporter/v2/reporteventreceiver.go#L269
Is responsible for printing the provider text.

**Comment by matthyx** [comment]
https://github.com/kubescape/kubescape/blob/master/core/core/initutils.go#L75

**Comment by VaibhavMalik4187** [comment]
@matthyx Can I work on this?

**Comment by matthyx** [comment]
sure, thanks!

**Comment by craigbox** [comment]
Looks like the PR to close this wasn't actually merged?

**Comment by matthyx** [comment]
> Looks like the PR to close this wasn't actually merged?

@slashben said we no longer need this, do you have a different opinion?

**Comment by craigbox** [comment]
not one as important as that, I just wanted to check it wasn't a flaw of automation
