### ISSUE TITLE
The `version` command displays an empty string on Ubuntu

### ISSUE THREAD

**Issue by VaibhavMalik4187** [kubescape/kubescape#1414]
# Description
The version command displays an empty string instead of the version number on Ubuntu.

# Environment
OS: `Ubuntu 22.04 LTS`
Version: `master at commit id: 425f278300895196d5538b71e191812aa6d7f12f`
 
# Steps To Reproduce
1. Build kubescape
2. Run `./kubescape version`

# Expected behavior
The version command should display the actual version number rather than an empty string.

# Actual Behavior

![image](https://github.com/kubescape/kubescape/assets/34866732/fd6d6518-f8ac-4e81-9f9a-1011687d94ca)

**Comment by VaibhavMalik4187** [comment]
Could someone please confirm if they're able to reproduce this behaviour? I'm interested in trying to fix it.

**Comment by matthyx** [comment]
This is because you need to specify the build number during the build:
`go build -ldflags="-X 'github.com/kubescape/kubescape/v2/core/cautils.BuildNumber=v1.0.0'"`

Please check https://github.com/kubescape/kubescape/blob/master/build.py#L63
