### ISSUE TITLE
I got assessment only one control when specific framework cis-v1.23-t1.0.1

### ISSUE THREAD

**Issue by paokrab** [kubescape/kubescape#1420]
# Description
I'm looking for a tool to generate a security compliance report, and I found one that meets my requirements. However, when I ran a scan using the CIS-v1.23-t1.0.1 framework, I got assessment only one control for result.

**Controls: 1 (Failed: 1, Passed: 0, Action Required: 0)
Failed Resources by Severity: Critical — 0, High — 6, Medium — 0, Low — 0**

# Environment
OS: ` ` RHEL8 
Version: ` `2.9.1
 
# Steps To Reproduce
$ kubescape scan  framework cis-v1.23-t1.0.1

# Expected behavior
Should be assessment all controls in framework cis-v1.23-t1.0.1

# Actual Behavior
Controls: 1 (Failed: 1, Passed: 0, Action Required: 0)
Failed Resources by Severity: Critical — 0, High — 6, Medium — 0, Low — 0

**Comment by matthyx** [comment]
@YiscahLevySilas1 can you take a look pls?

**Comment by YiscahLevySilas1** [comment]
@rcohencyberarmor @dwertent - the control scopes are too restricting, all controls under cis-v1.23-t1.0.1 should be allowed to run on clusters that are not managed by cloud providers. Currently 1 control is set to match scope "cluster", "file" and the rest are set for "cloud"

**Comment by paokrab** [comment]
I have downloaded the manifest and changed 'cloud' to 'cluster.' Now it works as I expected, but if we can fix it from the original, it will be even better.

Thanks @YiscahLevySilas1

**Comment by dwertent** [comment]
@YiscahLevySilas1 I believe there was a misunderstanding there, can you please update the CIS controls to cluster scope?
