### ISSUE TITLE
Yaml file can't be edited directly on ARMO Platform

### ISSUE THREAD

**Issue by anirudh-hegde** [kubescape/kubescape#1459]
![image](https://github.com/kubescape/kubescape/assets/105560839/fbb3e031-8404-4a06-8cbc-4692788f957a)

**Comment by yossiarmo** [comment]
Thank you for this feedback, this is something we positively consider.

**Comment by anirudh-hegde** [comment]
> Thank you for this feedback, this is something we positively consider.

Welcome @yossiarmo 
However please add the above feature.

**Comment by dwertent** [comment]
Your request has been thoughtfully forwarded to the product team for their attention.

Thank you :)
