### ISSUE TITLE
Scan failing using -t flag. 

### ISSUE THREAD

**Issue by alfrye** [kubescape/kubescape#148]
I am running kubescape and I set the -t flag to 93 and the scan returns as error "error: Scan score is bellow threshold" However, the scan log shows 94% in the results.

**Comment by dwertent** [comment]
@alfrye I'm not sure how this happens since it's a very [straightforward mechanism](https://github.com/armosec/kubescape/blob/master/cmd/framework.go#L153).

Is there any information you can share so as a screenshot of the final summary? Are you using exceptions?

**Comment by dwertent** [comment]
Thank you @alfrye . We are working on fixing this :)
