### ISSUE TITLE
Kubescape not running if github is inaccessible

### ISSUE THREAD

**Issue by mohaidoss** [kubescape/kubescape#1492]
# Description
Kubescape failing to initializing when github is inaccessible. This apparently is because it uses assets that are hosted on github release page of kubescape/regolibrary

# Environment
OS: `Ubuntu ` 
Version: ` 20.04.6 LTS (Focal Fossa)` 
 
# Steps To Reproduce

1. Block the access to github.com, by either editing the dns locally or disabling internet access
2. Run a kubescape command `kubescape scan`
![image](https://github.com/kubescape/kubescape/assets/48034655/7eb4cfb9-afb2-4ebb-8d41-f78ff41def6d)

# Expected behavior
This is a good way to use the recently updated assets, but in case github is down/inaccessible the whole application is useless and is not working.  
A good approach (since the assets are light in size less than 20MB in total) is to download the assets locally, for in case an access to github is impossible.

# Actual Behavior
Kubescape relies on github to download/access regolibrary assets

**Comment by matthyx** [comment]
you can download them with `kubescape download artifacts` isn't it sufficient?

**Comment by mohaidoss** [comment]
Hello again, the more I dig in this topic, I also noticed that kubescape is downloading the latest release of the kubescape/regolibrary which means that right now it is using RC release `v1.0.300-rc.1`.  

Is this intended ?

**Comment by matthyx** [comment]
Adding @YiscahLevySilas1 and @alegrey91 to the discussion here.

**Comment by mohaidoss** [comment]
> you can download them with `kubescape download artifacts` isn't it sufficient?

No not sufficient, it is still missing `allcontrols` as well. Let me do a check on what's missing

**Comment by mohaidoss** [comment]
> > you can download them with `kubescape download artifacts` isn't it sufficient?
> 
> No not sufficient, it is still missing `allcontrols` as well. Let me do a check on what's missing

@matthyx Back at it, after digging the kubescape download artifacts does indeed download the assets but suffixed with `.json`

Kubescape initialization is not expecting the extension name.

Example :
`kubescape download artifacts` will download `allcontrols.json`
`kubescape [cmd]` will fail at initialization because it's expecting `allcontrols` and not `allcontrols.json`

**Comment by mohaidoss** [comment]
> Ok, there you have your bug to fix :)

Will work on it :ok_hand:
