### ISSUE TITLE
Gateway creation error

### ISSUE THREAD

**Issue by urbaman** [kubescape/kubescape#1511]
Hi,

I installed kubescape via helm:

`helm repo add kubescape https://kubescape.github.io/helm-charts/ ; helm repo update ; helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=`kubectl config current-context` --set account=<account> --set accessKey=<access-key> --set server=api.armosec.io --set kubescape.serviceMonitor.enabled=true
`

It seems it cannot start the gateway pod due to missing serviceaccount:

```
kubectl describe replicaset -n kubescape gateway-c89d8d676
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  58s (x16 over 3m43s)  replicaset-controller  Error creating: pods "gateway-c89d8d676-" is forbidden: error looking up service account kubescape/gateway: serviceaccount "gateway" not found
```

Why that and how to solve?

OS: Ubuntu 22.04
K8s: Kubeadm 1.28.2
Kubescape: 3.0.1

**Comment by matthyx** [comment]
Hi this is very strange, did you get any error during the helm upgrade command?
If you try running it again do you still have this issue?
(I did a successful install yesterday on my personal cluster...)

**Comment by urbaman** [comment]
This is the output of the helm upgrade:

```
Release "kubescape" has been upgraded. Happy Helming!
NAME: kubescape
LAST DEPLOYED: Fri Nov 24 20:36:04 2023
NAMESPACE: kubescape
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
Thank you for installing kubescape-operator version 1.16.3.
View your cluster's configuration scanning schedule:  
> kubectl -n kubescape get cj kubescape-scheduler -o=jsonpath='{.metadata.name}{"\t"}{.spec.schedule}{"\n"}'

To change the schedule, set `.spec.schedule`:  
> kubectl -n kubescape edit cj kubescape-scheduler
View your cluster's image scanning schedule:  
> kubectl -n kubescape get cj kubevuln-scheduler -o=jsonpath='{.metadata.name}{"\t"}{.spec.schedule}{"\n"}'  

To change the schedule, edit `.spec.schedule`:  
> kubectl -n kubescape edit cj kubevuln-scheduler


View your image vulnerabilities scan summaries:  
> kubectl get vulnerabilitymanifestsummaries -A

Detailed reports are also available:  
> kubectl get vulnerabilitymanifests -A
```

So no errors or warnings of sort...
Also happened with the previous chart version (I actually upgraded to see if it worked and it didn't fix it)

I had to delete and re-install the chart, and it solved it out.

I'll close this as it's solved somehow, thank you very much for the moment
