### ISSUE TITLE
Test Case Needed for Non-Existent Image in GetPatchCmd

### ISSUE THREAD

**Issue by Umair0343** [kubescape/kubescape#1530]
Description:

While reviewing the test coverage for the GetPatchCmd function, it was noticed that there is no test case that verifies the behavior of this function when it's run with a non-existent image argument.

This scenario is important to test because it ensures that the function correctly handles invalid inputs and returns the appropriate error message.

The proposed test case should:

- Create a mock Kubescape interface
- Call the GetPatchCmd function with the mock interface
- Run the command with a non-existent image argument
- Check that there is an error and the error message is "image tag is required"

This issue can be closed once the test case has been implemented and is passing.

**Comment by ShivamJha2436** [comment]
Assign me this issue,  I am working on this issue.

**Comment by ShivamJha2436** [comment]
Hey! @Umair0343. Can you confirm if the issue has been resolved with this PR?

**Comment by Umair0343** [comment]
> Hey! @Umair0343. Can you confirm if the issue has been resolved with this PR?

Hey, @ShivamJha2436, yes.

**Comment by Umair0343** [comment]
The issue was resolved with the PR: Update patch_test.go (Add Test Case for Non-Existent Image in GetPatchCmd) #1529

**Comment by ShivamJha2436** [comment]
Thanks for letting me know @Umair0343 .
