### ISSUE TITLE
AUR package out of date

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1559]
We received this email:
```
Your package kubescape [1] has been flagged out-of-date by huiser [2]:

https://github.com/kubescape/kubescape/releases/tag/v3.0.1

[1] https://aur.archlinux.org/pkgbase/kubescape/
[2] https://aur.archlinux.org/account/huiser/
```

/cc @HollowMan6

**Comment by craigbox** [comment]
Thanks.  I knew I'd seen that message somewhere and couldn't find it when I went back to look at it!

**Comment by craigbox** [comment]
https://github.com/kubescape/packaging/settings/rules/ is now empty

**Comment by craigbox** [comment]
Manually run.
https://github.com/kubescape/packaging/actions/runs/7135195533/job/19431491441

Uploaded to AUR and OSC; all the Launchpad updates failed.  Perhaps a transient network error?

```
Uploading to kubescape (via sftp to ppa.launchpad.net):
EOF during negotiation
E: Error connecting to remote host.
make: *** [Makefile:91: ppa] Error 1
```

**Comment by HollowMan6** [comment]
The build is fixed as well. We can't compile in OSC for some of the systems https://build.opensuse.org/package/live_build_log/home:kubescape/kubescape/Debian_10/x86_64 since building go 1.20.12 requires Go 1.17.13 or later.
