### ISSUE TITLE
SSH key permission too wide on packaging GitHub action

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1560]
The "Setup SSH Key" step of the PPA workflow generates [this error output:](https://github.com/kubescape/packaging/actions/runs/7136715272/job/19435589001)

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/home/runner/.ssh/id_ed[25](https://github.com/kubescape/packaging/actions/runs/7135195533/job/19431804477#step:7:26)519' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/home/runner/.ssh/id_ed25519": bad permissions
```

The workflow completes successfully, suggesting this isn't needed.

**Comment by craigbox** [comment]
The fix would be easy enough (a `chmod` at https://github.com/kubescape/packaging/blob/main/.github/workflows/release.yml#L184) but I'm interested to know why this succeeds.  @HollowMan6, any thoughts?

**Comment by HollowMan6** [comment]
> The fix would be easy enough (a `chmod` at https://github.com/kubescape/packaging/blob/main/.github/workflows/release.yml#L184) but I'm interested to know why this succeeds. @HollowMan6, any thoughts?

We already have a `chmod 600 ~/.ssh/*` at https://github.com/kubescape/packaging/blob/main/.github/workflows/release.yml#L191C11-L191C29 So the workflow was fine.

Maybe they (`ssh`) add a new feature so that they even check the permission when they do `ssh-keygen -f ~/.ssh/id_ed25519 -y`

**Comment by HollowMan6** [comment]
Fixed now https://github.com/kubescape/packaging/actions/runs/7144716838/job/19458941633
