### ISSUE TITLE
E0104 13:08:04.033120  4900 memcache.go:121] couldn't get resource list for spdx.softwarecomposition.kubescape.io/v1beta1: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by Tim-Schwalbe** [kubescape/kubescape#1571]
I get these error messages after I uninstalled the helm chart. I sadly don't know the version anymore as it was a while ago.
`
E0104 13:08:04.033120    4900 memcache.go:121] couldn't get resource list for spdx.softwarecomposition.kubescape.io/v1beta1: the server is currently unable to handle the request`

Can anyone help me or had similiar experience?

**Comment by matthyx** [comment]
@Tim-Schwalbe make sure the `storage` pod is running

**Comment by Tim-Schwalbe** [comment]
ahh sorry it was a typo I meant after uninstalling.

**Comment by Tim-Schwalbe** [comment]
The namespace is stuck in `terminating `stage.

**Comment by matthyx** [comment]
> The namespace is stuck in `terminating `stage and was not deleted for some reason.

For how long?

**Comment by Tim-Schwalbe** [comment]
20 days

> > The namespace is stuck in `terminating `stage and was not deleted for some reason.
> 
> For how long?

20 days.

**Comment by rossigee** [comment]
Just happened to me too. I've come across this before with another controller, where a deleted namespace is left with a 'finalizer' that it can't process.

It's a bit of a hack, but in such cases I use this little script...

```
#!/bin/sh

if [ -z "$1" ]; then
	echo "Specify namespace."
	exit 1
fi

NS=$1
echo "Terminating $NS..."
kubectl get namespace $NS -o json \
	| jq '.spec = {"finalizers":[]}' \
	| kubectl replace --raw /api/v1/namespaces/$NS/finalize -f -

echo "Terminated $NS."
```

**Comment by Tim-Schwalbe** [comment]
I get this error, I already added the permission `container.namespaces.finalize` to the runner service account on GKE.

`cannot update resource "namespaces/finalize" in API group "" in the namespace "kubescape"`

**Comment by Tim-Schwalbe** [comment]
I could edit the namespace manually but it does always go back to that state of the finalizers. 
```

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-12-15T09:16:48Z"
  deletionTimestamp: "2023-12-15T12:59:38Z"
  labels:
    kubernetes.io/metadata.name: kubescape
    name: kubescape
  name: kubescape
  resourceVersion: "857507973"
  uid: 229b8fd8-def2-432b-9fcc-9d19ced93496
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2023-12-15T12:59:46Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the 
      complete list of server APIs: spdx.softwarecomposition.kubescape.io/v1beta1:
      stale GroupVersion discovery: spdx.softwarecomposition.kubescape.io/v1beta1'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2023-12-15T12:59:46Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2023-12-15T13:00:18Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2023-12-15T13:00:18Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2023-12-15T13:00:18Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```

**Comment by Tim-Schwalbe** [comment]
I could finally solve it over the Google Cloud Shell itself. Not sure why its different there then on my Laptop.

```
NAMESPACE=kubescape
kubectl get namespace $NAMESPACE -o json > $NAMESPACE.json
sed -i -e 's/"kubernetes"//' $NAMESPACE.json
kubectl replace --raw "/api/v1/namespaces/$NAMESPACE/finalize" -f ./$NAMESPACE.json
echo "deleted ${NAMESPACE}"
```

**Comment by trejo08** [comment]
> I could finally solve it over the Google Cloud Shell itself. Not sure why its different there then on my Laptop.
> 
> ```
> NAMESPACE=kubescape
> kubectl get namespace $NAMESPACE -o json > $NAMESPACE.json
> sed -i -e 's/"kubernetes"//' $NAMESPACE.json
> kubectl replace --raw "/api/v1/namespaces/$NAMESPACE/finalize" -f ./$NAMESPACE.json
> echo "deleted ${NAMESPACE}"
> ```

thanks man, it worked for me, I was diving on this issue for a couple of months
