### ISSUE TITLE
can't list and download custom framework

### ISSUE THREAD

**Issue by yf-0dyssey** [kubescape/kubescape#1579]
# Description
can't list and download custom framework

# Environment
OS version : Centos7
Kubescape version : v3.0.1
 
# Steps To Reproduce
1. I log into cloud.armosec.io and create a custom framework named test which included 9 controls. Below  is the screepshot.
![image](https://github.com/kubescape/kubescape/assets/145762994/bdf2233a-8cf6-44a6-aab8-337492fa776c)

2.  I use the **_config_** command to set account and view it to verify.Below  is the screepshot.
   
![image](https://github.com/kubescape/kubescape/assets/145762994/ae551088-0123-4d2a-8ee5-edfc00f3f4a7)
![image](https://github.com/kubescape/kubescape/assets/145762994/db6f75ac-2a86-4290-a8e6-e2cb66671129)

 
3. I use the **_list_**  command and with account parameter , but can't list all the frameworks(including my custom framework).  I can't download the custom framework also. Below  is the screepshot.
![image](https://github.com/kubescape/kubescape/assets/145762994/be9aa8ad-6a70-4b86-8a1a-4cbde5b030e2)

# Additional context
I met the same problem one year ago and I report the issue(https://github.com/kubescape/kubescape/issues/1028).  At that time I follow the instuction to download the lateset kubescape(v2.0.182) and the issue is solved. But now I met the same problem again . I don't know whether it is a bug or related to my network? Pls help me to find it out .Thanks a lot!

**Comment by yf-0dyssey** [comment]
@dwertent  Hi， could you help me to find out the problem？ thx a lot！

**Comment by dwertent** [comment]
Hi, since kubescape released `v3`, the ARMO URL is not set by default, so if you try to list from the ARMO portal you need to include the ARMO API to the command line (after you do it once it is cached).
Try this:
```
kubscape list frameworks --account <> --access-key <> --server api.armosec.io
```
Notice, that you might need to include the `access-key` flag, you can find it [here](https://cloud.armosec.io/settings/workspace/agent-access-keys).

**Comment by yf-0dyssey** [comment]
> Hi, since kubescape released `v3`, the ARMO URL is not set by default, so if you try to list from the ARMO portal you need to include the ARMO API to the command line (after you do it once it is cached). Try this:
> 
> ```
> kubscape list frameworks --account <> --access-key <> --server api.armosec.io
> ```
> 
> Notice, that you might need to include the `access-key` flag, you can find it [here](https://cloud.armosec.io/settings/workspace/agent-access-keys).

thanks a lot！ I' try   alter following your instruction.

**Comment by yf-0dyssey** [comment]
@dwertent Thank you very much. I tried as you said and it works. But it seems  the account and access-key parameter is necessary when downloading framework. If no account it said "no found'. If no access-key it said "401 Unauthorized”。Below the is screenshot.
By the way, I want to know whether this change is outlined in V3.0 release notes or any other documents.

Finally , thanks your quick and patient reply.  I'll support kubescape and your whole team for ever! It's a amazing k8s security product!


![image](https://github.com/kubescape/kubescape/assets/145762994/0c4712d0-daca-4c01-9854-73eb58090363)

**Comment by dwertent** [comment]
I appreciate your kind words, @yf-0dyssey 😊

Regarding the access-key support mentioned in the release ([link](https://github.com/kubescape/kubescape/releases/tag/v3.0.0)), you're absolutely correct. We should have explicitly stated that adding the access-key is now mandatory. If I recall correctly, it wasn't a breaking change per se, but once you've used an access-key at least once, it becomes a requirement going forward. We implemented this to ensure backward compatibility is maintained.
