### ISSUE TITLE
Missing content in the documentation

### ISSUE THREAD

**Issue by lucj** [kubescape/kubescape#1585]
Hi there,

The documentation is empty for the 'Customizing your scans' content (URL https://kubescape.io/docs/customizing-your-scans/).  

Also, it seems there is something missing at the end of the previous page: https://kubescape.io/docs/scanning/#scanning-with-the-kubescape-operator

**Comment by ShivamJha2436** [comment]
Assign me this issue as I'm working on this.

**Comment by dwertent** [comment]
[Resolved](https://github.com/kubescape/kubescape.io/pull/51)
