### ISSUE TITLE
When using Kubernetes nodes with RHEL 9, the `node-agent` pods fail to start

### ISSUE THREAD

**Issue by ioannisgk** [kubescape/kubescape#1596]
# Description
When using the Kubescape helm chart v1.18.1 and Kubernetes nodes with RHEL 9, the `node-agent` pods fail to start.

# Environment
Cluster: Kubernetes cluster with RHEL 9
Version: [Helm chart v1.18.1](https://artifacthub.io/packages/helm/kubescape/kubescape-operator)
 
# Steps To Reproduce
1. Have a fresh Kubernetess cluster with RHEL 9
2. Deploy Argo CD and setup a GitOps repository
3. Create an Argo CD application yaml file and use this info: targetRevision: 1.18.1, chart: kubescape-operator
5. Add the `account`, `accessKey` and `server` parameters names and values
6. See that all the `node-agent` pods keep restarting, as they cannot become healthy

# Expected behavior
All pods in the kubescape namespace should be healthy.
The `node-agent` pods fail to start only when the Kubernetes nodes use RHEL 9 as OS, this does not occur with Ubuntu 22.04 nodes.

# Actual Behavior
This is part of the logs of a `node-agent` pod in the kubescape namespace:
`{"level":"info","ts":"2024-01-31T18:45:56Z","msg":"credentials loaded","accountLength":36}
W0131 18:45:56.934227   29733 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-01-31T18:45:57Z" level=info msg="container-hook: monitoring runtime at /host/bin/runc"
time="2024-01-31T18:45:57Z" level=info msg="container-hook: monitoring runtime at /host/usr/bin/runc"
time="2024-01-31T18:45:57Z" level=info msg="container-hook: monitoring runtime at /host/usr/bin/crun"
time="2024-01-31T18:45:57Z" level=info msg="container-hook: monitoring runtime at /host/usr/bin/conmon"
{"level":"error","ts":"2024-01-31T18:45:57Z","msg":"error starting exec tracing","error":"creating tracer: attaching exit tracepoint: cannot create bpf perf link: permission denied"}
{"level":"fatal","ts":"2024-01-31T18:45:57Z","msg":"error starting the container watcher","error":"starting app behavior tracing: creating tracer: attaching exit tracepoint: cannot create bpf perf link: permission denied"}`

# Additional context
It is probably some kind of permissions conflict with the RHEL OS.
SELinux has been disabled on the nodes, this needs more research to find the root cause.

**Comment by matthyx** [comment]
@ioannisgk can you post here your kernel version from `uname -a` or equivalent?

**Comment by matthyx** [comment]
Also, which Kubernetes installer did you use?
I am thinking it might come from https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/

**Comment by ioannisgk** [comment]
@matthyx 

Thank you for the information. This is a self-managed cluster in RHEL 9 nodes, where I installed Kubernetes with the `kubeadm init` command. The exact same setup works with Ubuntu 22.04, this problem only occurs on RHEL nodes.

Nodes OS: RHEL v9.3
Linux kernel version: Linux kubernetes-master1 5.14.0-362.18.1.el9_3.x86_64
Helm chart: v1.18.1
Kubernetes Server: v1.28.3
Kubernetes Client: v1.28.3
Calico version: v3.26.3
Containerd version: 1.6.27

**Comment by matthyx** [comment]
I have replicated your error, and checking with our ebpf provider: https://github.com/inspektor-gadget/inspektor-gadget/issues/2444

**Comment by yanghoeg** [comment]
I have the same problem
time="2024-02-02T15:24:07Z" level=info msg="container-hook: monitoring runtime at /host/usr/local/bin/runc"
time="2024-02-02T15:24:07Z" level=info msg="container-hook: monitoring runtime at /host/usr/bin/crun"
time="2024-02-02T15:24:07Z" level=info msg="container-hook: monitoring runtime at /host/usr/bin/conmon"
{"level":"error","ts":"2024-02-02T15:24:08Z","msg":"error starting exec tracing","error":"creating tracer: attaching exit tracepoint: cannot create bpf perf link: permission denied"}
{"level":"fatal","ts":"2024-02-02T15:24:08Z","msg":"error starting the container watcher","error":"starting app behavior tracing: creating tracer: attaching exit tracepoint: cannot create bpf perf link: permission denied"}

i'm using rocky-linux / 5.14.0-362.13.1.el9_3.x86_64

**Comment by matthyx** [comment]
Yup, same kernel, same issue. I will update here when we have the fix...

**Comment by matthyx** [comment]
after further investigation, it is a bug in the RHEL kernel and the inspektor-gadget team has opened a PR for a fix: https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/3717

**Comment by matthyx** [comment]
@ioannisgk may I ask you to raise this issue to your Red Hat success manager to speed up the merge request above?

**Comment by gabrielrinaldi** [comment]
I have the same issue but I'm using EKS managed bottlerocket nodes

**Comment by matthyx** [comment]
@gabrielrinaldi I can confirm the issue is the same, but the reason is different. Can you open a new issue and we'll discuss the solutions there?

**Comment by matthyx** [comment]
@ioannisgk I have a workaround if you want: while the kernel version usually remains the same for the whole lifecycle of a RHEL release, there is a way to install a more recent one...

I have followed this page https://wiki.crowncloud.net/?Installing_the_Linux_Kernel_6x_on_AlmaLinux_9 and installed https://elrepo.org/tiki/kernel-lt (because I wanted the latest "long term support" branch.

I can confirm our ebpf capabiilities are working with this kernel:
```
$ uname -a
Linux localhost.localdomain 6.1.77-1.el9.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  5 16:34:15 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matthyx** [comment]
@ioannisgk can I hear back from you?

**Comment by dwertent** [comment]
I [updated the documentation](https://hub.armosec.io/docs/installation-troubleshooting#rhel-9-nodes) with the proposed workaround.
