### ISSUE TITLE
Failure to run on AKS cluster

### ISSUE THREAD

**Issue by muandane** [kubescape/kubescape#1602]
# Description

# Environment
OS: it's container so what ever is the dockerfile set to, but the aks nodepool OS is on `Ubuntu 22.04`  
Version: `v3.0.3` 
 
# Steps To Reproduce

# Expected behavior

it should work, i tested kubescape on a k3s node with my armo accountID and secret which works without issues
# Actual Behavior

![kubescape](https://github.com/kubescape/kubescape/assets/114167214/650d3bf9-5485-4b97-8960-12486bbcb7e2)

# Additional context

**Comment by muandane** [comment]
@EtienneDeneuve

**Comment by matthyx** [comment]
@muandane we have just released a new Chart to address this issue, can you try again?

**Comment by matthyx** [comment]
1.18.3 released 2 minutes ago

**Comment by muandane** [comment]
thanks @matthyx i dont get that erreur anymore, but i'm getting this instead is it because of kubescape not being fully compatible with AKS ?

<img width="923" alt="image" src="https://github.com/kubescape/kubescape/assets/114167214/b21aa5a0-caee-4df5-9543-9ee7f5498fdd">

**Comment by muandane** [comment]
does it have to do with 1 kubevuln pod being down due to ephemeral-storage limitation ?
<img width="804" alt="image" src="https://github.com/kubescape/kubescape/assets/114167214/bd87c6d3-5f88-45f5-a52b-05d99a0cd3eb">

**Comment by matthyx** [comment]
> thanks @matthyx i dont get that erreur anymore, but i'm getting this instead is it because of kubescape not being fully compatible with AKS ?

It means we didn't detect you're running on AKS... you can try setting `cloudProviderMetadata.cloudProviderEngine=aks`

**Comment by matthyx** [comment]
> does it have to do with 1 kubevuln pod being down due to ephemeral-storage limitation ? `Pod ephemeral local storage 

kubevuln doesn't have to do with compliance scan, it's the component that does vulnerability scans... however it would be nice to have it running :)
on your cluster you don't have PV support?

**Comment by muandane** [comment]
I'm installing kubescape using flux, this is the values structure i'm giving flux 

![image](https://github.com/kubescape/kubescape/assets/114167214/d65cc89a-6184-4fc5-8a58-158d64c3bea5)

ps: 
- i have also added the secrets to the kuebscape deployment but in a form a secret instead of passing them as stings using envFrom.secretRef
- for the PV yes my aks cluster supports it i added as you can see the storage class needed
- for the `cloudProviderMetadata.cloudProviderEngine=aks` i checked the chart locally and it's not used anywhere i think that's the issue

**Comment by matthyx** [comment]
right, this parameter was deprecated looooong ago... sorry
maybe you could try setting some of the AKS specific values `cloudProviderMetadata.aks*` from https://github.com/kubescape/helm-charts/tree/main/charts/kubescape-operator ?

**Comment by muandane** [comment]
yes i added all of them as a secret
<img width="430" alt="Screenshot 2024-02-12 at 5 12 45 PM" src="https://github.com/kubescape/kubescape/assets/114167214/c5e490a1-32f9-4401-953d-70b9c0e158fd">

<img width="773" alt="Screenshot 2024-02-12 at 5 14 50 PM" src="https://github.com/kubescape/kubescape/assets/114167214/2f6174c7-ca79-45cc-996f-65c696c5734e">
<img width="682" alt="image" src="https://github.com/kubescape/kubescape/assets/114167214/ae9d4a7b-92b3-4246-b019-56773909c298">

**Comment by matthyx** [comment]
hmm, @dwertent any idea?

**Comment by dwertent** [comment]
I think this is because we dont get the cloud provider from the nodes.
I will change this behavior.

**Comment by dwertent** [comment]
I revisited the issue and found that Kubescape identifies the cloud provider. 
Have you reviewed the documentation [here](https://hub.armosec.io/docs/azure-aks)? It mentions both User-Assigned Managed Identities and System-Assigned Managed Identities. Ensure that you have defined the correct one.

**Comment by matthyx** [comment]
@dwertent I think your recent fix in the latest release should solve that.
