### ISSUE TITLE
documentation missing

### ISSUE THREAD

**Issue by ld-singh** [kubescape/kubescape#1603]
Hi
Could you provide some documentation for below?
https://kubescape.io/docs/scanning/#scanning-with-the-kubescape-operator

Also provide some info on how to configure correctly for AWS EKS cloud.

Thanks

**Comment by dwertent** [comment]
Hi @ld-singh,
Apologies for the inconvenience, but we are currently restructuring some sections of the documentation. While this is underway, you can access the basic documentation by following this link: [Basic Documentation](https://github.com/kubescape/helm-charts/tree/main/charts/kubescape-operator#install).

For information on setting up access for compliance scanning in EKS, please refer to this resource: [Setting up AWS IAM Authorization for In-Cluster Installation of Kubescape in EKS](https://hub.armosec.io/recipes/setup-aws-iam-authorization-of-in-cluster-installation-of-kubescape-in-eks).

**Comment by ld-singh** [comment]
Thanks @dwertent This is helpful
