### ISSUE TITLE
Does kubescape have arm architecture image?

### ISSUE THREAD

**Issue by testwill** [kubescape/kubescape#1641]
## Problem

Does kubescape have arm architecture image?

**Comment by matthyx** [comment]
yes, both [kubescape](https://quay.io/repository/kubescape/kubescape?tab=tags) and [kubescape-cli](https://quay.io/repository/kubescape/kubescape-cli?tab=tags) have amd64 and arm64 in the manifest

**Comment by matthyx** [comment]
also the latest binary release supports arm64 amd64 and riscv64: https://github.com/kubescape/kubescape/releases/tag/v3.0.6
