### ISSUE TITLE
Add control references in the PDF output

### ISSUE THREAD

**Issue by maxgio92** [kubescape/kubescape#1661]
## Overview

The PDF report is useful, especially for assessment overviews.
As of now a reference to each control, independently of the framework, is missing and only a description is provided.

## Problem

The description of the control is not enough to reference the documentation of the control, remediation included.

## Solution

Include a new column in the PDF to reference the control ID.

## Alternatives

Include an hyperlink to the online documentation of the specific control, as already done for the pretty table output.

## Additional context

The current version (`v1`) of the used PDF library `maroto` misses the support for hyperlinks, introduced by https://github.com/johnfercher/maroto/pull/372. 
 
In that case, a porting to the new v2.0.0-beta version would be needed. This work is already tracked in #1458.

My proposal is to not wait for the library porting for this issue, and instead approach it in an agile way and subsequently include the hyperlink once supported.

**Comment by maxgio92** [comment]
Hello, JFI I've a PR almost ready :-)

**Comment by matthyx** [comment]
fixed in https://github.com/kubescape/kubescape/pull/1662
