### ISSUE TITLE
sha256 not being published since v3.0.3

### ISSUE THREAD

**Issue by echoblag** [kubescape/kubescape#1664]
## Overview
Previous releases included a sha256 file that could be verified.

This initially raised and included as a result of https://github.com/kubescape/kubescape/issues/98

I did look around for any documentation on updated signing or validation mechanisms and found none.

## Problem
This was an easy means of preventing mutated binaries and unexpected changes.

## Solution
Including the sha256 files again seems like the simplest solution.

**Comment by matthyx** [comment]
@echoblag please check the SBOM files, if they don't contain what you need, let's see if https://goreleaser.com/customization/checksum/ can add them back - I'll happily review your PR 👍

**Comment by matthyx** [comment]
Let me follow-up on that next week when I'm back, but I think we can configure goreleaser to provide the checksums.

Also, our images https://quay.io/repository/kubescape/kubescape and https://quay.io/repository/kubescape/kubescape-cli should be signed with cosign: https://kubescape.io/docs/install-operator/#validation-with-public-key

**Comment by matthyx** [comment]
fixed by #1665
