### ISSUE TITLE
Kubescrape external providers

### ISSUE THREAD

**Issue by spron-in** [kubescape/kubescape#1690]
## Overview
We are thinking to use kubescrape and integrate it with our UI.

## Problem

I see this doc https://kubescape.io/docs/providers/, but it is not clear what kind of data Kubescrape sends and it what format.

## Solution
I would love to have at least vague understanding about it, maybe some internal docs.

**Comment by matthyx** [comment]
Hi @spron-in what kind of UI is it?

**Comment by spron-in** [comment]
@matthyx an in-house developed UI. It is in react, backed by rest API and postgreSQL database.
I was thinking that kubescrape can send the data to an API, i would store it in the database and show it in the UI.

**Comment by slashben** [comment]
@spron-in are you planning to build this UI as an open-source project, or you are implementing some custom needs

**Comment by spron-in** [comment]
For now it is for internal / custom needs.
