### ISSUE TITLE
Node agent does not find containerd.sock for k3s

### ISSUE THREAD

**Issue by mgalesloot** [kubescape/kubescape#1739]
# Description
The node agent does not detect the proper location of containerd.sock. It checks for /run/containerd/containerd.sock but this should be /run/k3s/containerd/containerd.sock. 
Because Inpektor gadget is capable of finding the right location of containerd.sock, the expectation is that the node agent can do this too. 

# Environment
OS:  Suse MicroOS 20240922 with K3s v1.30.4.
Kubescape operator version 22.

# Steps To Reproduce
Install Kubescape operator
Watch the logs of the node agents
Observe the errors with containerd.sock

# Expected behavior
The nodeagent should find the proper location of containerd.sock. 

 Inspektor gadget (installed with its own helm chart) is capable of locating containerd: 
`gadget-schtj gadget time="2024-09-23T19:51:46Z" level=info msg="using the detected container runtime socket path from Kubelet's config: /run/k3s/containerd/containerd.sock"
`
# Actual Behavior
The node agent uses the location /run/containerd/containerd.sock. The log shows failures. 

`time="2024-09-23T20:08:44Z" level=warning msg="Runtime enricher (containerd): couldn't get current containers: listing containers with request &ListContainersRequest{Filter:nil,}: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory\""  `

**Comment by matthyx** [comment]
Thanks for the report, let me check tomorrow... Fun fact the former k3s location was added by me.
In the meantime there's a parameter in the values to set the runc path.

**Comment by mgalesloot** [comment]
I tried the parameter for the runc path. I checked on the host, it was `/var/lib/rancher/k3s/data/current/bin/runc` and put this in gloab.overrideRuntimePath. But this setting did not make any difference for the .sock failure.

**Comment by matthyx** [comment]
I think you can try setting `INSPEKTOR_GADGET_CONTAINERD_SOCKETPATH` and I will check if we need to change or initialization of the container-watcher to use the new detection system.

**Comment by mgalesloot** [comment]
I have tried to configure the env in the daemonset:
```
    - name: INSPEKTOR_GADGET_CONTAINERD_SOCKETPATH
       value: /run/k3s/containerd/containerd.sock
```
This did not fix the error. It still shows: `Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory"`

**Comment by matthyx** [comment]
Can you try prepending /host to the path?

**Comment by mgalesloot** [comment]
Some more detail from the log. It shows that ListContainersRequest() and getNodes() fail, but the actual monitoring of pods does seem to start (see the last lines). Maybe these initial warnings are indeed just warnings? 
```
node-agent-ftlch node-agent time="2024-09-24T20:00:10Z" level=warning msg="Runtime enricher (containerd): couldn't get current containers: listing containers with request &ListContainersRequest{Filter:nil,}: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
node-agent-ftlch node-agent time="2024-09-24T20:00:13Z" level=warning msg="Failed to retrieve socket path for runtime client from kubelet: getting /configz: fetching /configz from \"k3s-worker-small-jue\": unknown (get nodes k3s-worker-small-jue). Falling back to default container runtime"
node-agent-ftlch node-agent {"level":"info","ts":"2024-09-24T20:00:19Z","msg":"main container handler started"}
node-agent-ftlch node-agent {"level":"info","ts":"2024-09-24T20:00:24Z","msg":"RuleBinding added/modified","name":"/all-rules-all-pods"}
node-agent-ftlch node-agent {"level":"info","ts":"2024-09-24T20:00:25Z","msg":"start monitor on container","container ID":"352a5651daadc0c027dfc66d10ac40d37c443096df8a75ea7b2133bc2c59f55a","k8s workload":"cert-manager/cert-manager-9647b459d-ht4l4/cert-manager-controller"}
node-agent-ftlch node-agent {"level":"info","ts":"2024-09-24T20:00:25Z","msg":"start monitor on container","container ID":"d2cb874bb91e82cb5d3f5d2ff6d85e59eba681eeb4442abb383c3b5fa7f531c7","k8s workload":"cert-manager/cert-manager-cainjector-5d8798687c-fkr7w/cert-manager-cainjector"}
```

Now when I prepend /host to the path, the first two calls for  ListContainersRequest() and getNodes() still fail, but now the monitoring also fails. Note the /host/host. 
```
node-agent-89626 node-agent time="2024-09-24T19:58:55Z" level=warning msg="Skip pod kyverno/kyverno-reports-controller-665ccb5b65-lfpz4: cannot find container (ID: containerd://7c64a14e55ada64595916abbbc96408c6a85f36c88cfdb174cdf25d373ffb18c): rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /host/host/run/k3s/containerd/containerd.sock: connect: no such file or directory\""
```

After unsetting the var HOST_ROOT there is another error.  
```
node-agent-k8cvt node-agent {"level":"error","ts":"2024-09-24T20:18:04Z","msg":"error starting the container watcher","error":"setting up container collection: initializing container collection: starting container fanotify: container-hook: notifying /var/lib/rancher/k3s/data/current/bin/runc: stat /var/lib/rancher/k3s/data/current/bin/runc: no such file or directory"}
```
The path seem OK to me because `stat /var/lib/rancher/k3s/data/current/bin/runc` on the node itself works.

**Comment by matthyx** [comment]
> Maybe these initial warnings are indeed just warnings?

Yes seems like so.

**Comment by larssb** [comment]
> I think you can try setting `INSPEKTOR_GADGET_CONTAINERD_SOCKETPATH` and I will check if we need to change or initialization of the container-watcher to use the new detection system.

For anyone else here .... I'm pretty sure that this `env. var.` is no longer used by Inspektor Gadget. See: https://github.com/inspektor-gadget/inspektor-gadget/pull/2794
