### ISSUE TITLE
Download exceptions.json from portal.armo.cloud

### ISSUE THREAD

**Issue by RothAndrew** [kubescape/kubescape#174]
## Feature request

As a user of kubescape who uploads reports to portal.armo.cloud and also runs kubescape in my CI pipeline, I'd like the ability to download the exceptions.json file from portal.armo.cloud so that I can use it in my pipeline.

## Context

The cloud UI lets me toggle exceptions for resources. Example: 
![image](https://user-images.githubusercontent.com/16000938/137798614-eef25ead-d6b9-4e56-9a59-0fbefb978fa3.png)

I'd like the ability to download the resulting exceptions.json so that I can run the same set of exceptions in my CI pipeline without needing to write my own exceptions file.

**Comment by slashben** [comment]
@RothAndrew , check out the new UI :)
