### ISSUE TITLE
KubeScape scan failure with http error

### ISSUE THREAD

**Issue by DLakin01** [kubescape/kubescape#1750]
# Description
The kubescape operator is failing to scan many running workloads in my cluster with the error: `http: read on closed response body`. This results in missing vulnerability manifests, ApplicationProfiles, etc.

# Environment
Platform: EKS Kubernetes 1.28, OS is Amazon Linux 2
Operator version: `v0.2.34`
KubeScape version: `v3.0.18 `
 
# Steps To Reproduce
1. Install the kubescape operator Helm chart (v1.22.5) on an EKS cluster
2. Check the operator logs for errors

# Expected behavior

The operator's KubeScape scans should be able to scan all my apps and generate all the expected CRDs

# Actual Behavior

Many of the scans fail with errors similar to:

```
{
  "level":"error",
  "ts":"2024-10-31T14:22:39Z",
  "msg":"failed to complete action",
  "command":"kubescapeScan",
  "wlid":"wlid://************/namespace-kube-system/deployment-vertical-pod-autoscaler-vpa-recommender",
  "error":"http: read on closed response body"
}
```

**Comment by matthyx** [comment]
already tracked here https://github.com/kubescape/operator/issues/238
solution should be merged next week
