### ISSUE TITLE
GKE Autopilot Support - Yay or Nay? 

### ISSUE THREAD

**Issue by seth-acuitymd** [kubescape/kubescape#1759]
# Description

Hey Kubescape team! 

I was investigating whether we could leverage Kubescape in our GKE Autopilot clusters for various security needs - but it looks like we'd have to disable the node agent, as it expects a lot of host level permissions that the GKE Autopilot Admission controller does not allow - 

```shell
admission webhook "warden-validating.common-webhooks.networking.gke.io" denied the request:
GKE Warden rejected the request because it violates one or more constraints. 
Violations details: {"[denied by autogke-default-linux-capabilities]":["linux 
capability 'SYS_ADMIN,SYSLOG,SYS_RESOURCE,IPC_LOCK' on container 'node-agent' not allowed; 
Autopilot only allows the capabilities: 
'AUDIT_WRITE,CHOWN,DAC_OVERRIDE,FOWNER,FSETID,KILL,MKNOD,NET_BIND_SERVICE,NET_RAW,SETFCAP,SETGID,SETPCAP,
SETUID,SYS_CHROOT,SYS_PTRACE'."]
```

```shell
[denied by autogke-disallow-hostnamespaces]":["enabling hostPID is not allowed in Autopilot."]
```

```shell
"[denied by autogke-no-write-mode-hostpath]":["hostPath volume host in container node-agent is accessed in write mode;
 disallowed in Autopilot.",
"hostPath volume run in container node-agent is accessed in write mode; 
disallowed in Autopilot.",
"hostPath volume modules in container node-agent is accessed in write mode; 
disallowed in Autopilot.",
"hostPath volume debugfs in container node-agent is accessed in write mode; 
disallowed in Autopilot.",
"hostPath volume cgroup in container node-agent is accessed in write mode; 
disallowed in Autopilot.",
"hostPath volume bpffs in container node-agent is accessed in write mode; 
disallowed in Autopilot."]
```

# Environment
OS: `GKE COS` 
Version: `v3.0.21`
 
# Steps To Reproduce

1. Create Autopilot cluster
2. Install kubescape via Helm Chart 

# Expected behavior

- Not entirely sure! 

# Actual Behavior
- Node agent cannot run with desired permissions 

# Additional context

As mentioned above, I'm not _sure_ what the expected behavior should be. Messing around in Headlamp with the Kubescape plugin, I can see information about potential vulns in running images, which is nice, the `Compliance` tab is empty 

Since GKE Autopilot is so tightly managed, I don't expect GKE to allow anyone but GCP services to really poke around on the nodes, do we just chalk this up to "It's autopilot so we can assume the nodes are secure?"

Curious what the Kubescape community thinks!

**Comment by seth-acuitymd** [comment]
Thanks @slashben ! I knew this wasn't a bug, it didn't really fit any issue type - 

Everything you said makes total sense, and squares with my mental model of GKE Autopilot - I manage most of the Kubernetes things for my org so the less for me to actually _run_ the better (hence - autopilot's managed nodes!) 

We have a mix of standard and autopilot - so I'm going to continue my `kubescape` testing in that cluster since it's a great tool that I think I can leverage effectively! 

If I want to make use of the config/vuln scanning in Autopilot - do I still need the cluster-side components (minus node agent) or can I just leverage the CLI? 

Thanks so much! 

(I'll close this out once I confirm the above question)

**Comment by matthyx** [comment]
@seth-acuitymd you can use either way, installing the helm chart will provide automatic scan when a workload starts, CLI has the benefit of being "agent less"

**Comment by slashben** [comment]
@seth-acuitymd, you're welcome to pop into our Slack channel or community meetings if you have follow-up questions!
https://github.com/kubescape/project-governance/blob/main/COMMUNITY.md
