### ISSUE TITLE
Provide ARM64 release binaries

### ISSUE THREAD

**Issue by scottslowe** [kubescape/kubescape#195]
It would be great to provide ARM64 release binaries (for both Linux and macOS). I noted the current `build.py` script doesn't account for processor architecture, but a manual build of an ARM64 Darwin/macOS binary from a AMD64-based Linux host using Go 1.17 did not produce any errors. The resulting binary _seemed_ to work as expected, but I did not perform any extensive testing.

**Comment by dwertent** [comment]
Kubescape [images are built with arm support](https://github.com/armosec/armo-helm/releases/tag/armo-cluster-components-1.7.8)

**Comment by HollowMan6** [comment]
For linux, the multi-architecture (like aarch64, s390x, i586, armv7l, ppc64le etc.) is now already available with package managers:
- https://github.com/kubescape/kubescape/issues/1143
- https://github.com/kubescape/kubescape/issues/1142

I will work for a solution on the arm64 for macOS later.
