### ISSUE TITLE
Allow Privilege Escalation check passes when it shouldn't?

### ISSUE THREAD

**Issue by raesene** [kubescape/kubescape#27]
Setup
--

-kind 1.21 cluster `kind create cluster`
-Standard pod run with `kubectl run -it testtools2 --image=raesene/alpine-containertools /bin/bash`
-run `kubescape scan framework nsa --exclude-namespaces kube-system,kube-public`

In the results I got :-

```
[control: Allow privilege escalation] passed 👍
Description: Attackers may gain access to a container and uplift its privilege to enable excessive capabilities.
Summary - Passed:2   Failed:0   Total:2
```

Is this control checking for `allowPrivilegeEscalation` in the pod manifest? If so, I think this check should have failed as the default for Kubernetes is to allowPrivilegeEscalation unless it's specified in the pod/container securityContext.

**Comment by BenHirschbergCa** [comment]
Yes, we did two controls:
* Privileged container: fires alert if  `containers.securityContext.privileged == true`  (meaning, the container processes are not really separated from the non-containerized processes and devices)
* Privilege escalation: alerts if  `container.securityContext.allowPrivilegeEscalation == true`  (meaning, as you pointed out in your blog, the a containerized process can "enjoy the feature" of setuid bit and get a higher privilege after `execv`)

I did not really understand the connection with PSP, please correct me if I am wrong. With the proper configuration, PSP can block either of the above container settings, however they are not connected to PSP per se.

**Comment by raesene** [comment]
So the PSP reference was just was just because that's what the NSA guide was discussing when looking at container lockdown options and taking about `privileged` and `allowPrivilegeEscalation`. PSPs (or OPA or Kyverno etc) should be able to block either of those individually.

In a default config. I'd be expecting your first check to come back as [PASSED] as privileged won't be set but for the second check to come back as [FAILED] as Docker and kubernetes don't set `allowPrivilegeEscalation: false` by default 😄
