### ISSUE TITLE
sign kubescape binaries and container images with cosign 

### ISSUE THREAD

**Issue by developer-guy** [kubescape/kubescape#328]
[cosign](https://github.com/sigstore/cosign) is a tool that allows you to sign and verify container images, blobs, etc. with using public/private key pairs or without key (keyless) by taking the strength of the Transparency Log. You can learn more about the project from its official website [here](https://chainguard.dev/posts). So, we'll be using cosign with a keyless approach to make kubescape binaries even more secure and let people verify kubescape binaries to check whether these binaries have been tampered with.

> https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/

**Comment by developer-guy** [comment]
please feel free to assign it to me. I'm willing to work on it.

**Comment by slashben** [comment]
@developer-guy sounds like a great initiative

**Comment by slashben** [comment]
@developer-guy please target our dev branch in PRs

**Comment by slashben** [comment]
@developer-guy I'll check it, thanks!

please open the PR against our dev branch

**Comment by Blue-Skyer** [comment]
Hello, 

We notice that developer-guy (https://github.com/developer-guy) requested the feature in this pull request/issue, but the code relies on the GitHub project (https://github.com/sigstore/cosign), in which developer-guy is one of the contributors. This fits into our category of "self-promotion" (it is unethical to promote the use of a project without mentioning that he or she is associated with the project).

Regards, Blue Skyer.

**Comment by dwertent** [comment]
Completed

**Comment by slashben** [comment]
Nice
