### ISSUE TITLE
Submit Kubescape to CNCF Landscape

### ISSUE THREAD

**Issue by ibidani** [kubescape/kubescape#335]
CNCF Landscape is a dictionary for Kubernetes tools, seems like Kubescape will be a great addition for extra visibility of this great tool.
Here is how to request to be added https://landscape.cncf.io/guide#introduction--what-is-the-cloud-native-landscape

**Comment by slashben** [comment]
@ibidani , thanks :) 

Kubescape has been submitted to CNCF sandboxing, hopefully it will be accepted at the next TOC meeting.

**Comment by ibidani** [comment]
Oops just realized I closed it accidently, sorry

**Comment by matthyx** [comment]
I think that one is done?
