### ISSUE TITLE
use github.repository_owner instead of hardcoded repository name

### ISSUE THREAD

**Issue by developer-guy** [kubescape/kubescape#339]
In build GA, I saw that kubescape uses a hardcoded repository name called "armosec" which causes a problem when someone wants to test GA in his fork, so, changing it with github.repository_owner seems a better option to solve this.

> feel free to assign it to me 🙋🏻‍♂️

**Comment by slashben** [comment]
good point!

**Comment by ArnWEB** [comment]
I have fixed this issue .Can you please review and and merge it in main barnch
I have created the PR waiting for your approval

@dwertent

**Comment by anjannair** [comment]
This issue should be closed considering the PR #361

**Comment by dwertent** [comment]
Merged a few months ago.
