### ISSUE TITLE
Failed to load kubernetes config: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by sundowndev** [kubescape/kubescape#35]
I'm stuck with this error `Failed to load kubernetes config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`. Setting the env var `KUBERNETES_MASTER` or `KUBE_CONFIG_PATH` does not change anything, what am I missing ?

**Comment by dwertent** [comment]
@sundowndev I'm not sure what you are missing, is it possible you do not have a running Kubernetes cluster?

We use the [client-go](k8s.io/client-go/kubernetes) package for loading the Kubernetes config. 

Please update if you managed to solve your issue

**Comment by sundowndev** [comment]
@dwertent Not sure what I should specify in `KUBERNETES_MASTER` for it to work, I tried my kubeconfig path, my cluster's URL...

> is it possible you do not have a running Kubernetes cluster?

No, I can manage my cluster with kubectl

**Comment by BenHirschbergCa** [comment]
@sundowndev , if you don't mind, can you please share how your Kubernetes cluster is hosted? (minikube, EKS, GKE or etc.)

I am asking because for GKE support we needed to include an additional go module

**Comment by sundowndev** [comment]
@BenHirschbergCa It's hosted on Digitalocean

**Comment by hermanbanken** [comment]
I have the same error, but I'm using plain YAML generated via Kustomize, eg.
```bash
cat output.dev.yaml        | kubescape scan framework nsa -
cat output.test.yaml       | kubescape scan framework nsa -
```

**Comment by dwertent** [comment]
@hermanbanken  I think the issue in your case is that Kubescape loads the k8s config when the input is a file, loading the config is unnecessary since the input is a file and not a running cluster.

We will fix this next release :)

**Comment by hermanbanken** [comment]
> @hermanbanken I think the issue in your case is that Kubescape loads the k8s config when the input is a file, loading the config is unnecessary since the input is a file and not a running cluster.
> We will fix this next release :)

Cool! I was looking at the policyhandler package and couldn't figure out why it was loading the resources
https://github.com/armosec/kubescape/blob/571a15bee8de5a75beaee1aad091fcde2d7c25ca/policyhandler/handlenotification.go#L79-L84

Turned out it was aborting way before 😄

**Comment by dwertent** [comment]
@hermanbanken  I fixed the issue, please confirm it works :)

**Comment by dwertent** [comment]
@sundowndev  try setting `export KUBECONFIG=<path to config>`,  is it better?

**Comment by hermanbanken** [comment]
Verified it works, thanks!
