### ISSUE TITLE
Proposal: Display images vulnerabilities scan results 

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#430]
Kubescape already supports [pulling the image vulnerabilities scanning results](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/k8sresources.go#L67).
We should add the option of displaying these results in a `pretty-print`/`json` format.

If you wish to take this upon yourself, please contact [one of the maintainers](https://github.com/kubescape/kubescape/blob/master/MAINTAINERS.md) for more information

**Comment by SaNsK11** [comment]
Hey @dwertent I would like to work on this issue! I am new to Kubescape, so would love to get some pointers on how to get started

**Comment by 9gl** [comment]
Hi @dwertent ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.Looking forward to contribute to the issue.

**Comment by kunjgit** [comment]
Hi @dwertent i would like to contribute in this issue can you please share some resources that i can go through to understand this issue very well.

**Comment by SrijanShovit** [comment]
Hi @dwertent I would like to contribute in this issue ,Could you please share resources that so as to understand this issue and start contributing asap

**Comment by harshitasao** [comment]
Hello, @dwertent. Could you please provide me with more information about this issue so that I can prepare a proposal?

**Comment by anubhav06** [comment]
Hi @dwertent. I'd like to work on this issue.
How about I add an `image` sub-command which can be used to display the image scan results ?

**Example:** Running `kubescape scan image -f "pretty-print"/"json"` would display the image vulnerability scan results in the requested format.

Kindly let me know if this approach is correct, so that I may proceed with it :)

**Comment by anubhav06** [comment]
Hey @dwertent . I'm downloading the image scanning results from this [API call](https://api.armosec.io/openapi/v2/swaggerui#/Image%20Scanning/postVulnerabilityScanResultsDetails): `https://api.armosec.io/api/v1/vulnerability/scanResultsDetails`.

However, this does not return all the CVE's which I see on the KS Image Scanning dashboard.
There are certain CVE's which are shown in the SaaS, however they are not present in the API response. Vice versa, there are certain CVE's which are NOT shown in the SaaS, however they are present in the API response.

So, is this a problem/bug with the SaaS, or am I doing something wrong ?

**Comment by dwertent** [comment]
We have done this here #1320
