### ISSUE TITLE
Develop AWS ECR image vulnerability adaptor

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#436]
Kubescape uses image vulnerability information to give enhanced security information about the cluster.

The code has been designed to support multiple vulnerability information sources, but for now only Kubescape SaaS is supported.

Need to implement AWS ECR adaptor to be able to read information from ECR.

See more about the adaptor design [here](https://github.com/armosec/kubescape/blob/master/docs/proposals/container-image-vulnerability-adaptor.md)

Example of the Kubescape Saas adaptor is [here](https://github.com/armosec/kubescape/blob/master/registryadaptors/armosec/v1/civarmoadaptor.go)

**Comment by verma-kunal** [comment]
Hey @slashben I would love to work on this issue!
I am new to the Kubescape project so, can you help me with some pointers and resources to start with
Thanks 🙂

**Comment by slashben** [comment]
Hey! Great to hear!

I suggest you read this as the first step: https://github.com/armosec/kubescape/blob/master/docs/proposals/container-image-vulnerability-adaptor.md

If you join to discord channel we have been discussing this there, you are welcome

**Comment by verma-kunal** [comment]
Hey sure! I am a part of the discord community. Is there any specific channel where the discussion related to this topic has been going on?

> If you join to discord channel we have been discussing this there, you are welcome

**Comment by slashben** [comment]
In the developers channel, we have someone working on the same
functionality just for GCP. It worth checking out!

**Comment by verma-kunal** [comment]
> In the developers channel, we have someone working on the same functionality just for GCP. It worth checking out!

Yeah, just saw the message on the channel & replied! 
Thanks :)

**Comment by nashetali837** [comment]
Hey@slashben, i would like to work on this issue.

**Comment by verma-kunal** [comment]
> Hey@slashben, i would like to work on this issue.

Hey @nashetali837 , glad to know you are interested in working on this! I have actually been working on this one & made some progress as well. Maybe we could collaborate in the future :)

Till then, you may have a look at various other open issues out there (https://github.com/kubescape/kubescape/issues)
Hope you understand :)

**Comment by verma-kunal** [comment]
> Hey@slashben, i would like to work on this issue.

Hey @nashetali837 , glad to know you are interested in working on this! I have actually been working on this one & made some progress as well. Maybe we could collaborate in the future :)

Till then, you may have a look at various other open issues out there (https://github.com/kubescape/kubescape/issues)
Hope you understand :)

**Comment by amirmalka** [comment]
@verma-kunal It seems like a good first step.

Next steps would be:
1. Define a new ECR adaptor which implements the `IContainerImageVulnerabilityAdaptor` interface (https://github.com/kubescape/kubescape/blob/dev/core/pkg/registryadaptors/registryvulnerabilities/interfaces.go) 
2. Initialize your ECR adaptor in the `listAdaptors()` function https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/registrydata.go#L150

**Comment by verma-kunal** [comment]
Thanks @amirmalka ! Will resume working on this as soon as my exams are over :)

**Comment by verma-kunal** [comment]
Hey @amirmalka @dwertent , I am actually stuck on the part for defining a new adaptor.
From what I learned going through the file system, we have an API file in the `core/cautils/getter` called as `kscloudapi.go` which basically defines a struct called `KSCloudAPI` & that allows accessing the API of the Kubescape Cloud offering.
Now, I understand that this has to be created for AWS as well & then we'll refer to this while defining the new adaptor!

AWS doesn't have a single API for all the operations (atleast I wasn't able to find that) but it has separate ones for accessing various services we want, in this case its ECR  ([here](https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/) is the api for that). 
Now, I am logically stuck on this part on what to define in that struct & how to proceed. Will keep trying around different things but if you can provide a direction here, that would help a lot 

Thanks :)

**Comment by amirmalka** [comment]
@verma-kunal 

It is very hard to answer in advance what would you need to have defined in your struct. To get things running, I would start off by creating an empty struct which implements the 
`IContainerImageVulnerabilityAdaptor` interface (with empty implementation)

Then, I would create an initialization method (something like `NewECRAdaptor` which takes the configuration needed to create the client, and stores it in the struct (https://github.com/verma-kunal/kubescape-ecr-adaptor/blob/main/demo/main.go#L43) 

I assume that creating the client involves the authentication stage against the provided config, (https://github.com/verma-kunal/kubescape-ecr-adaptor/blob/main/demo/main.go#L49), so in this case, I would create the client in the `Login()` method and keep it in the struct, and so on...

Once you have the initialized client, you can continue implementing the rest of the functions.

It may help you to take a look on the implementation of GCR adaptor as we have a new PR on that  https://github.com/kubescape/kubescape/pull/814

**Comment by verma-kunal** [comment]
Thanks for guiding here, @amirmalka 
Would try this out & get back with updates!

**Comment by verma-kunal** [comment]
Hey @amirmalka , i hope you are doing well!
I actually wanted to resume my work on this adaptor! I know it's been long, but got caught up with some personal work. Just wanted to confirm whether this has been implemented yet or not?
Thanks

**Comment by amirmalka** [comment]
@verma-kunal no progress made on this issue, feel free to continue working on it :)

**Comment by craigbox** [comment]
We have moved vulnerability scanning into the cluster and deprecated the adaptors, so this issue is no longer relevant.
