### ISSUE TITLE
Develop GCP GCR image vulnerability adaptor

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#437]
Kubescape uses image vulnerability information to give enhanced security information about the cluster.

The code has been designed to support multiple vulnerability information sources, but for now only Kubescape SaaS is supported.

Need to implement GCP GCR adaptor to be able to read information from ECR.

See more about the adaptor design [here](https://github.com/armosec/kubescape/blob/master/docs/proposals/container-image-vulnerability-adaptor.md)

Example of the Kubescape Saas adaptor is [here](https://github.com/armosec/kubescape/blob/master/registryadaptors/armosec/v1/civarmoadaptor.go)

**Comment by AvineshTripathi** [comment]
Hey @slashben I would like to work on this issue, can you help me with some pointers and resources to start with

**Comment by slashben** [comment]
> Hey @slashben I would like to work on this issue, can you help me with some pointers and resources to start with 

Cool! Have you seen the interface?

**Comment by AvineshTripathi** [comment]
I have tried the using kubescape on clusters, running commands and exploring it

**Comment by slashben** [comment]
I suggest reading this as a good starting point: 
https://github.com/armosec/kubescape/blob/master/docs/proposals/container-image-vulnerability-adaptor.md

Then, you can look here 
https://github.com/armosec/kubescape/tree/master/core/pkg/registryadaptors

Here is the interface of the adaptor you need to implement for GCP
https://github.com/armosec/kubescape/blob/master/core/pkg/registryadaptors/registryvulnerabilities/interfaces.go

We have implemented here the only working registry adaptor "ARMO cloud" vulnerea adaptor. You can look into it as an example.

Have fun :) If you have any question, please ping us on discord

**Comment by AvineshTripathi** [comment]
Update: sorry for the delay(was stuck in some work), resuming the work and will update soon with the progress

**Comment by satvik2131** [comment]
Hi @slashben I want to work on this issue , can you help me working on it

**Comment by Aman123lug** [comment]
@slashben  hey ben you please assign me this project i want to work on it.

**Comment by slashben** [comment]
@satvik2131 , @Aman123lug , please note that this issue has already been assigned

**Comment by slashben** [comment]
Sure, we will be happy to assist you. Hop on and say hi on our Discord
