### ISSUE TITLE
Implement a graphic rich GitHub Action for Kubescape

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#439]
Many thanks to @avinashupadhya99 Kubescape has a GitHub action!

We want to extend this action to make it more useful for developers to track down the problems with their Kubernetes manifests. It should use the Javascript package of GitHub to create a useful graphical output of the action, where:
* All resources are listed, each of them are linked to the file in repo
* Control failures are listed per resource
* Controls are grouped by Frameworks

Anyone considering to contribute on this, make sure you get familiar with the GitHub action module of Node.js

**Comment by Kanika637** [comment]
I want to contribute to this issue, but as I am new to this project and the issue, could you please help me out @slashben?

**Comment by slashben** [comment]
Hi @Kanika637 ! Let's talk on discord, ok?

**Comment by Kanika637** [comment]
Suree @slashben

**Comment by Adi9235** [comment]
Hey can I contribute in this issue but I am beginner in this project @slashben

**Comment by slashben** [comment]
This is a duplicate of #591 , sorry guys for the confusion :(

**Comment by Rohan-Dah** [comment]
Hey @slashben  .. I would love to contribute to this issue as well... I am learning new stuff about it and am ready to team up with people to get this issue sorted... Could you please help me out with this?..

**Comment by slashben** [comment]
@Rohan-Dah , it is a duplicate of #591 and already a some guys are working on it

**Comment by Rohan-Dah** [comment]
@slashben alright...

**Comment by dwertent** [comment]
This is in the roadmap
