### ISSUE TITLE
run kubescape with --kubeconfig flag

### ISSUE THREAD

**Issue by matsonkepson** [kubescape/kubescape#479]
Allow to run kubescape with `--kubeconfig` flag like its done with kubectl tool. 
to make the multicluster/multuser/namespace check more granular.

**Comment by dwertent** [comment]
Hi @matsonkepson .
Kubescape already supports the `--kube-context` flag which is for scanning different contexts.
If you wish to include/exclude namespaces you can specify the namespaces with the `--include-namespaces`/`--exclude-namespaces` flags. 
Do you have suggestions for other flags we can support?

**Comment by matsonkepson** [comment]
As I understand correctly to use `--kube-context` I need to be already logged in (like with `oc login` tool). 

I have a practice of using multiple clusters assigned as aliases to my bash with builtin kubeconfig file like
`alias kt='kubectl --kubeconfig /mnt/c/work/secret/it-kube.conf '`
`alias kp='kubectl --kubeconfig /mnt/c/work/secret/ip-kube.conf '`
`alias kd='kubectl --kubeconfig /mnt/c/work/secret/dev-kube.conf '`

So I am not actively logged it to any of it. 

How in this situation I would be able to use the `--kube-context` flag ?

**Comment by dwertent** [comment]
Oh I see.
Good idea. We will add support for `--kubeconfig` flag :)

**Comment by dwertent** [comment]
@matsonkepson Since kubescape supports the `KUBECONFIG` env var you can set your alias as following:

```
alias kst='KUBECONFIG=/mnt/c/work/secret/it-kube.conf kubescape'
alias ksp='KUBECONFIG=/mnt/c/work/secret/ip-kube.conf kubescape'
alias ksd='KUBECONFIG=/mnt/c/work/secret/dev-kube.conf kubescape'
```

**Comment by alegrey91** [comment]
Hi @dwertent! I'd like to take care of this in my free time. Can you explain how to integrate this flag (if you are still interested in adding support)?

**Comment by dwertent** [comment]
Hi @alegrey91 , sorry for the late response.
Are you still interested?

**Comment by alegrey91** [comment]
Hi @dwertent, yes, always interested to contribute. If it's not urgent, I could take care by the beginning of September. Currently I'm a little bit busy. Let me know if it's ok for you.

**Comment by SrijanShovit** [comment]
Hi @dwertent I would like to contribute in this issue ,Could you please share resources that so as to understand this issue and start contributing asap

**Comment by Talha-Here** [comment]
Hi @dwertent I would like to help and contribute in this issue , it would be great if you share some resources as it would help in understanding and contributing

**Comment by itsCheithanya** [comment]
@dwertent assign this issue as I've already completed half of the work just some checks needed

**Comment by dwertent** [comment]
Merged
