### ISSUE TITLE
Wildcard scanning of directories not working

### ISSUE THREAD

**Issue by avinashupadhya99** [kubescape/kubescape#547]
When kubescape is run to scan an entire directory of manifest files using a wildcard(*) character, kubescape scans only the first file in the directory.

Steps to reproduce - 
1. `git clone https://github.com/GoogleCloudPlatform/microservices-demo.git`
2. `cd microservices-demo`
3. `kubescape scan kubernetes-manifests/*.yaml -v`
4. Notice the results - It only mentions the first file name i.e. `full-path/kubernetes-manifests/adservice.yaml`
5. `kubescape scan kubernetes-manifests/adservice.yaml -v`
6. Notice the result is same as the previous run
7. `kubescape scan kubernetes-manifests/loadgenerator.yaml -v`
8. Notice the result i.e., the % risk score
9. `mv kubernetes-manifests/loadgenerator.yaml kubernetes-manifests/aaloadgenerator.yaml`
10. `kubescape scan kubernetes-manifests/*.yaml -v`
11. Notice the results is same as the previous run but the file name is different since we renamed it. The result is not identical to the very first run even though it is the same set of files.

**Comment by danieljkemp** [comment]
I'm seeing this as well. I ended up moving the manifests to a new directory and just scan the directory
