### ISSUE TITLE
feature suggestion: gitops pipeline compliant vulnerability remediation

### ISSUE THREAD

**Issue by touchthesun** [kubescape/kubescape#551]
Kubescape already has the ability to generate YAML from misconfigured resources and append or highlight changes that would resolve certain vulnerabilities. However as far as I know, this only works in the UI. 

What would be amazing is something that allows you to output all those yaml files from a scan into a temp directory. This lets engineers do all the fixes at one go and push the fixed files back up to git, and ideally it should allow for whatever level of automation is desired in implementing those changes.

So for example, say I run kubescape scan framework nsa --report-out=tmp/reports, and that creates yaml files in the tmp/reports directory for each misconfigured resource. Now I can run a script that grabs .items[0].metadata.name from each one, runs a kubectl get <name> -o yaml on each, runs a diff between the two, and uses yq to substitute the values suggested by the report into the main manifest. Then those all get pushed back into the pipeline, scanned again, and should now pass.

Anyway, just a thought on how you can take a great product and make it better. Keep up the good work.

**Comment by dwertent** [comment]
@touchthesun Thank you very much for your feedback and your suggestion! 
We are actually discussing this very thing right [here](https://github.com/armosec/kubescape/discussions/550).

If you noticed, by running Kubescape with the `-v`/`--verbose` flag you can get a detailed report including the exact paths.

I have two main concerns regarding the automatic generating of YAMLs:
1. We do not have an automatic fix for each issue. e.g. we cannot auto generate limits, requests, labels etc.
2. If you simply apply the generated fixes it can effect the behavior of your application. e.g. If your container is expected to run as root and now it's not

Obviously we can generate fixes we know and assume the user will apply them carefully, but if we come up with a better solution it will be great!

I do not have an out-of-the-box solution for these limitations, I will like to hear from you or from anyone else in the community if you have any suggestion, I have been thinking about this for a really long time and I still do not have a solution.

@slashben Do you have anything to add?

**Comment by dwertent** [comment]
One other thought - When generating an auto fix for a cluster we can store the generated YAMLs in a single file, but when we generate fixes for a local directory/git repo, we will need to keep the directory structure or add a comment/annotation for the different generated YAMLs since we can have the same file metadata but the YAML itself will have different content

**Comment by slashben** [comment]
Sounds a very interesting direction.

I am thinking on @touchthesun 's idea.

It is not necesseraly a must to create an "automatic" fix to the issues. The user must confirm each change manually (I think we don't have a doubt here).

However, the question is how to incorporate the fixes into the code stream:
* Either creating a copy with the fix in a `tmp` directory as @touchthesun proposed
* Creating the temprary fix files next to the original files
* Creating `patch` files for each issue
* Making the changes on the original files and let the user validate all changes with `git diff` and other tools (VS Code and etc)

What do you think?

**Comment by aiyushbedi007** [comment]
Hey !! I will like to work on this issue and start my contribution to kubescape.
Thanks!

**Comment by slashben** [comment]
@aiyushbedi007 you are welcome to!

**Comment by aiyushbedi007** [comment]
Thanks @slashben  I am new to Kubescape can you guide me? what is the best way to reach you if I have any questions?

**Comment by 9gl** [comment]
Hi @slashben  ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by slashben** [comment]
@9gl , @aiyushbedi007 , are you on Discord? Let's have a chat there (I am opening a channel there for this "kubescape-remidiation-actions"). Join there and we will loop-back here when we have more.

**Comment by dwertent** [comment]
@touchthesun This is [now supported](https://github.com/kubescape/kubescape/releases/tag/v2.0.183) with the `fix` command!

**Comment by touchthesun** [comment]
Amazing! I can’t wait to try itSent from the futureOn Jan 14, 2023, at 11:36 PM, David Wertenteil ***@***.***> wrote:﻿
@touchthesun This is now supported with the fix command!

**Comment by dwertent** [comment]
Notice that the `fix` command will not work exactly as you suggested, we do not fix the resources running in your cluster. Instead, the fix command will fix your CICD this way you can control the proposed suggested using SCM.

This is something no one else does in the industry so we will love to get some feedback so we can improve the feature.

Please feel free to me directly or contact me via the Kubescape slack channel if you wish to give input regarding this capability.
