### ISSUE TITLE
Ability to force colored output for CI environments that are not a real TTY

### ISSUE THREAD

**Issue by mowies** [kubescape/kubescape#560]
I know that there is the option to specifically disable colors in the output of kubescape, but it would also be nice to be able to force-enable colored output.
This is especially important for CI tools like GitHub Actions, that don't have a real TTY but still have the ability to show ANSI colors correctly.

**Comment by dwertent** [comment]
What is the exact issue? Do you see the pretty printer but without colors or that you see the zap logger (the zap logger prints the logs in json format)?
If the issue is that you see the zap logger, you can set an environment variable as follows: `"KS_LOGGER_NAME": "pretty"`
Please let me know if it solves your issue :)

**Comment by dwertent** [comment]
Can you please share a screenshot/example of how you run so I can reproduce and try fixing it? :)

**Comment by mowies** [comment]
Hey @dwertent !
I created a small example repo with a workflow that reproduces my issue: https://github.com/mowies/kubescape-color-test
The workflow can be found here: https://github.com/mowies/kubescape-color-test/blob/main/.github/workflows/test.yml
And here is the log output of the workflow run:
![Screenshot 2022-07-11 at 08 36 16](https://user-images.githubusercontent.com/6901203/178203209-2fdf6c0e-230e-4058-9d2e-0abf869d5c61.png)

**Comment by mowies** [comment]
@dwertent any updates on this?

**Comment by dwertent** [comment]
I'm on it :)

**Comment by dwertent** [comment]
@vladklokun Can you please take a look at this?

**Comment by devmrfitz** [comment]
@vladklokun @dwertent Can I work on this issue?

**Comment by devmrfitz** [comment]
@mowies Does [this](https://github.com/devmrfitz/kubescape-color-test/runs/8174671148?check_suite_focus=true) look good?

**Comment by mowies** [comment]
@devmrfitz could you please post a Screenshot? I can't access the logs in your pipeline run

**Comment by devmrfitz** [comment]
![Screenshot_20220904-232451_Chrome](https://user-images.githubusercontent.com/58381523/188327005-63a95d6e-0e90-40c5-ba95-b81d0ce3ea4c.jpg)

**Comment by devmrfitz** [comment]
@mowies

**Comment by mowies** [comment]
That looks great @devmrfitz !
