### ISSUE TITLE
Implement "apply fix" in VSCode extension

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#592]
Kubescape VSCode extension is showing which lines are failing different controls based on the Kubescape result object. The result object contains "failedPath" entry for each control per object.

Kubescape also supplies "fixedPath" which is a proposed solution to the given issue. We want to use the "apply fix" mechanism of VSCode using the "fixedPath" in Kubescape results.

**Comment by rohan-kulkarni-25** [comment]
Hey !! I will like to work on this issue will you like to guide me and start my contribution to kubescape. 
Thanks!

**Comment by kunjgit** [comment]
hey @slashben i would love to resolve this issue give some resources that i can go through and start working on this perticular issue

**Comment by Ciggzy1312** [comment]
Hey @slashben if its okay I also might give this one a try

**Comment by slashben** [comment]
Hey all,

@Ciggzy1312 asked these two questions on Discord , I am putting the answers here so all of us can enjoy ;-)

> I did find the failed paths in the scanned results returned by the api but there is no fixedPaths that you mentioned in the issue description. There is one fix parameter but it is in the diagonistic reports but it remains undefined. So probably am missing something and a bit of assistance would be great

@Daniel-GrunbergerCA has looked into this and indeed the `fixPaths` is missing and undefined. It is most likely a parsing problem. Kubescape CLI (on which this plugin is built) is returning `fixPaths` in the JSON output, but it is not parsed into the structure you are talking about. I suggest you look into the parsing part, it might require change.

> And can you give me a brief about what exactly are the goals or what we are willing to implement regarding this issue

The fix path is the line you should add to fix the issue in the YAML file. We are displaying problematic lines and/or missing ones. We should use this information to enable the user in VS Code to fix an issue in place

**Comment by Ciggzy1312** [comment]
Thanks, @slashben @Daniel-GrunbergerCA  for helping us out
I will try to look into it

**Comment by aparna2071** [comment]
Hey @slashben I would also like to give it a try.

**Comment by Ciggzy1312** [comment]
Hey @slashben as the scanned results are not returning the `fixPaths` but the cli is the problem might be with the package (https://github.com/kubescape/node-kubescape) that is scanning the YAML file and I thought of checking it out but came across an error that `Kubescape is not installed`

Any way to test it locally without facing the issue? Any help would be great

**Comment by slashben** [comment]
Hey @Ciggzy1312 ,
Try this command:

`kubescape scan -f json --format-version v2 https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/release/kubernetes-manifests.yaml | jq . | grep fixPath`

You will see that the Kubescape does return `fixPath` (not `fixPaths`, my bad if I misled you) 

You can also check out the actual structure in the output of the CLI (see `output.json`)

`kubescape scan -f json --format-version v2 -o output.json https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/release/kubernetes-manifests.yaml`

This is availabe for the [node-kubescape package](https://github.com/kubescape/node-kubescape). I think that you're right that the issue is there.

@amirmalka , can you help @Ciggzy1312 with the `Kubescape is not installed` issue?

**Comment by amirmalka** [comment]
@Ciggzy1312 Could you please advise how did you get this error? The VSCode extension is compiling and running without issues for me

I advise to anyone who's willing to work on this ticket to setup his dev environment as follows:
1. Clone [vscode-kubescape](https://github.com/kubescape/vscode-kubescape) repository
2. Run `npm install`
3. Launch VSCode extension in debug (.vscode configuration files are part of the project)
 
Upon success, a new VS code window should be opened with a debugger.
I would recommend to open some YAML files and play with the extension to explore its capabilities and understand how it works.

**Comment by Ciggzy1312** [comment]
Hey @amirmalka, sorry as I probably have misled you. I followed all the steps you and ben mentioned beforehand and found out that the scanned results from the [node-kubescape package](https://github.com/kubescape/node-kubescape) don't return `fixPath` and so I tried to check it out by setting it up locally

The problem I am facing is that whenever I am trying to do `npm link @kubescape/install` after linking the package locally and then running the vs-code extension instance and testing it out I am getting the following error
![image](https://user-images.githubusercontent.com/65884232/187248269-582792b1-1b3d-44c5-8c4f-78d2c2f10f5f.png)
I hope I make sense this time

I will keep digging in the code more but any leads from your side on why the error is appearing or where should I be looking into will be great

**Comment by amirmalka** [comment]
@Ciggzy1312 I assume you are getting this error because our vscode extension currently works with version `0.3.6` of `@kubescape/install`, while `npm link` links to the latest version?
I know there have been a few changes in the latest versions of `@kubescape/install` which would require code changes before using a newer version.

**Comment by Ciggzy1312** [comment]
Hey @slashben let me know if we want something like this
[Video url](https://user-images.githubusercontent.com/65884232/188274895-371e1589-0508-4218-8db2-2c49435c04c0.webm)

One thing to keep in mind is that the `fixPath` is not returned when we are using kubescape from `"/home/deepayan/Desktop/OSS/Kubescape/vscode-kubescape/install/kubescape"` but everything works fine when the relative path is replaced by just `kubescape` in the [node-kubescape package](https://github.com/kubescape/node-kubescape)
Also am working in the `0.3.6` but I think this should also work in `0.3.12`

Now the question is if it is a viable solution or if this is happening because of some versioning issues?

If yes, I can make a PR for this.
If no, -> Then do let me know what I should be working on 
         -> Or this issue can be stalled until the code changes being made to the `vs-code extension` for using plugin version `0.3.12` or maybe I can also work on the code changes to be made to the extension with a bit of help as I got very familiar with the codebase

**Comment by slashben** [comment]
@Ciggzy1312 awesome!!

It is a great start! I wanted something like this. Do you think it is possible to do it from a context menu (right click on mouse)? In general, my question is, would you (as a developer) be satisfied with this user flow?

About this issue with the missing fixPath: it looks indeed like a versioning issue (I am sure that the relative and absolute path invocations are pointing to different versions of Kubescape).

You can do a PR with it, we will test it as well and then discuss

**Comment by Ciggzy1312** [comment]
@slashben yes I think it would be possible to do it from a context menu and it would also be better from the user perspective.
But I would need a bit more clarification on exactly what we need to implement

Also before making PR which is just changing the path from relative to absolute(in `0.3.12` so it wouldn't even be in effect as of now) will it not be a better idea to first take care of the versioning issue if possible or even string up the `vs-code extension` with the current version of the plugin `0.3.12`

I was just curious if there is a community or developers meeting or even an office hours meeting to talk about issues that made a bit of progress, we might be able to discuss it there if it is allowed.

**Comment by slashben** [comment]
Hey

We will hold community meeting tomorrow at 14:00 GMT in Zoom (will push to
readme.md the link in a few minutes)

Want to join?

**Comment by Ciggzy1312** [comment]
@slashben yes, would love to join

**Comment by Ciggzy1312** [comment]
@slashben @dwertent created an issue regarding the versioning problem [here](https://github.com/kubescape/node-kubescape/issues/1)
Made the issue in the plugin repo rather than the extension repo as it is more of the plugin not pointing to the same version for relative and absolute path

And as for the user context feature will start working on it on the side in such a way that it will be compatible with the future versions so we can merge it as soon as we deal with the versioning issue

**Comment by amirmalka** [comment]
@Ciggzy1312 we have released a newer version of the `@kubescape/install` package, which uses the latest version of Kubescape and supports the new report format (v2).

**Comment by dwertent** [comment]
This should be part of the vs code epic once we decide to work on it
