### ISSUE TITLE
Exceptions not showing in list counter and not discarding issue

### ISSUE THREAD

**Issue by lamenawuer** [kubescape/kubescape#596]
While in the UI, inspecting the issues from a cluster I came upon what it seems a bug to me:

I marked all raised points (6) by kubescape as exceptions in an issue and:

- it does not show them in the issue preview. It shows "0" instead

- it does not close the issue

![Screenshot from 2022-08-17 14-57-31](https://user-images.githubusercontent.com/18737883/185140443-fb98c65e-7135-42c4-861e-9fe7df5ba312.png)

![Screenshot from 2022-08-17 14-57-54](https://user-images.githubusercontent.com/18737883/185140615-72425f08-dfa1-4aac-af41-16f260cabb07.png)

What is the point of marking things as exceptions if when marking all in an issue it does not close?

**Comment by lamenawuer** [comment]
HI @dwertent ,

Yes I did scan it afterwards and the list hasn't changed

**Comment by dwertent** [comment]
Do you still encounter such issues?
