### ISSUE TITLE
Feature request: Exception list

### ISSUE THREAD

**Issue by lamenawuer** [kubescape/kubescape#597]
It would be very useful if Kubescape could list all the exceptions in a cluster/namespace etc... It'd be easier to track down actual problems

**Comment by lamenawuer** [comment]
Hello @dwertent , 

Thanks for the answer, but I was hoping for a solution within the UI. We have Kubescape running as a helm chart and I would like to avoid sshing into the server pod just to see the exception list

**Comment by aiyushbedi007** [comment]
Hey !! I will like to work on this issue and start my contribution to kubescape.
Thanks!

**Comment by dwertent** [comment]
@lamenawuer We will have a solution from the UI, it is in our roadmap.
Unfortunately, w do not support it yet (from the UI).

**Comment by aiyushbedi007** [comment]
@dwertent i am fullstack Developer and i can work on the Frontend for this issue, is the Frontend repository open to contribution? Let's connect offline to discuss more on it.

**Comment by dwertent** [comment]
This is in the roadmap.
/cc @yossi77
