### ISSUE TITLE
Future enhancement  Image scan feature via kubescape command and Cancel scan feature for image scanning to be enabled ?

### ISSUE THREAD

**Issue by ijewelmas** [kubescape/kubescape#598]
I understand kubescape scan is used for misconfiguration scan within the cluster, but it could be good to have image scan of the cluster along with it as a future feature?
Since image vulnerability is only possible using helm and only visible in the UI at the moment, if some scan has got stuck it only shows pending and doesn't fail. In such a case could a cancel scan option be enabled in the future ?

**Comment by dwertent** [comment]
Thank you @ijewelmas for your great ideas.
In fact, we are planning on scanning the images using a CLI and not only from the HELM.

In addition we will add an option of canceling a scan after it has been triggered. 

FYI, We [open-sourced](https://github.com/kubescape) all of the components running within the cluster :)

**Comment by aiyushbedi007** [comment]
Hey !! I will like to work on this issue and start my contribution to kubescape.
Thanks!

**Comment by dwertent** [comment]
Hi @aiyushbedi007 , Thank you for willing to work on this.
We have a lot of design to do before coding, this might take a while.
We have this in our roadmap but we have not started working on it yet.

Stay tuned!

**Comment by AvineshTripathi** [comment]
Do we have any updates on this issue @dwertent maybe implementing the cli image scan can be done. Thoughts?

**Comment by AvineshTripathi** [comment]
Reminder ping @dwertent ^

**Comment by dwertent** [comment]
This has been merged (beta version):
```
kubescape scan --view=security --scan-images
```
