### ISSUE TITLE
Wrong remediation path for control c-0013 (Non-root containers)

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#599]
The path kubescape [suggests to fix](https://github.com/kubescape/regolibrary/blob/master/rules/non-root-containers/raw.rego#L37) is `spec.securityContext.runAsNonRoot=true` but the actual path is `spec.template.spec.containers[0].securityContext.runAsNonRoot=true` (when scanning a Deployment)

**Comment by i-am-yuvi** [comment]
Can I work on this?

**Comment by dwertent** [comment]
Sure.
@radoslawdob Can you please lead the solution?

**Comment by i-am-yuvi** [comment]
Ohh! Thanks I got it.

**Comment by dwertent** [comment]
[Merged](https://github.com/kubescape/regolibrary/pull/88)
