### ISSUE TITLE
Kubescape reports HTTP 400 with a malformed account ID

### ISSUE THREAD

**Issue by vladklokun** [kubescape/kubescape#605]
# Describe the problem
When a user runs a Kubescape command and specifies an account ID that is not a valid UUID, Kubescape reports an HTTP 400 Bad Request status code.

# Environment
OS: Ubuntu 22.04 LTS

Kubescape version (`kubescape version`):
```
Your current version is:
```

# Steps to Reproduce
1. Install Kubescape
2. Ensure that an accessible Kubernetes cluster is running.
3. Run Kubescape via `kubescape scan --account=invalidID`
4. Observe the resutls

# Expected Result
Kubescape reports that a given account ID is not a valid ID (UUID) and does not proceed with performing the operation.

# Actual Result
Kubescape proceeds as expected and briefly mentions that an error occurred while loading exceptions.

CLI output:
```
$ ./kubescape scan --account=invalidID --submit
[info] ARMO security scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
[warning] Kubernetes cluster nodes scanning is disabled. This is required to collect valuable data for certain controls. You can enable it using  the --enable-host-scan flag
[info] Downloading/Loading policy definitions
◓[error] failed to load exceptions. error: http-error: '400 Bad Request', reason: 'invalid customerGUID: invalid UUID length: 6'
[success] Downloaded/Loaded policy
[info] Accessing Kubernetes objects
[warning] failed to collect image vulnerabilities. error: credentials are not configured for any registry adaptor
[success] Accessed to Kubernetes objects
[info] Scanning. Cluster: minikube
[success] Done scanning. Cluster: minikube

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Controls: 58 (Failed: 39, Excluded: 0, Skipped: 5)
[SNIPPED]
```

**Comment by nalin-singh** [comment]
I would like to work on this issue

**Comment by 10kumaranurag01** [comment]
I would love to work on this issue.

**Comment by vladklokun** [comment]
@nalin-singh feel free to go ahead :)

I will be supporting your efforts, so if you need help, feel free to reach out to me. And please take a look at #577, especially the comment regarding how the validation should apply to commands that consume the `--account` flag.

**Comment by vladklokun** [comment]
@10kumaranurag01 Thanks for your willingness to help!

Seeing how having two people working on the same issue might be counterproductive, could you maybe take a look at our [other issues](https://github.com/kubescape/kubescape/issues?q=is%3Aissue+is%3Aopen+label%3A%22open+for+contribution%22) that are open to contributions?

**Comment by Deadpicker** [comment]
I am looking to contribute to this issue.
I am an total beginner can contribute?

**Comment by nalin-singh** [comment]
> @nalin-singh feel free to go ahead :)
> 
> I will be supporting your efforts, so if you need help, feel free to reach out to me. And please take a look at #577, especially the comment regarding how the validation should apply to commands that consume the `--account` flag.

Sure, I'm exploring the code right now and I did go through the comments on the other issue as well. If I would have to contact you are you on the kubescape discord ?

**Comment by Deadpicker** [comment]
> > @nalin-singh feel free to go ahead :)
> > 
> > I will be supporting your efforts, so if you need help, feel free to reach out to me. And please take a look at #577, especially the comment regarding how the validation should apply to commands that consume the `--account` flag.
> 
> Sure, I'm exploring the code right now and I did go through the comments on the other issue as well. If I would have to contact you are you on the kubescape discord ?

Yes I am on kubescape's discord You can find me there as my username Deadpicker

**Comment by nalin-singh** [comment]
> > > @nalin-singh feel free to go ahead :)
> > > I will be supporting your efforts, so if you need help, feel free to reach out to me. And please take a look at #577, especially the comment regarding how the validation should apply to commands that consume the `--account` flag.
> > 
> > 
> > Sure, I'm exploring the code right now and I did go through the comments on the other issue as well. If I would have to contact you are you on the kubescape discord ?
> 
> Yes I am on kubescape's discord You can find me there as my username Deadpicker

I wasn't reffering you @Deadpicker , I was reffering @vladklokun

**Comment by Deadpicker** [comment]
Mention man! @nalin-singh

**Comment by iks1** [comment]
Can i work on this issue?

**Comment by vladklokun** [comment]
@iks1 There’s already someone assigned to the issue.

In the meantime, I suggest you take a look at [other issues](https://github.com/kubescape/kubescape/issues?q=is%3Aissue+is%3Aopen+label%3A%22open+for+contribution%22) tagged as “open for contribution”.

**Comment by vladklokun** [comment]
@nalin-singh 

> Sure, I'm exploring the code right now and I did go through the comments on the other issue as well. If I would have to contact you are you on the kubescape discord ?

No, I’m not on Discord.

Let’s start by keeping the conversation here, so we can keep a paper trail and keep track of possible decisions we make. And if there is a need for a lengthy discussion, then we can talk on Discord :)

But please keep in mind that I expect you to propose a preliminary fix by yourself, given how it has already been proposed in #577, and expand the available fix to cover all commands that consume the `--account-id` flag. Then, we will polish your solution together to arrive at something we would like to merge.

So please keep try to open a PR as soon as you have something that works and adds value to #577, and we will take it from there. Deal?

**Comment by nalin-singh** [comment]
@vladklokun Sure

**Comment by nalin-singh** [comment]
> @nalin-singh
> 
> > Sure, I'm exploring the code right now and I did go through the comments on the other issue as well. If I would have to contact you are you on the kubescape discord ?
> 
> No, I’m not on Discord.
> 
> Let’s start by keeping the conversation here, so we can keep a paper trail and keep track of possible decisions we make. And if there is a need for a lengthy discussion, then we can talk on Discord :)
> 
> But please keep in mind that I expect you to propose a preliminary fix by yourself, given how it has already been proposed in #577, and expand the available fix to cover all commands that consume the `--account-id` flag. Then, we will polish your solution together to arrive at something we would like to merge.
> 
> So please keep try to open a PR as soon as you have something that works and adds value to #577, and we will take it from there. Deal?

@vladklokun Sure

**Comment by Saptaktdk** [comment]
[error] failed to discover API server information.
[error] failed to load exceptions. error: http-error: '400 Bad Request', 
[fatal] failed to get resource:


Iam getting this types of errors, any idea to solve it ?

**Comment by devmrfitz** [comment]
@vladklokun Can I take up this issue?
