### ISSUE TITLE
Including namespaces

### ISSUE THREAD

**Issue by Moshe-Rappaport-CA** [kubescape/kubescape#608]
# Describe the problem
When a user runs a Kubescape with `--include-namespaces` flag, he receives results on resources that are linked to RBAC from namespaces that are not included
# Environment
OS: Ubuntu 20.04.4 LTS  
  
kubescape version:  
```
Your current version is: v2.0.167
```
# Steps to Reproduce
1. Install Kubescape
2. Set up a cluster using Minikube via `minikube start`
3. Run Kubescape via `kubescape scan --include-namespaces "default" -v`
4. Observe the resutls

# Expected Result
When scanning, Kubescape looks and reports only the resources in the namespace `default`

# Actual Result
Kubescape scans and includes a ServiceAccount from the namespace `kube-system` which should not be included in the scan.

CLI output:
```
ApiVersion: 
Kind: ServiceAccount
Name: replication-controller
Namespace: kube-system

Controls: 9 (Failed: 1, Excluded: 0)

+----------+------------------+------------------------------------+-----------------------------------------+
| SEVERITY |   CONTROL NAME   |                DOCS                |          ASSISTANT REMEDIATION          |
+----------+------------------+------------------------------------+-----------------------------------------+
| Critical | Data Destruction | https://hub.armosec.io/docs/c-0007 | relatedObjects[1].rules[3].resources[0] |
|          |                  |                                    | relatedObjects[1].rules[3].verbs[1]     |
|          |                  |                                    | relatedObjects[1].rules[3].apiGroups[0] |
|          |                  |                                    | relatedObjects[0].subjects[0]           |
|          |                  |                                    | relatedObjects[0].roleRef.name          |
+----------+------------------+------------------------------------+-----------------------------------------+

```

**Comment by mhammadsaani** [comment]
I can work on this, if it is beginner friendly

**Comment by vladklokun** [comment]
> I can work on this, if it is beginner friendly

Hi, Muhammad!

You’re welcome to give it a try, but keep in mind that this issue is not exactly beginner-friendly: it would require taking a look at how Kubescape fetches resources, declares and resolves resources required to check a particular control and builds reporting data.

However, if you want to contribute, may I suggest you take a look at #605? That one is really beginner friendly, and there’s even an open PR #577 with a partial fix that you can apply to more commands.

**Comment by Moshe-Rappaport-CA** [comment]
Similar to #95

**Comment by sahilsuman933** [comment]
@Moshe-Rappaport-CA  can I work on this issue?

**Comment by Anubhavdevv** [comment]
@Moshe-Rappaport-CA I would like to contribute to the issue and try to understand how kubescape fetch resources work !
Looking forward to work on this issue !
It would be great if you could assign this issue to me !

**Comment by sakxshi** [comment]
Hey could you please mention the skills required to work on this?

**Comment by Moshe-Rappaport-CA** [comment]
Hey @Anubhavdevv 
It looks like you have the skills for this issue.
I assign this issue to you.
You are welcome to contact me at any stage.

**Comment by Anubhavdevv** [comment]
Sure Sounds Good 
I will start working on this !
Thank You !

**Comment by shivang2000** [comment]
hey @Anubhavdevv, @Moshe-Rappaport-CA.
can I also contribute to this as I think I will be able to do it?
