### ISSUE TITLE
I'm unable to join discord channel through given link in readme file

### ISSUE THREAD

**Issue by prajapatiomkar** [kubescape/kubescape#610]
![image](https://user-images.githubusercontent.com/72141037/185950826-91a8cb37-6dde-4a7c-9ffe-cdcdcf13e069.png)

**Comment by NirmitSawant** [comment]
Hey, You can join on this link: https://discord.com/invite/DWv4gPgCzU

Its present in the official site of kubescape: https://cloud.armosec.io/dashboard

**Comment by prajapatiomkar** [comment]
Thanks i made change in README file and created pr

**Comment by dwertent** [comment]
Fixed #616
