### ISSUE TITLE
README - installation url broken 

### ISSUE THREAD

**Issue by HawkingRadiation42** [kubescape/kubescape#639]
# Describe the bug
In README, the TL;DR section has URL for installation on Mac OS, windows and go along with others to redirect the page for installation of the particular operating system.
But after clicking on the URL it redirects to the same repository 

Its better to remove the specific URLs for various way for installation as the above curl command is there 
or 
better to fix the URL by redirecting it to that specific operating system installation.

**Comment by thisiskaransgit** [comment]
We can just fix the URL as it is easier to have a specific installation guide for each OS 
I would like to fix this issue ⚒️

**Comment by om2137** [comment]
it was fixed in #627
