### ISSUE TITLE
Typo in `kubescape/docs/roadmap.md`

### ISSUE THREAD

**Issue by bishal7679** [kubescape/kubescape#643]
# Describe the bug
A clear typo is there on [kubescape](https://github.com/kubescape/kubescape)/[docs](https://github.com/kubescape/kubescape/tree/master/docs)/roadmap.md

# Expected behavior
The typo `Confiugration` should be corrected to `configuration`

# Actual Behavior

![Screenshot (284)](https://user-images.githubusercontent.com/70086051/186203220-0db8f1ca-7316-4c94-a6f3-4c336d7216a3.png)

**Comment by npneeraj** [comment]
Please assign it to me since i am newbie to open-source.

**Comment by Hirdey-1999** [comment]
You Can Merge The My PR https://github.com/kubescape/kubescape/pull/645

**Comment by bishal7679** [comment]
@KanishkaVerma054 @Hirdey-1999 
Thanks for showing interest
Actually a PR against this issue is already raised #644
So try to not raise any further PR please, it can generate conflicts
You can go for another opened issue

**Comment by dwertent** [comment]
Merged #645
