### ISSUE TITLE
Typos in  `examples / prometheus / README.md`

### ISSUE THREAD

**Issue by bishal7679** [kubescape/kubescape#646]
# Describe the bug
Typo is there `vulinrability`

# Screenshot

![Screenshot (285)](https://user-images.githubusercontent.com/70086051/186211675-6d136aeb-9dce-4ba6-8164-07ba8331ac4b.png)

# Expected behavior
typo `vulinrability` should be changed into `vulnerability`

**Comment by dwertent** [comment]
Hi @bishal7679 , thank you for reporting.
I suggest you should open a PR with a fix :)
