### ISSUE TITLE
Typos in Error message and change const variable name

### ISSUE THREAD

**Issue by bishal7679** [kubescape/kubescape#649]
# Describe the bug

- It will increase better readability if we change the const variable name to `prometheusMetricsPath` from `prometheusMmeticsPath`
- The error message typo in fmt.Errorf()

```go
   pair, err := tls.LoadX509KeyPair(certFile, keyFile)
   if err != nil {
	   return nil, fmt.Errorf("filed to load key pair: %v", err)
   }
   return &pair, nil
```
# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

# Expected behavior

1. ```go
   pair, err := tls.LoadX509KeyPair(certFile, keyFile)
   if err != nil {
	   return nil, fmt.Errorf("failed to load key pair: %v", err)
   }
   return &pair, nil
   ```

2. change the const variable name to `prometheusMetricsPath` from `prometheusMmeticsPath`


File link :-https://github.com/kubescape/kubescape/blob/master/httphandler/listener/setup.go

**Comment by dwertent** [comment]
Hi @bishal7679 Thank you for reporting.
Please feel free to open a PR with the relevant fixes.

**Comment by bishal7679** [comment]
> Hi @bishal7679 Thank you for reporting. Please feel free to open a PR with the relevant fixes.

Already raised a PR for this
