### ISSUE TITLE
Typo Function name `sumObj.ListOfDangerousArtifcats`

### ISSUE THREAD

**Issue by bishal7679** [kubescape/kubescape#653]
# Describe the bug
- Typo in function of sumObj

```go
if len(sumObj.ListOfDangerousArtifcats) != 3 {
		t.Errorf("sumObj.ListOfDangerousArtifcats = %v", sumObj.ListOfDangerousArtifcats)
	}
```
- It would be better if we write `res != 0` instead of `0 != res`

```go
func TestCalculateFixed(t *testing.T) {
	res := CalculateFixed([]FixedIn{{
		Name:    "",
		ImgTag:  "",
		Version: "",
	}})
	if 0 != res {
		t.Errorf("wrong fix status: %v", res)
	}
}
```

# Expected behavior
- `sumObj.ListOfDangerousArtifcats` should be `sumObj.ListOfDangerousArtifacts`
-
```go
func TestCalculateFixed(t *testing.T) {
	res := CalculateFixed([]FixedIn{{
		Name:    "",
		ImgTag:  "",
		Version: "",
	}})
	if res != 0 {
		t.Errorf("wrong fix status: %v", res)
	}
}
```

File link :- https://github.com/kubescape/kubescape/blob/master/core/pkg/containerscan/containerscan_test.go

**Comment by iamhardikat11** [comment]
Greetings my name is Hardik Soni. I am have decent knowledge of DevOps, Open-Source and Kubernetes.I would like this issue up, please assign this to me.

**Comment by dwertent** [comment]
Hi @bishal7679 , thank you for reporting.
I suggest you should open a PR with a fix :)
