### ISSUE TITLE
HyperLink Broken in README.md

### ISSUE THREAD

**Issue by iamhardikat11** [kubescape/kubescape#666]
# Describe the bug
In the TL, DR Sections on Installation of all the links to ```Install using Go```, ```Install in MacOS``` are broken.
I will solve this and submit a PR.
Thanks and Regards.

**Comment by iamhardikat11** [comment]
I hope in the Docs we have terminal commands provided to install KubeScape on MAC OS, Windows, Linux as well as Nix OS, but it lacks Installation of Golang, which is a dependency to run it on a local machine. So adding docs and support for the same.
Thank you.

**Comment by dwertent** [comment]
Fixed #637
