### ISSUE TITLE
Making image scan results available in the cluster

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#668]
**Description**
Kubescape microservices scanning container images for vulnerabilities in the cluster. The results today are posted to ARMO cloud (https://cloud.armosec.io). They should be kept in the cluster to make it available for other applications as well. Even kubescape scanner could use the results locally without the need of coming through the ARMO cloud APIs.

**Describe the solution you'd like**
I would like Kubescape microservices to keep relevnt image scan results as CRDs in the cluster. Every new scan report should be stored (together with the SBOM) in CRDs and old results for the same workloads could be discarded (as well as reports which does not have corresponding images in the cluster anymore).

**Additional context**
This would enable feeding the results to Prometheus as well.

**Comment by kushagra-gupta01** [comment]
Can you please assign me for this issue?
I would love to contribute.

**Comment by slashben** [comment]
> Can you please assign me for this issue? I would love to contribute.

Just did :)

Please be in touch with @dwertent about implementation guidlines

**Comment by kushagra-gupta01** [comment]
ok sure

**Comment by npneeraj** [comment]
Hi @slashben I would also like to contribute to this issue.

**Comment by satvik2131** [comment]
I want to work on this issue , please assign and guide me regarding it .

**Comment by Aman123lug** [comment]
@slashben can you me assign me this project i love to contribute

**Comment by slashben** [comment]
@npneeraj , @satvik2131 , @Aman123lug , this issue has already been assigned to someone. If you want to check with him, please reach out directly to @kushagra-gupta01

**Comment by vinayak-0017** [comment]
> ok sure

heyy man , can I work with you on this issue??

**Comment by vinayak-0017** [comment]
@kushagra-gupta01  hey man, can I work with you on this issue?

**Comment by priyansu-nayak** [comment]
@kushagra-gupta01  Can we collab on this ?

**Comment by harshitasao** [comment]
Hi, @slashben @dwertent. I'd like to work on this as there hasn't been any progress. I think I understand the issue and the approach required, if necessary, I can prepare a proposal. So, could you please provide the implementation guidelines?

**Comment by dwertent** [comment]
This issue is a feature request related to the [Kubevuln](https://github.com/kubescape/kubevuln) component.

Currently, Kubevuln runs as a microservice that receives an image as input. The Kubevuln scans the image (using [Grype](https://github.com/anchore/grype)) and submits the results to the kubescape SaaS.
We will need to make the following changes in the Kubevuln: 
1. Extract the image SBOM (in addition to the results)
2. Store SBOM and scan results as CRD's
3. When scanning an image, the Kubevuln will first search if the image has an available SBOM. If so, the Kubevuln will pass Grype the SBOM and not the image tag.
5. Remove SBOMs of images that are no longer running in the cluster (the [Kollector](https://github.com/kubescape/kollector) should do this)
6. Remove older image scanning results

Once we complete this, we can update the Kubescape so it will load the image scanning results CRD's instead of downloading them from the Kubescape SaaS.

**Comment by legendarykamal** [comment]
Thankyou @dwertent for the explaination, it surely clears many things :)

**Comment by maheshsk28211** [comment]
@kushagra-gupta01 can I work with you on this feature. I'm clear about reqs & implementation regarding this. @slashben

**Comment by maheshsk28211** [comment]
@slashben @dwertent please assign this feature to me, I'm halfway into it.

**Comment by maheshsk28211** [comment]
@dwertent should CRD changes be part of kubevuln project or separate repository

**Comment by maheshsk28211** [comment]
> This issue is a feature request related to the [Kubevuln](https://github.com/kubescape/kubevuln) component.
> 
> Currently, Kubevuln runs as a microservice that receives an image as input. The Kubevuln scans the image (using [Grype](https://github.com/anchore/grype)) and submits the results to the kubescape SaaS. We will need to make the following changes in the Kubevuln:
> 
>     1. Extract the image SBOM (in addition to the results)
> 
>     2. Store SBOM and scan results as CRD's
> 
>     3. When scanning an image, the Kubevuln will first search if the image has an available SBOM. If so, the Kubevuln will pass Grype the SBOM and not the image tag.
> 
>     4. Remove SBOMs of images that are no longer running in the cluster (the [Kollector](https://github.com/kubescape/kollector) should do this)
> 
>     5. Remove older image scanning results
> 
> 
> Once we complete this, we can update the Kubescape so it will load the image scanning results CRD's instead of downloading them from the Kubescape SaaS.

should CRD changes be part of kubevuln project or separate repository

**Comment by maheshsk28211** [comment]
I have created spdx format CRD for initial implementation, there are multiple formats of sbom output.  I'm writing a parser to parse output of sbom  generated and convert to crd object. is this approach correct ?

**Comment by siddhikhapare** [comment]
@dwertent  I want to work on this issue https://github.com/kubescape/kubescape/issues/669. but above issue is related to it so I am also trying to scan image results. I scanned image and it's SBOM in json format using grype and syft.  can you provide me setup guidance of kubevuln with grype to scan images. From https://github.com/kubescape/kubevuln/blob/master/README.md this markdown file by using make build command give me  error  that is make: *** [makefile:15: build] error 127.
output in json -
first I genrate sbom of image and then scanned it with grype
https://github.com/siddhikhapare/screenshots/blob/main/imagesbominjson.PNG

**Comment by dwertent** [comment]
@slashben I'm not sure this is the right place for the feature request. 
This has more to do with Kubevuln than with Kubescape.

**Comment by slashben** [comment]
It can be moved from my POV

**Comment by maheshsk28211** [comment]
I was on vacation due to Diwali festival over here, will resume my work on this.

**Comment by dwertent** [comment]
Closing this issue since it is not related directly to Kubescape as described [here](https://github.com/kubescape/kubescape/issues/668#issuecomment-1244946591).

Supporting this issue will require refactoring the Kubevuln component. We will open a separate design document for this.
