### ISSUE TITLE
Make image scanning results available for Prometheus

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#669]
**Description**

Image scanning reports/results should be made available for Prometheus stack

**Describe the solution you'd like**
This feature depends on #668 . When it is completed, Kubescape microservices should create an exporter endpoint for Prometheus

**Comment by Hirdey-1999** [comment]
Can I Work On This Issue

**Comment by slashben** [comment]
Sure @KlausMikhaelson @Hirdey-1999 , but please not that there is a dependency here #668

**Comment by SrijanShovit** [comment]
Hi @slashben I would like to contribute in this issue ,Could you please share resources that so as to understand this issue and start contributing asap as I am new to Kubernetes

**Comment by Aman123lug** [comment]
@slashben @Hirdey-1999 @KlausMikhaelson @taylor can you assign me this project please i want to work on it i already learn kubernetes docker all these thing i want to work on it.

**Comment by nitishmalang** [comment]
hi can I work on this issue

**Comment by Aman123lug** [comment]
still this feature are open no one can will create this okay .. i will create this @slashben

**Comment by dwertent** [comment]
As explained [here](https://github.com/kubescape/kubescape/issues/668#issuecomment-1321051487), we will work on this issue with a proper design document and not have the related discussions here in the GitHub issues.
