### ISSUE TITLE
Enrich RoleBinding/ClusterRoleBinding objects with cloud vendor infromation

### ISSUE THREAD

**Issue by slashben** [kubescape/kubescape#670]
**Is your feature request related to a problem? Please describe.**
Kubescape today scans a lot of RBAC objects. The RoleBinding objects (both namespace and cluster level) are binding users and groups to roles. This user and group descriptions are not enough alone and the user needs to go to the cloud vendor API to find out who is really behind the given identity.

**Describe the solution you'd like**
It would be great if Kubescape could retrieve this information from the cloud vendor API and present the results with this resolution.

**Comment by i-am-yuvi** [comment]
Can I work on it? @slashben

**Comment by dwertent** [comment]
@i-am-yuvi  I'm sure you can start working on this.
You will need to update the [cloudsupport](https://github.com/kubescape/k8s-interface/tree/master/cloudsupport) package for this.

**Comment by i-am-yuvi** [comment]
Sure, Thnks for letting me know

**Comment by YashRajSingh-4799** [comment]
Hi, am looking to contribute to this issue.
Can I work on it? @slashben

**Comment by aparna2071** [comment]
Hi @slashben I would also like to contribute to this issue.

**Comment by SrijanShovit** [comment]
Hi @slashben  I would like to contribute in this issue ,Could you please share resources that so as to understand this issue and start contributing asap as I am new to Kubernetes

**Comment by npneeraj** [comment]
Hi @slashben I would also like to contribute to this issue. Plz share some resources to get started with.

**Comment by Coolsum4** [comment]
Hi @slashben I would like to contribute to this issue, can share some resources so we can understand the issue properly

**Comment by rakshitgondwal** [comment]
Hey guys, I think @i-am-yuvi is already working on this issue. I would suggest you all to look up for some other issue or try raising a new issue from your own but if you guys have some leads on issue already then you can try collaborating with @i-am-yuvi to solve this issue together.

**Comment by i-am-yuvi** [comment]
Yaa I would agree to @rakshitgondwal. You can even start contributing to it without asking as maintainers are busy in other stuffs too.

**Comment by Aman123lug** [comment]
@slashben hey please assign me this project i love to contribute in open source and this is great opportunity for me.

**Comment by DeeptanshuDas** [comment]
Hi @slashben  I would like to contribute in this issue.

**Comment by slashben** [comment]
As said before, @i-am-yuvi is already working on this. Please be in touch with him. He might divide the work into sub-tasks (GCP vs AWS and etc.)

**Comment by shashankdaima** [comment]
@i-am-yuvi  are you still working on this? can we collab for this issue?

**Comment by i-am-yuvi** [comment]
@shashankdaima yaa I'm still working on it. We can collab for sure. Go through the docs before jumping to the repos.

**Comment by i-am-yuvi** [comment]
i_m_yuvi#9537 there you go @shashankdaima

**Comment by devmrfitz** [comment]
@i-am-yuvi Would you like a hand on this?

**Comment by i-am-yuvi** [comment]
@devmrfitz sure why not

**Comment by priyansu-nayak** [comment]
@i-am-yuvi @shashankdaima Can we collab for this issue?

**Comment by i-am-yuvi** [comment]
@dwertent Can you help us on this?

**Comment by ash-kamrip** [comment]
Hi @slashben , @dwertent 

Since this requires changes to the k8s-interface repo , I have opened a PR on the repo k8s-interface , I don't know how to link that PR in this repo. Could you take some time to review it ?

**Comment by dwertent** [comment]
@ash-kamrip any progress here?

**Comment by ash-kamrip** [comment]
Hi @dwertent , so https://github.com/kubescape/k8s-interface/pull/6  was recently merged on k8s-interface if you think this concluded everything that needs to cover checkpoints of this issue , I think we're done here  😄

**Comment by dwertent** [comment]
Thank you @ash-kamrip , I see this is for EKS.
Do you have a screenshot you can share so the end results will be visible?

@slashben Should we open tickets for each cloud vendor separately?

**Comment by slashben** [comment]
Yes

**Comment by ash-kamrip** [comment]
I don't understand  ? screenshot for what exactly . Also I will try to implement it for other 2 cloud vendor as well

**Comment by ash-kamrip** [comment]
Hi @dwertent  I was just going through a implementation for azure support and found that one of the packages `containerservice` is deprecated , I think opening up different PR's now would be a good idea. Also wanted to know what were the project goals around this? are you guys planning for a upgrade or how is it gonna be, Let me know if there's a link to this discussion or anything.

**Comment by dwertent** [comment]
Hi @ash-kamrip , Sorry, I missed your comment.
No, I was not aware of the deprecation of the containerservice package.
Can you please share some more info about this, and how is this related to this feature?

**Comment by ash-kamrip** [comment]
hi @dwertent , right now this containerservice isn't doing much , it's just being used for authorization and to create a instance of ManagedCluster client  for aks cluster

**Comment by ash-kamrip** [comment]
Hi @dwertent , 

I've added support for Azure Cluster and raise a pull request on k8s-interface repo. 

> adding ListAllRolesForScope function to list Azure Roles #11

Kindly review , once you have a moment.

Regards, 
Ashu

**Comment by slashben** [comment]
> Is this issue still open for grabs?

I looks stale so I guess yes

**Comment by adityachouh** [comment]
is this issue still open
i want to contribute in it
if it is open,please guide me.

**Comment by rakshitgondwal** [comment]
> is this issue still open i want to contribute in it if it is open,please guide me.

Yes, it is!

**Comment by ash-kamrip** [comment]
just for FYI,  under this request I couldn't work towards any kind of contribution for clusters in google cloud so anybody interested can start from there i guess.

**Comment by DhruvSinghiitmandi** [comment]
Hi if this issue is open can i be assigned this issue I want to start contributing  in KubeScape

**Comment by XDRAGON2002** [comment]
> Hi if this issue is open can i be assigned this issue I want to start contributing  in KubeScape

Feel free to go ahead and open a PR!

Most times the maintainers are busy with a lot of things so they might not respond promptly.

But PRs are always welcome to the repo ;)

**Comment by dwertent** [comment]
We would have a proper design for this when we would want to implement it
