### ISSUE TITLE
Typos in docs/proposals/container-image-vulnerability-adaptor.md

### ISSUE THREAD

**Issue by bishal7679** [kubescape/kubescape#673]
# Describe the bug
Typo is `picutre`

# Expected behavior
Typos `picutre` should be changed into `picture`

**Comment by RohitYandigeri** [comment]
I fixed the typo

**Comment by RohitYandigeri** [comment]
[https://github.com/kubescape/kubescape/pull/678#issue-1349466893](url)

**Comment by bishal7679** [comment]
@RohitYandigeri where?

**Comment by bishal7679** [comment]
Kindly check the current content
And typo is there

**Comment by RohitYandigeri** [comment]
> Kindly check the current content
> And typo is there

Can you please close your PR as a newbie I want to merge the PR

**Comment by dwertent** [comment]
> as a newbie I want to merge the PR

@RohitYandigeri I wish you best of luck :)
