### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by souravsk** [kubescape/kubescape#681]
# Describe the bug
After cloning the project locally I was build the project by running the first command as mention in the Readme  file
` make libgit2 `
but it shows 2 error

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

# Actual Behavior
A clear and concise description of what happened. If applicable, add screenshots to help explain your problem.
![make](https://user-images.githubusercontent.com/33636054/186444662-515d300b-00c3-4d7c-9fd4-64149201e7a2.png)

**Comment by dwertent** [comment]
Did you check you dir permissions?

**Comment by souravsk** [comment]
![Screenshot from 2022-08-25 12-29-07](https://user-images.githubusercontent.com/33636054/186596797-e63fbeda-a6c7-4784-ac92-828de05dad8f.png)
yes I think it has all the necessary permission. Please let me if it need more

**Comment by souravsk** [comment]
@dwertent  
The permission issue is solved but now it says there is a missing file
![Screenshot from 2022-08-26 12-38-13](https://user-images.githubusercontent.com/33636054/186843739-c292bfba-9a11-426d-adef-2ae197abdbcf.png)
.

**Comment by souravsk** [comment]
I tried using the vs code but the problem remain same there is some missing file

![Screenshot from 2022-08-27 16-26-07](https://user-images.githubusercontent.com/33636054/187027400-8022fbdf-4950-47a2-9b1e-b069ce2041f8.png)

**Comment by dwertent** [comment]
@amirmalka Did you see this before?

**Comment by amirmalka** [comment]
@souravsk `pkg-config` & `cmake` are needed. In your case I can see that `pkg-config` is missing

I don't have an ubuntu machine to confirm but I would say that the following commands should install it:
```
sudo apt-get update
sudo apt-get -y install pkg-config
```

Please advise if it solves your issue

**Comment by souravsk** [comment]
@amirmalka thank you it worked I have tried precisely but I didn't at that time but for some reason, it is working now.
