### ISSUE TITLE
Killercoda KubeScape Playground fails to load

### ISSUE THREAD

**Issue by orrgato** [kubescape/kubescape#683]
# Describe the bug
The KubeScape playground mentioned in the [README.md file](https://github.com/kubescape/kubescape#playground) fails to load the scenario.
<img width="1440" alt="The Killercoda Screen failing to load KubeScape Scenario" src="https://user-images.githubusercontent.com/89532792/186490444-33dab15a-725b-4fc0-b2c0-bdfddc28c874.png">

# Environment
The playground runs on [KillerCoda's Website](https://killercoda.com/saiyampathak/scenario/kubescape)

# Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to 'https://killercoda.com/saiyampathak/scenario/kubescape'
2. Click on 'Start Icon on the left'
3. See error in the terminal on right side of the screen.

# Expected behaviour
An ubuntu terminal with KubeScape installed.

# Actual Behavior
The Scenario tries to run 
`VERSION=$(curl --silent "https://api.github.com/repos/armosec/kubescape/releases/latest" | jq -r .tag_name)` command,
 but the Command `jq` is not found which gives the error.
<img width="1440" alt="The error that occurs after running the command" src="https://user-images.githubusercontent.com/89532792/186489721-72a6bd42-c458-4b35-bff1-82c4322b4774.png">

# Additional context
After manually installing `jq` through `apt install jq` as suggested in the terminal, and manually running the command
`VERSION=$(curl --silent "https://api.github.com/repos/armosec/kubescape/releases/latest" | jq -r .tag_name)`
fails to store the latest version of KubeScape in `VERSION` which breaks the scenario as `VERSION` is required by subsequent commands.

**Comment by MaruthiKo** [comment]
I have tried to recreate the bug by following the steps you have provided.
This is what I have got:
![github](https://user-images.githubusercontent.com/63769209/186563601-dbfcc815-0cec-4eb0-9eb8-34602edf525e.png)

**Comment by orrgato** [comment]
@MaruthiKo Yes and the next command that should be executed is `wget https://github.com/armosec/kubescape/releases/download/$VERSION/kubescape-ubuntu-latest`, but running that gives the following error,
<img width="949" alt="Terminal screen after running the command" src="https://user-images.githubusercontent.com/89532792/186565448-ead8c03a-0b13-403b-bfa7-e2d5fbd9aebc.png">

It has the value of `VERSION` as `null`.

**Comment by suhasgumma** [comment]
Quick Solution to Use Killercoda Playground Immediately: Run the following Commands after the playground opens and shows the above-described error:

```
apt install jq 
```
```
VERSION=$(curl  -L --silent "https://api.github.com/repos/armosec/kubescape/releases/latest" | jq -r .tag_name) 
```
```
wget https://github.com/armosec/kubescape/releases/download/$VERSION/kubescape-ubuntu-latest 
```
```
chmod +x kubescape-ubuntu-latest && 
mv kubescape-ubuntu-latest kubescape && 
mv kubescape /usr/local/bin/
```

**Comment by suhasgumma** [comment]
# Permanent Solution

## Root Causes
* 'jq' library is not installed in the playground. It might have been installed by default when the author was creating the playground but it's not installed now.
* The URL which is used to get the 'VERSION' was moved from "https://api.github.com/repos/armosec/kubescape/releases/latest "  to "https://api.github.com/repositories/395283401/releases/latest"
## Solution
1. Install 'jq' by running 'apt install jq'
2. Add "-L" tag to the command so that it can fetch information from the new link. Final Command looks like this.
```
VERSION=$(curl  -L --silent "https://api.github.com/repos/armosec/kubescape/releases/latest" | jq -r .tag_name) 
```

@saiyam1814 , Could you please look into this?

**Comment by saiyam1814** [comment]
Would you like to raise a PR for this ? @suhasgumma

**Comment by suhasgumma** [comment]
> Would you like to raise a PR for this ? @suhasgumma

In my understanding, I have to make changes in the "https://github.com/saiyam1814/katacoda-scenarios" repository to solve this issue. Is there a way to open a pull request here?

**Comment by saiyam1814** [comment]
Yes just open the PR in above repo and once merged, it will be reflected in the scenarios

**Comment by orrgato** [comment]
That would solve the issue. 
@suhasgumma, Could you please let me know once you make the pr, so I can close this issue.

**Comment by suhasgumma** [comment]
> Yes just open the PR in above repo and once merged, it will be reflected in the scenarios

Done!! I opened the PR in your katakoda-scenarios. Thanks for the help @saiyam1814

**Comment by suhasgumma** [comment]
> That would solve the issue. @suhasgumma, Could you please let me know once you make the pr, so I can close this issue.

Yes, will let you know once the issue is solved.

**Comment by suhasgumma** [comment]
#saiyam1814/katacoda-scenarios#4

**Comment by saiyam1814** [comment]
I have tested and it works fine now

**Comment by suhasgumma** [comment]
Thank you Saiyam!! @orrgato, you can close the issue now.

**Comment by orrgato** [comment]
I learnt a lot from opening this issue. 
Thank you @suhasgumma, @saiyam1814.
