### ISSUE TITLE
Improving the Readme

### ISSUE THREAD

**Issue by legendarykamal** [kubescape/kubescape#689]
# Describe the bug
 
Currently, the icon in the readme is left aligned including the badge below it which doesn't look good. 
2> It asks for liking but there is no way people can react to that call

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

# Expected behavior

1> It can be centre aligned giving it a better look and feel. 
2> we can ask users to give a ⭐ to the report instead. 

.

**Comment by satyamkale27** [comment]
Can you please assign me for this issue?

**Comment by satyamkale27** [comment]
ok

**Comment by legendarykamal** [comment]
@vladklokun please assign me this issue .

**Comment by ryuusama09** [comment]
Is this issue now closed , if not then please assign it to me
