### ISSUE TITLE
Adding a progressbar when downloading kubescape from powershell

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#703]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when download it from powershell it didn't show me how much content is downloaded and how much still to be downloaded due to that i quit it many time if i have slow internet connection

**Describe the solution you'd like**

You can solve it by just adding a progress bar of 100% and showing how much percentage is downloaded and how much remaining

**Comment by satyamkale27** [comment]
Can you please assign me for this issue?

**Comment by satvik2131** [comment]
I am interested to contribute here , let me know if I can start ?

**Comment by muppinesh** [comment]
Hi Vicky, I am interested to solve this issue. Can you assign me this

**Comment by pwnb0y** [comment]
> Hi, I would like to work on this issue

Sorry, @MaruthiKo  I have started working on this already.
But I will open more issues soon, look out for them 🙂

**Comment by MaruthiKo** [comment]
> > Hi, I would like to work on this issue
> 
> Sorry, @MaruthiKo  I have started working on it already.
> But I will open more issues soon, look out for them 🙂

Alright sure✌️

**Comment by pwnb0y** [comment]
🙂 Need help: 

#Progress bar script of PowerShell to download Kubescape 
$fullurl= https://github.com/kubescape/kubescape/releases/download/v2.0.168/kubescape-windows-latest 
$Total_size= (Invoke-WebRequest -Uri $fullurl -Method Head).Headers.' Content-Length'
$Downloaded_size=0
while($Downloaded_size -lt $Total_size){
 $downloaded_percentage= ((100/$Total_size)*$Downloaded_size)+1
 [MATH]::Floor($downloaded_percentage)
 $Downloaded_size += ? 
 }
 
 #here is how to fetch real-time downloaded size during the downloading process without using any buffer operation

**Comment by craigbox** [comment]
Closed by #716.
