### ISSUE TITLE
Kubescape fails to authenticat remote private github repo

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#710]
# Bug description
Kubescape fails to clone private github repositories because the authentication is not working

# Environment
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168
```

# Steps To Reproduce

1. Setup GITHUB_TOKEN env
```
export GITHUB_TOKEN=XXXXXX
```
2. Scan remote repo
```
kubescape scan https://github.com/org/private-repo
``` 

# Expected behavior
Kubescape should clone the repo and scan 

# Actual Behavior
Authentication failed:
```
[fatal] failed to clone git repo 'https://github.com/org/private-repo',  failed to clone private-repo'. authentication required
```
# Additional context
Kubescape [is not using](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/remotegitutils.go#L23) the token when cloning the repo ->
```
	cloneOpts := git.CloneOptions{URL: cloneURL, Auth: <add auth function name>}
```

**Comment by suhasgumma** [comment]
Can I work on this @dwertent ?

**Comment by dwertent** [comment]
@suhasgumma Any ETA?

**Comment by ShivanshCharak** [comment]
this bug seems interesting, i am second in the line

**Comment by suhasgumma** [comment]
> @suhasgumma Any ETA?
Are you asking estimated time??

**Comment by ShivamTyagi12345** [comment]
Is this issue good for the ones who have only a prefatory idea of the code base  @dwertent Or does it require a higher level of familiarity?

**Comment by suhasgumma** [comment]
> > @suhasgumma Any ETA?
> > Are you asking estimated time??

I am almost done!!
