### ISSUE TITLE
Issue with Running KubeScape on Mac OS

### ISSUE THREAD

**Issue by iamhardikat11** [kubescape/kubescape#711]
I have a MacOS System, we have some issues mentioned particularly for Ubuntu System. If I have to work on them, should I switch to a Linux Based Operating System, or can I use a VM Like Parallels. I can't afford to buy another machine just to do development. I am facing problems with VM like Parallels failing to install GoLang and Visual Studio Code as Debian Distribution support amd64 architecture and my m1 is arm64. Please Guide.

**Comment by dwertent** [comment]
You can use a VM, but there is no need.
