### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by ShivanshCharak** [kubescape/kubescape#712]
**Is your feature request related to a problem? Please describe.**
I was trying to update kubescape's version but i didn't find update command, so i first uninstalled the cli and then reinstalled it for the new version
**Solution**
I think it would be great if we add update command in the cli.

**Comment by ShivamTyagi12345** [comment]
Hey @ShivanshCharak  Can you please add any additional info on this issue,Maybe `steps to reproduce the bug`? Thank You😊

**Comment by shivang2000** [comment]
@ShivamTyagi12345 i think @ShivamTyagi12345 is asking for a feature like npm install -h npm or just simply run 

kubescape update 
to go from lets say v1.1 -> v1.2

**Comment by satyamkale27** [comment]
i would like to work on this feature

**Comment by dwertent** [comment]
@ShivamTyagi12345 This might require writing permissions, which are usually not granted.
But in general, I think this is a great idea.

## Requriments
Add `kubescape update` command
We should support an additional `-v`/`--version` flag for downloading a specific version

## User story
When the user runs this command, kubescape will re-install to the latest/specified version. 
If the command fails, Kubescape should print the [download command](https://github.com/kubescape/kubescape#install).

## Good to have
When running the `kubescape scan`/`kubescape version`, if the version is not the latest, kubescape should propose to the user to run `kubescape update` 
 
## DoD
An example of the command working and failing.

**Comment by ShivanshCharak** [comment]
@dwertent so can we contribute to this issue? I think this one most relevant to me to start with

**Comment by legendarykamal** [comment]
hi @dwertent thankyou for the detailed info , I would love to contribute on this @vladklokun @dwertent can you please assign me this issue?

**Comment by Aryan-Deshpande** [comment]
Hey, this issue seems interesting and would love to start working on this !.
