### ISSUE TITLE
Steps not defined in the Job for Github actions

### ISSUE THREAD

**Issue by Yh010** [kubescape/kubescape#713]
https://github.com/Yh010/kubescape/actions/runs/2938641745/workflow

No steps have been defined for the first job, resulting in an invalid workflow file/ failure in running checks for, say, a PR for correction of grammatical errors

**Comment by MaruthiKo** [comment]
Hi,I would like to work on this issue

**Comment by ryuusama09** [comment]
hi , I would like to help here

**Comment by suhasgumma** [comment]
Hi @Yh010, #755 Solved this issue. Could you please check if the issue is still there? 
If not, you can close the issue.
