### ISSUE TITLE
install.ps1 script is not working on microsoft azure cloud VM

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#717]
# Describe the bug
When I fire up the command in Powershell to download kubescape on my azure cloud VM error will occur.

# Environment
OS: Microsoft Windows NT 10.0.19044.0
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168  
```

![issue](https://user-images.githubusercontent.com/96813659/187147756-06754975-b4ce-4649-9b77-19f1d9d31a87.png)

**Comment by pwnb0y** [comment]
Hey @dwertent i pull request for this issue please marge it

**Comment by pwnb0y** [comment]
Assign me first please

**Comment by dwertent** [comment]
Hi @pwnb0y I am testing your PR :)

**Comment by dwertent** [comment]
@Moshe-Rappaport-CA Any updates here?

**Comment by Moshe-Rappaport-CA** [comment]
@dwertent I did tests for @pwnb0y PR (#720), and everything works well.

**Comment by dwertent** [comment]
Merged
