### ISSUE TITLE
Scan Kustomize charts

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#718]
**Description**
Currently, Kubescape scans YAMLs and Helm templates but not [kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) charts.

**Additional context**
Kubescape should generate the Kubernetes YAMLs from the Kustomize chart and scan the files.
This should work similarly to the [helm chart](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L118) scanning mechanism

**Comment by PratikDey** [comment]
Hi @dwertent , can I work on this issue?

**Comment by dwertent** [comment]
Please take a look at how we implemented this with helm.
In a word - we generated the YAML objects from the templates, and we scanned those objects.

Also here, we will need to generate kubernetes objects from the file.
I'm sure there is a go package that can do this.

**Comment by PratikDey** [comment]
So, the implementation is going to be the same as the helm implementation?

**Comment by PratikDey** [comment]
> Well, not the same but very similar. I think.

Ok, I'll start working on this issue

**Comment by PratikDey** [comment]
Hi @dwertent , do I need to make the Kustomize chart file in the cautils folder before writing the code for the pkg/resourcehandler/filesloader file?
Sorry if this is a silly question.

**Comment by suhasgumma** [comment]
Hi @PratikDey, Can I work on this issue?

**Comment by PratikDey** [comment]
> Hi @PratikDey, Can I work on this issue?

Yeah sure, we can collaborate and work together if that's not a problem. How about you dm me on discord and we can discuss the next steps
Discord username is-- localhost#8022

**Comment by deepuyadav004** [comment]
> > Hi @PratikDey, Can I work on this issue?
> 
> Yeah sure, we can collaborate and work together if that's not a problem. How about you dm me on discord and we can discuss the next steps Discord username is-- localhost#8022

Hello @PratikDey can I also join you. I think we all three can collaborate together and make our work more productive.

**Comment by PratikDey** [comment]
@deepuyadav004 sure

**Comment by itsCheithanya** [comment]
Hey even I would like work alongside

**Comment by deepuyadav004** [comment]
> localhost#8022



> @deepuyadav004 sure

How can i contact you

**Comment by suhasgumma** [comment]
> Hi @PratikDey, Can I work on this issue?

Sorry @PratikDey , lost your reply in the mix. I have completed the task. But, there is one more similar issue(Scanning Terraform). Would love to work on that with you.

**Comment by PratikDey** [comment]
No worries @suhasgumma , I think someone is already working on the terraform issue.
Anyways I'd love to connect with you on discord or twitter @suhasgumma and discuss about this issue.

**Comment by deepuyadav004** [comment]
> @deepuyadav004 sure

How can i contact you. Please give your discrod link or slack link
