### ISSUE TITLE
Grammar mistake in PULL_REQUEST_TEMPLATE.md file

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#725]
# Describe the bug

Grammar mistake in PULL_REQUEST_TEMPLATE.md file
``` I have commented my code, particularly in hard-to-understand areas ```
should be
``` I have commented on my code, particularly in hard-to-understand areas ```
# Environment
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168 
```

**Comment by pwnb0y** [comment]
Assign to me

**Comment by MaruthiKo** [comment]
Hi, I would like to work on this issue
