### ISSUE TITLE
Combining the Installation for the OS under One Title

### ISSUE THREAD

**Issue by krupalitrivedi** [kubescape/kubescape#726]
Hello! While going through the documentation, I was able to see the following in the ReadMe file and I have some suggestions regarding the same.

![image](https://user-images.githubusercontent.com/99717469/187248414-2a186e8d-a287-4d6e-968c-b5e7180a5320.png) 

- Instead of "Install for `platform name` ", it would look consistent and easier to read when someone is going through repository if we change it to `Installation`
- All three differently listed can be combined under one as drop-down if possible.

As a result, it would look like this:
![image](https://user-images.githubusercontent.com/99717469/187249204-42187324-c6a9-414c-96b8-bc8e919ff9f4.png)

Thank you!

**Comment by MaruthiKo** [comment]
Hi, I would like to work on this issue

**Comment by ShivamTyagi12345** [comment]
Goodluck with the feature @MaruthiKo.Lemme know if you need help at any point😄

**Comment by MaruthiKo** [comment]
> Goodluck with the feature @MaruthiKo But since you are working on multiple issues , Do you mind if i take this😄 Stating from
> 
> * [Grammar mistake in PULL_REQUEST_TEMPLATE.md file #725](https://github.com/kubescape/kubescape/issues/725)
> 
> / assign

Sorry bro, just completed this and also added a PR

**Comment by pwnb0y** [comment]
@MaruthiKo  of course bro 😃

**Comment by dwertent** [comment]
I [do not think](https://github.com/kubescape/kubescape/pull/730#issuecomment-1236315688) we should make the changes since this will limit us from using links.
