### ISSUE TITLE
build.bat file is not working.

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#735]
# Describe the bug
When I try to build from buid.bat or try to download it through too many errors and also warning is occurring

# Environment
OS: ``` Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0  ```        
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168 
```

# Steps To Reproduce
1. Go to 'kubescape directory'
2. Click on 'build.bat'
3. See an error
![build](https://user-images.githubusercontent.com/96813659/187340631-9789ab93-be90-463a-8dfb-e5c984f0988c.png)

**Comment by SD-13** [comment]
Hey @pwnb0y, Can I give it a try?

**Comment by pwnb0y** [comment]
Sorry, @SD-13 I am already working on this issue.

**Comment by SD-13** [comment]
Okay, np

**Comment by pwnb0y** [comment]
Hey, @SD-13 You can work on this issue. Good luck 👍

**Comment by deepuyadav004** [comment]
Hello @SD-13, are you working on it or do you need any kind of help than please let me know I will be happy to help you

**Comment by SD-13** [comment]
> Hello @SD-13, are you working on it or do you need any kind of help than please let me know I will be happy to help you

Thanks for asking, I am still working on it.

**Comment by SD-13** [comment]
Hey @pwnb0y, I can't see any pop-up like this, Can you please confirm.

**Comment by XDRAGON2002** [comment]
@pwnb0y the linked PR should resolve this issue as well, as it would allow users to move away from `.bat` files entirely and use `.ps1` files instead for Windows environments.
