### ISSUE TITLE
some grammar mistakes in  "kubescape/httphandler/README.md" file.

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#736]
# Describe the bug
I found some grammatical mistakes in ``` kubescape/httphandler/README.md ```  file
In place of :
```    /livez - will respond 200 is server is alive  ```
It should be:
```   /livez - will respond to 200 if the server is alive   ``` <br>
In place of :
 ``` Trigger scan and wait for scan to end  ```
It should be:
``` Trigger scan and wait for the scan to end ``` <br>
In place of :
``` query id=<string> -> request results of a specific scan ID. If empty will return latest results```
It should be:
``` query id=<string> -> request results of a specific scan ID. If empty will return the latest results   ``` <br>
In place of :
 ``` Check the scanning status - is the scanning in progress or done.   ```
It should be:
```  Check the scanning status - is the scanning in progress or done?    ```

# Environment
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168 
```

**Comment by KanishkaVerma054** [comment]
Can I work on this issue?

**Comment by pwnb0y** [comment]
Why not😊

**Comment by AmanGupta677** [comment]
I would like to work on this issue can I get started?

**Comment by KanishkaVerma054** [comment]
Hey @pwnb0y, I've updated the httphandler readme file as you've said. Can you please review my changes and merge it?

**Comment by pwnb0y** [comment]
ok sure 👍

**Comment by pwnb0y** [comment]
Hi @KanishkaVerma054  after changing this line
```  * `/livez` - will respond to 200 if the server is alive ```
you can also change and correct this line 
``` * `/readyz` - will respond 200 if server can receive requests ``` here 'the' is missing

**Comment by KanishkaVerma054** [comment]
Thanks for the the reply @pwnb0y. I'm fixing this issue right now.

**Comment by KanishkaVerma054** [comment]
Hey @pwnb0y, I've changed the issue as you've said. Can you please review my change and merge it?

**Comment by KanishkaVerma054** [comment]
hey @pwnb0y have you seen the changes I've done?

**Comment by pwnb0y** [comment]
👍

**Comment by KanishkaVerma054** [comment]
@pwnb0y can you please merge my code?

**Comment by KanishkaVerma054** [comment]
Hey, @dwertent I've updated all the changes describe in this issue. Can you please review my changes and merge it?
