### ISSUE TITLE
Adding a banner in install.sh file

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#743]
**Is your feature request related to a problem? Please describe.**
Kindly add a banner in install.sh file for better UI and attract users to be curious about our organization.

**Describe the solution you'd like**
It can be an ASCII banner that is written in echo to just print it out
![banner](https://user-images.githubusercontent.com/96813659/187512224-26136d02-9c92-409e-9e30-c97db5713036.png)

**Comment by Nabhag8848** [comment]
Hey, would love to work on it.  can you assign it.

**Comment by iamhardikat11** [comment]
I would like to work on this Issue?

**Comment by iamhardikat11** [comment]
Can you assign this to me?

**Comment by dwertent** [comment]
I dont see why we should add a banner
