### ISSUE TITLE
Improving Dockerfile

### ISSUE THREAD

**Issue by RahulSurwade08** [kubescape/kubescape#747]
We can improve Dockerfile by 

1. Adding Alpine tag for future reference of base image version
2. Removing inessential commands

**Comment by ryuusama09** [comment]
hey ! , I would like to work on this issue . Can you tell me where to start from @RahulSurwade08

**Comment by Aryan-Deshpande** [comment]
If this issue is authorised, would love to work with this one !

**Comment by RahulSurwade08** [comment]
Hey @ryuusama09 @Aryan-Deshpande Thanks for asking but I have created this issue for keeping track of the PR raised.

**Comment by dwertent** [comment]
Merged #748
