### ISSUE TITLE
Registry scanning ACR

### ISSUE THREAD

**Issue by nerodtm** [kubescape/kubescape#749]
unable to run registry scanning in ACR

**Comment by pwnb0y** [comment]
Hey, @nerodtm can you explain this issue in detailed manner?

**Comment by nerodtm** [comment]
For your reference,

[image: kubescape.PNG]

Thanks and Best regards
DTM Niroshan Tharanga

**Comment by Bezbran** [comment]
Hi @nerodtm , the ACR [isn't tested yet](https://hub.armosec.io/docs/registry-vulnerability-scan#tested-on).
I will glad to set a meeting with you to see why it's not working for you.
Please feel free to contact me: bez@armosec.io.

**Comment by Bezbran** [comment]
After defining the secret as described [in the docs](https://hub.armosec.io/docs/registry-vulnerability-scan), with regular username and password docker credentials, it worked as expected.

**Comment by nerodtm** [comment]
Hi Vicky,

When I try to scan the registry (ACR) using kubescape, it didn't work. It
appeared as scanning. But, it didn't finish.

Thanks and Best regards
DTM Niroshan Tharanga
