### ISSUE TITLE
Misconfiguration in "close-typos-issues.yaml" workflow file 

### ISSUE THREAD

**Issue by suhasgumma** [kubescape/kubescape#754]
# Describe the bug
* A job named "build" was defined in the `".github/workflows/close-typos-issues.yaml"` file but steps are not defined. This throws an invalid workflow file error.

# Expected behaviour
* `"close-typos-issues.yaml"` attempts to define a GitHub Actions workflow to close issues automatically if they are labelled "typo".

# Actual Behavior
throws an invalid workflow file error.

# Additional context
Apart from correcting the above mistake, some work is needed to be done to define the GitHub Actions workflow to close issues automatically if they are labelled "typo".

**Comment by suhasgumma** [comment]
Can I work on this?

**Comment by ryuusama09** [comment]
can I work on this issue ? @slashben

**Comment by suhasgumma** [comment]
> can I work on this issue ? @slashben

@ryuusama09  I've already solved it and raised a PR

**Comment by ryuusama09** [comment]
> > can I work on this issue ? @slashben
> 
> @ryuusama09 I've already solved it and raised a PR
oh okay
