### ISSUE TITLE
make a script to build on windows in powershell (ie: build.ps1)

### ISSUE THREAD

**Issue by pwnb0y** [kubescape/kubescape#760]
**Is your feature request related to a problem? Please describe.**
When  building it in a windows environment with build.bat, the script is not working bat scripting can not be used at large scope so I decided to build it in PowerShell script which works correctly in any windows environment

**Comment by pwnb0y** [comment]
I am very excited to work on it please assign it to me.

**Comment by craigbox** [comment]
Did you ever do anything here, @pwnb0y?

(Please see https://github.com/kubescape/kubescape/pull/101 for some past approaches.)

If not, I will test #735, and close this if it works.

**Comment by XDRAGON2002** [comment]
Hi @pwnb0y @craigbox could you elaborate a bit more on what the goal here was? 
Was it to create a script which would install the tool for a new user (there already is a install.ps1 script I believe)? 
Or to build the tool for development purposes from source (which in the docs are expected to use make for)?
Thanks!
