### ISSUE TITLE
[PR] Template Improve

### ISSUE THREAD

**Issue by legendarykamal** [kubescape/kubescape#763]
# Describe the bug

The PR template should include a line saying This PR fixes: #
But currently it says Ticket no. which will not be convenient for the new contributors and they might not link their issue no. , so we need to change. 

https://github.com/kubescape/kubescape/blob/master/.github/PULL_REQUEST_TEMPLATE.md

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is:
```

# Steps To Reproduce

# Expected behavior

# Actual Behavior
A clear and concise description of what happened. If applicable, add screenshots to help explain your problem.

# Additional context

**Comment by AmanGupta677** [comment]
I would like to work on this issue.
