### ISSUE TITLE
Backstage plugin

### ISSUE THREAD

**Issue by Bezbran** [kubescape/kubescape#784]
As DevOps, we want to allow the developers as much autonomy as we can for their workloads operations while keeping all our necessary guardrails.

[Backstage portal](https://github.com/backstage/backstage#getting-started) is one of the most powerful and common in use solutions to fulfil this requirement.
Backstage is the centralized place where developers meet the operations of the applications.

Backstage secret ingredient is their [plugins catalog](https://github.com/backstage/backstage/tree/master/plugins).
Let's see how we can make a Kubescape plugin to give this value to the DevOps people.

**Comment by itsCheithanya** [comment]
I would like to work on this issue

**Comment by MitAbhay** [comment]
I would also like to work on this issue @Bezbran

**Comment by deepuyadav004** [comment]
I would also like to work on this

**Comment by Bezbran** [comment]
Hi guys, do you have an experience in Backstage? Or experience with developing on any similar plugin platform?

**Comment by MitAbhay** [comment]
@Bezbran  No, I don't have worked on any plugin platform before, but I would like to learn stuff related to backstage.

**Comment by deepuyadav004** [comment]
> Hi guys, do you have an experience in Backstage? Or experience with developing on any similar plugin platform?

No, I don't have any experience in Backstage but I would like to work on it.

**Comment by itsCheithanya** [comment]
Neither I but we can make it work during this program

**Comment by Adidev-KGP** [comment]
I would like to work on this issue. I have developed a few frontend plugins using backstage. Would be great if you can share more details on what is expected out of this issue @Bezbran .

**Comment by majjikishore007** [comment]
hey @Bezbran could you please more details on the same

**Comment by Bezbran** [comment]
> I would like to work on this issue. I have developed a few frontend plugins using backstage. Would be great if you can share more details on what is expected out of this issue @Bezbran .

Since I see we have here @Adidev-KGP , a guy with an experience in this area, I think we can go ahead.
I think a demo of former plugins developed by @Adidev-KGP to all of us will be a good start so we can be on the same page.

The backstage plugin should act very similar to [Lens extension](https://github.com/kubescape/lens-extension).
High level requirements headlines:
- Allow user to get scan result per K8s resource / Git repository / Image.
- Allow user to get the assisted remediation for the resource.
- Allow user to get trends.
- Allow user to get list of failed controls.
- Allow users to integrate with [Kubescape operator](https://hub.armosec.io/docs/installation-of-armo-in-cluster) inside their cluster.
- Allow users to integrate with their account in [Kubescape Cloud](https://hub.armosec.io/docs/kubescape-cloud-account).

@Adidev-KGP , please contact me so we can schedule a demo, bez@armosec.io.

Thank you all of being part of it!!!
Just take into account, to contribute to such project you need the know Kubescape, K8s, TypeScript, and knowledge in Golang is very useful as well.

**Comment by deepuyadav004** [comment]
> > I would like to work on this issue. I have developed a few frontend plugins using backstage. Would be great if you can share more details on what is expected out of this issue @Bezbran .
> 
> Since I see we have here @Adidev-KGP , a guy with an experience in this area, I think we can go ahead. I think a demo of former plugins developed by @Adidev-KGP to all of us will be a good start so we can be on the same page.
> 
> The backstage plugin should act very similar to [Lens extension](https://github.com/kubescape/lens-extension). High level requirements headlines:
> 
> * Allow user to get scan result per K8s resource / Git repository / Image.
> * Allow user to get the assisted remediation for the resource.
> * Allow user to get trends.
> * Allow user to get list of failed controls.
> * Allow users to integrate with [Kubescape operator](https://hub.armosec.io/docs/installation-of-armo-in-cluster) inside their cluster.
> * Allow users to integrate with their account in [Kubescape Cloud](https://hub.armosec.io/docs/kubescape-cloud-account).
> 
> @Adidev-KGP , please contact me so we can schedule a demo, [bez@armosec.io](mailto:bez@armosec.io).
> 
> Thank you all of being part of it!!! Just take into account, to contribute to such project you need the know Kubescape, K8s, TypeScript, and knowledge in Golang is very useful as well.

Hello @Bezbran I want to learn backstage plugin and give it a try with you folks. So, may is also be a part of your team.

**Comment by Bezbran** [comment]
I am trying to build some team to work on this issue, so please write down what you have experience in.
@deepuyadav004

**Comment by suhasgumma** [comment]
> I am trying to build some team to work on this issue, so please write down what you have experience in. @deepuyadav004

Hi @Bezbran, I have intermediate knowledge in K8s, Golang, AWS & Docker. I've been working on the Kubescape codebase for the past few days.

I Would love to be in the team working on this issue. Thank you.

**Comment by TarangVerma** [comment]
hey @Bezbran I think we can start with adding backstage-kubernetes plugin to kubescape in order to check health & monitor all the services. Does it sound good to you.

**Comment by deepuyadav004** [comment]
> I am trying to build some team to work on this issue, so please write down what you have experience in. @deepuyadav004

I have worked on following technologies
Languages :- C++, Golang, Python, JavaScript, HTML, CSS
front-end frameworks :- React.js
backend :- node.js, express.js, Rest APIs
Database :- MySql, mongodb
tools and other technologies :- Docker, Kubernetes, linux, git, github, windows

**Comment by TarangVerma** [comment]
> I am trying to build some team to work on this issue, so please write down what you have experience in. @deepuyadav004

I have been contributing to kubescape since couple of weeks now and i know its codebase quite well now so i would like to work on this.
I have experience in Docker, K8, Helm, yaml, Go, JavaScript.

**Comment by Bezbran** [comment]
> hey @Bezbran I think we can start with adding backstage-kubernetes plugin to kubescape in order to check health & monitor all the services. Does it sound good to you.

What requirements of the high level requirements [above](https://github.com/kubescape/kubescape/issues/784#issuecomment-1242894182) this health check is for?

**Comment by majjikishore007** [comment]
Hey @Bezbran  I would like to be part of this

**Comment by TarangVerma** [comment]
> > hey @Bezbran I think we can start with adding backstage-kubernetes plugin to kubescape in order to check health & monitor all the services. Does it sound good to you.
> 
> What requirements of the high level requirements [above](https://github.com/kubescape/kubescape/issues/784#issuecomment-1242894182) this health check is for?



> > hey @Bezbran I think we can start with adding backstage-kubernetes plugin to kubescape in order to check health & monitor all the services. Does it sound good to you.
> 
> What requirements of the high level requirements [above](https://github.com/kubescape/kubescape/issues/784#issuecomment-1242894182) this health check is for?

 If i am not getting it wrong we are trying to create a kubescape plugin which we will add to backstage so that users can use the kubescape plugin from there directly though kubescape extension right?

**Comment by TarangVerma** [comment]
> > hey @Bezbran I think we can start with adding backstage-kubernetes plugin to kubescape in order to check health & monitor all the services. Does it sound good to you.
> 
> What requirements of the high level requirements [above](https://github.com/kubescape/kubescape/issues/784#issuecomment-1242894182) this health check is for?

Iif i am not getting it wrong we are trying to create a kubescape plugin which we will add to backstage so that users can use the kubescape plugin from there directly though kubescape extension...

**Comment by Ciggzy1312** [comment]
Hey @Bezbran if you are forming a team to work on this I would love to be a part of it also
I have an idea about backstage and am also working on the vs-code extension of kubescape so I am very familiar with typescript which we will need and the rest of the stack required.
I have also been a contributor to keptn which is a project under CNCF and they also are working on a backstage plugin implementation so I have a good idea about how things work

So do let me know how are we planning to proceed. Thank you

**Comment by deepuyadav004** [comment]
Hey @Bezbran have you made your team or have you started/done your work on this issue. I didn't get any update about this issue.  May I know will you form a team in future or not ??
