### ISSUE TITLE
how to scan helm chart locally offline

### ISSUE THREAD

**Issue by jainpratik163** [kubescape/kubescape#787]
# Describe the bug
i am running this command `kubescape scan <helm chart directory>` help menu is opening and when I run below command 

`kubescape scan framework nsa <helm chart directory>`
I am getting this 
**ARMO security scanner starting
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
empty list of workloads - no workloads found**

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v1.0.131
```

**Comment by shivanii1702** [comment]
@jainpratik163 I want to work on this issue, can you elaborate the issue

**Comment by jainpratik163** [comment]
I want to scan the helm chart and run these steps as part of CI.

**Comment by dwertent** [comment]
Hi @jainpratik163 you are running an old version.
Please update kubescape to the latest version :)

**Comment by jainpratik163** [comment]
thanks, @dwertent  with the latest version I am able to run the command.
The report which the command is created is very difficult to understand can we also update the report?
i know we can run the command with -v but if we can more info without -v would be great.

**Comment by dwertent** [comment]
@jainpratik163 
We do not want to print too much information to the terminal because we do not want to overwhelm the user. 
That being said, feel free to share a proposal.
