### ISSUE TITLE
failed to initialize a new kubernetes client, reason: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"% when running scan

### ISSUE THREAD

**Issue by idan-codefresh** [kubescape/kubescape#788]
# Describe the bug
when trying to run kubescape scan, I'm getting this error

`failed to initialize a new kubernetes client, reason: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"%`

my kubectl and cluster versions
 seem fine 
`Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
idanarbel@Idans-MacBook-Pro ~ %`
# Environment
AWS k8s 1.21
Version: the version that Kubescape reports when you run `kubescape version`
v2.0.170
Your current version is:
```

# Steps To Reproduce
Steps to reproduce the behavior:
run the scan command

# Expected behavior
A clear and concise description of what you expected to happen.

# Actual Behavior
A clear and concise description of what happened. If applicable, add screenshots to help explain your problem.

# Additional context
Add any other context about the problem here.

**Comment by dwertent** [comment]
Hi @idan-codefresh This is a [known issue](https://github.com/aws/aws-cli/issues/6920) with the AWS-CLI client since they broke backward compatibility.
Please update your `AWS-CLI` version to latest and update the `kubeconfig` file. [Here there is an example](https://github.com/aws/aws-cli/issues/6920#issuecomment-1171113816).

**Comment by dwertent** [comment]
As explained, this is an issue with the AWS-CLI and not with Kubescape.
