### ISSUE TITLE
panic: runtime error: index out of range [3] with length 3

### ISSUE THREAD

**Issue by dazzag24** [kubescape/kubescape#789]
Using the version installed today using brew on a MAC M1 (seems that brew version is not the latest)

```
kubescape scan .
[info] ARMO security scanner starting
[warning] current version 'v2.0.166' is not updated to the latest release: 'v2.0.170'
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
github.com/armosec/go-git-url/gitlabparser/v1.(*GitLabURL).Parse(0x140003fc1c0, {0x1400005bc20?, 0x1046a5ce0?})
        github.com/armosec/go-git-url@v0.0.15/gitlabparser/v1/parser.go:89 +0x33c
github.com/armosec/go-git-url/gitlabparser/v1.NewGitLabParserWithURL({0x1400005bc20, 0x3e})
        github.com/armosec/go-git-url@v0.0.15/gitlabparser/v1/parser.go:28 +0x98
github.com/armosec/go-git-url.NewGitURL({0x1400005bc20, 0x3e})
        github.com/armosec/go-git-url@v0.0.15/init.go:28 +0x1b0
github.com/armosec/kubescape/v2/core/cautils.metadataGitLocal({0x16d837657?, 0x3?})
        github.com/armosec/kubescape/v2/core/cautils/scaninfo.go:405 +0xe8
github.com/armosec/kubescape/v2/core/cautils.setContextMetadata(0x14000c3d3f0, {0x16d837657, 0x3})
        github.com/armosec/kubescape/v2/core/cautils/scaninfo.go:358 +0x364
github.com/armosec/kubescape/v2/core/cautils.scanInfoToScanMetadata(0x140002fc4e0)
        github.com/armosec/kubescape/v2/core/cautils/scaninfo.go:289 +0x328
github.com/armosec/kubescape/v2/core/cautils.NewOPASessionObj({0x0, 0x0, 0x0}, 0x0, 0x140002fc4e0)
        github.com/armosec/kubescape/v2/core/cautils/datastructures.go:43 +0x5c
github.com/armosec/kubescape/v2/core/pkg/policyhandler.(*PolicyHandler).CollectResources(0x14000b9b808, {0x14000611500, 0x5, 0x8}, 0x140002fc4e0)
        github.com/armosec/kubescape/v2/core/pkg/policyhandler/handlenotification.go:26 +0x40
github.com/armosec/kubescape/v2/core/core.(*Kubescape).Scan(0x103f05b60?, 0x140002fc4e0)
        github.com/armosec/kubescape/v2/core/core/scan.go:142 +0x618
github.com/armosec/kubescape/v2/cmd/scan.getFrameworkCmd.func2(0x1045bd120?, {0x14000427680, 0x2, 0x140006b1560?})
        github.com/armosec/kubescape/v2/cmd/scan/framework.go:102 +0x3ac
github.com/armosec/kubescape/v2/cmd/scan.GetScanCommand.func1(0x140000ff680?, {0x140006b1560, 0x1, 0x1?})
        github.com/armosec/kubescape/v2/cmd/scan/scan.go:45 +0x180
github.com/spf13/cobra.(*Command).ValidateArgs(...)
        github.com/spf13/cobra@v1.5.0/command.go:1018
github.com/spf13/cobra.(*Command).execute(0x140000ff680?, {0x140006b1540?, 0x1?, 0x1?})
        github.com/spf13/cobra@v1.5.0/command.go:841 +0x3a4
github.com/spf13/cobra.(*Command).ExecuteC(0x140000ff400)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/armosec/kubescape/v2/cmd.Execute()
        github.com/armosec/kubescape/v2/cmd/root.go:84 +0x34
main.main()
        github.com/armosec/kubescape/v2/main.go:9 +0x1c
```

**Comment by dazzag24** [comment]
This also happens with the latest v2.0.170 release as well.

**Comment by dazzag24** [comment]
```
origin	git@gitlab.com:foobar/machine-learning/cluster-manifests.git (fetch)
origin	git@gitlab.com:foobar/machine-learning/cluster-manifests.git (push)
```

**Comment by operon-io** [comment]
This bug occurs on GitLab with versions v2.0.165-172. Version v2.0.164 seems to work, so until patch is ready will resort to use that.

**Comment by dwertent** [comment]
@dazzag24 Have you done here any progress?

**Comment by dazzag24** [comment]
> @dazzag24 Have you done here any progress?

I think [Aman123lug](https://github.com/Aman123lug) volunteered to work on this.

**Comment by dwertent** [comment]
@Aman123lug Any updates?

**Comment by fredbi** [comment]
@dwertent hello. I've looked at it briefly and the offending line is: https://github.com/kubescape/go-git-url/blame/master/gitlabparser/v1/parser.go#L86

Wrapping it with a check on the "-" particular path part is enough to avoid a panic:
```go
	if splittedRepo[index] == "-" {
		index += 1 // skip "-" symbol in URL
	}
```

However, I am not really sure about the consistency of the eventual result. This parser obviously is not designed in the first place to support general URLs.

**Comment by Aman123lug** [comment]
> @Aman123lug Any updates?

I think @dazzag24 working on it

**Comment by fredbi** [comment]
Also I've detected that there are 2 versions of this go-git-url repo being used: one under the kubescape owner, one under the armosec owner: while the armosec version is still being pulled as a direct dependency, the other version is pulled indirectly...

**Comment by fredbi** [comment]
I have a small patch ready if you guys are interested. This assumes a few things. I'd need a piece of advice to be sure I am heading in the right direction.  I wouldn't want to interfere with some other people's work. Let me know if you want a PR (actually 2 since 2 repos are concerned).

1. kubescape/go-git-url: added the simple check above. In the case of such "scp-like" git-urls, it no longer panics if the input is not exactly as expected. However, the OP-provided remote ```````````git@gitlab.com:foobar/machine-learning/cluster-manifests.git`  won't really work as expected: in this example, "foobar" is considered the owner, "machine learning" the repo and "cluster..." the branch. 
With a correct origin like so  "git@gitlab.com:gitlab-tests/sample-project.git", the owner & repo are inferred correctly.
I am not sure that this is acceptable behavior.
Parsed "pseudo-URL" results in :
``` 
=== RUN   TestFred
    fred_test.go:26: remote: git@gitlab.com:foobar/gitlab-tests/sample-project.git
(*v1.GitLabURL)(0xc00030a380)({
 host: (string) (len=10) "gitlab.com",
 owner: (string) (len=6) "foobar",
 repo: (string) (len=12) "gitlab-tests",
 project: (string) "",
 branch: (string) (len=18) "sample-project.git",
 path: (string) "",
 token: (string) ""
})
--- PASS: TestFred (0.00s)
PASS
```
3. kubescape/kubescape: replaced deps on github.com/armosec/go-git-url by github.com/kubescape/go-git-url (both repos are the same right now).  I assume this is the right repo to look into. Will need to upgrade dep on go-git-url.

**Comment by fredbi** [comment]
@dwertent  here is a proposal for a fix. @dazzag24, @Aman123lug  feel free to discard this if you've already started something better. For sure, the fix is not perfect: just assuring that wrong/unexpected input doesn't panic the CLI.
