### ISSUE TITLE
Request to add a CodeSee.io Codebase Map

### ISSUE THREAD

**Issue by RayAsh37** [kubescape/kubescape#798]
Hey @dwertent, this is a suggestion. How about adding a [CodeSee](https://www.codesee.io/) map for your codebase. It becomes way more accessible for new contributors to work and contribute to the repo.

I have an auto-generated example [here](https://app.codesee.io/maps/public/ea279b60-31d6-11ed-ae63-7d65ece0c3cb) that I was able to produce from my Kubescape fork. Just remember to switch it from **_View Mode_** to **_Playground Mode_** to view the entire file structure.

I believe this will also be helpful for future Onboarding purposes too.

Btw, I love what you guys have made, and have been actively trying to learn the Codebase. And hopefully, make a meaningful contribution.

**Comment by deepuyadav004** [comment]
great idea @RayAsh37 It will be helpful for many of folks

**Comment by RayAsh37** [comment]
I would have loved to do it myself but I believe it would be better if it is set up by the Maintainer. Because it can be tricky when it comes CodeSee account ownership.

**Comment by RayAsh37** [comment]
Hi @dwertent I have added a CodeSee Clickable to the documentation (README.md) at the PR #801 
Please review

**Comment by dwertent** [comment]
We decided not to add codeSee since we do not want to constantly maintain the link.
