### ISSUE TITLE
Fix the typo as it is confusing

### ISSUE THREAD

**Issue by RayAsh37** [kubescape/kubescape#809]
The example description for the command
`kubescape download --help`
outputs examples but one of them has an extra 'download' word. It is confusing fo a beginner and might not understand it.

##Marked in RED
![downloadGo typo](https://user-images.githubusercontent.com/70441807/190165299-3df8c920-5a76-48da-8227-341f4febe1ab.png)
This is the console output

**Comment by RayAsh37** [comment]
I have opened a PR for this, @dwertent please review

**Comment by Susmita-Dey** [comment]
@RayAsh37 You must have waited to get assigned first before creating a PR. This is a valid way of contributing to a n open source project.
