### ISSUE TITLE
[DOCS] Install Using Go link in README not working - no steps present

### ISSUE THREAD

**Issue by Susmita-Dey** [kubescape/kubescape#811]
# Describe the bug
![image](https://user-images.githubusercontent.com/79099734/190181622-3943e916-ebe5-4f11-9b55-0ac7cc29e6e1.png)
When I'm clicking on this link, it's not working.

# Steps To Reproduce
1. Go to 'README.md' file
2. Scroll down to 'Install' section
3. Click on 'Install Using Go'

# Expected behavior
On clicking the link, it would work and take me to the section from where I can get the command to install Kubescape using **Go**

# Actual Behavior
A clear and concise description of what happened. If applicable, add screenshots to help explain your problem.

# Additional context
The commands are not there in the `README.md` file.

**Comment by Susmita-Dey** [comment]
I'd like to work on this issue. Kindly assign me.

**Comment by kunjgit** [comment]
@Susmita-Dey let me know if you are working on it because i  can fix this.

**Comment by Susmita-Dey** [comment]
@kunjgit I'll be working on it after getting assigned

**Comment by kunjgit** [comment]
@Susmita-Dey thanks for letting me aware.
