### ISSUE TITLE
[FEATURE] Make numbers dynamic

### ISSUE THREAD

**Issue by Susmita-Dey** [kubescape/kubescape#812]
**Is your feature request related to a problem? Please describe.**</br>
 > No, it's not related to a problem but I just want to make the numbers dynamic.

**Describe the solution you'd like.**</br>
 > I just want to make the numbers dynamic. using javascript if possible so that when the page loads, the numbers will act as counters.

**Describe alternatives you've considered.**</br>
 > No alternatives currently in my mind

**Additional context.**</br>
![image](https://user-images.githubusercontent.com/79099734/190182826-8c2c6e3b-b57c-4ed8-8ba9-18f57116d56e.png)
I'm talking about these static numbers.

**Comment by dipankardas011** [comment]
@Susmita-Dey I can give it a try
Just for now found that using GitHub API we can get the stars, forks counters
if the just have to see the source code
![image](https://user-images.githubusercontent.com/65275144/190340389-e5c0a1ae-b37a-401e-a3d3-a3dc7290a275.png)

**Comment by RayAsh37** [comment]
@Susmita-Dey @dipankardas011 I believe the website is not Open Source

**Comment by Susmita-Dey** [comment]
@RayAsh37 I don't think so. Although I need to checkout.

**Comment by rahul3002** [comment]
i would like to contribute to this issue

**Comment by dwertent** [comment]
This is from the armosec website.
Unfortunately it is not open-source
