### ISSUE TITLE
unable to scroll through the reviews section

### ISSUE THREAD

**Issue by TarangVerma** [kubescape/kubescape#818]
# Describe the bug
I was unable to scroll and read all the feedback given by people in the review section.
This is the screenshot of the problem.
![Screenshot (15)](https://user-images.githubusercontent.com/90996971/190462581-b62c96c2-4e6f-4740-bb8e-22b9cdc1aae8.png)

# Environment
OS: windows 10 home

# Steps To Reproduce
1. Go to the kubescape official website.
2. Scroll down to the review section.
3. Try to read the comments of the people by scrolling

# Expected behavior
User should see and be able to read all the reviews by companies and people.

**Comment by Gnana-Athityan** [comment]
can i work on this , im new to this . Looking forward to contribute

**Comment by rahul3002** [comment]
i would to contribute to this issue I have an experience on working on it

**Comment by anubhav06** [comment]
@TarangVerma It works for me. I think it is an issue with your browser.
