### ISSUE TITLE
Previous and Next buttons are not expected here

### ISSUE THREAD

**Issue by TarangVerma** [kubescape/kubescape#819]
# Describe the bug
I don't think these buttons are required here and if required then they are not in proper place to be viewed by the user.
Here is the Screenshot of the following:

![Screenshot (16)](https://user-images.githubusercontent.com/90996971/190466875-0e35406c-0f34-4ec0-9749-89180cad6acc.png)

# Environment
OS: Windows 10 home
Your current version is:
```

# Steps To Reproduce
Steps to reproduce the behavior:
1. Go to kubescape official website.
2. Scroll down to feedback and review section
3. See error

# Expected behavior
Those buttons should be in proper place and more visible so that users can access it when required.

**Comment by RayAsh37** [comment]
@TarangVerma KubesScape website is not open source.

**Comment by dwertent** [comment]
The website is not yet opened source :(
