### ISSUE TITLE
Adding kubectl plugin

### ISSUE THREAD

**Issue by gaurangkudale** [kubescape/kubescape#841]
I have already started working on this feature and if anyone wants to add functionalities they can ping here

**Comment by Meyazhagan** [comment]
@gaurangkudale  Shall I also join with you !

**Comment by gaurangkudale** [comment]
@Meyazhagan Yeah sure!

**Comment by Manish4044** [comment]
@gaurangkudale I also want to work with you on this feature

**Comment by Cvr421** [comment]
@gaurangkudale Hello can I also work with you guys

**Comment by gaurangkudale** [comment]
Hi @dwertent,
I am working on the kubectl plugin and I have questions listed below:

1. For which sub-commands in kubectl should I add the support? Can you please provide suggestions?
2. Which sub-command functionalities should I add? Can you please mention any specific requirements of sub-command 
i.e any specific sub-command which will improve the kubescape or you are planning to add (Any Suggestions would help me)?

**Comment by Aman123lug** [comment]
@gaurangkudale can i join with you guys please

**Comment by Aman123lug** [comment]
@gaurangkudale shall I join to you bro please

**Comment by Manda-supraja26** [comment]
@gaurangkudale  i'm intrested in this topic . i would to know what kind  of plugins you want add to kubectl..?

**Comment by craigbox** [comment]
@gaurangkudale Hi Gaurang; do you have a draft PR you can share?

**Comment by dwertent** [comment]
There is a plugin :)
