### ISSUE TITLE
[BUG] Excluding Namespaces

### ISSUE THREAD

**Issue by anubhav06** [kubescape/kubescape#847]
# Describe the bug
When a user runs a Kubescape scan with `--exclude-namespaces "kube-system"` flag, that namespace is not excluded.

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.168
```

# Steps To Reproduce
1. Run `kubescape scan --exclude-namespaces "kube-system" -v`
2. Observe the results

# Expected behavior
The scan results should not include the results from `kube-system` namespace

# Actual Behavior
We see the results from the `kube-system` namespace, although we have specified to exclude it.  

![0](https://user-images.githubusercontent.com/43821031/191981731-dd76f9d4-77a0-47fb-9540-6ba1f5dcf8be.png)

**Comment by anubhav06** [comment]
This issue is inter-linked with #608 , and I'm working on the solution

**Comment by Meyazhagan** [comment]
@anubhav06 I saw it was already fixed #107

**Comment by anubhav06** [comment]
I see there's already an issue created for this. So, let me close this one 👍
