### ISSUE TITLE
go build fails for kubevuln component

### ISSUE THREAD

**Issue by maheshsk28211** [kubescape/kubescape#851]
# Describe the bug
While building kubevuln project, go build failed
# github.com/anchore/grype/grype/pkg
../../go/pkg/mod/github.com/anchore/grype@v0.35.0/grype/pkg/package.go:94:11: undefined: pkg.RpmdbMetadataType
../../go/pkg/mod/github.com/anchore/grype@v0.35.0/grype/pkg/package.go:127:34: undefined: pkg.RpmdbMetadata

# Environment
OS: Ubuntu 22.04 LTS
Version: Kubescape latest
```
Your current version is:
```

# Steps To Reproduce
1. git clone https://github.com/kubescape/kubevuln.git
2. execute go mod tidy, followed by go build to execute in local machine
3. saw error
# github.com/anchore/grype/grype/pkg
../../go/pkg/mod/github.com/anchore/grype@v0.35.0/grype/pkg/package.go:94:11: undefined: pkg.RpmdbMetadataType
../../go/pkg/mod/github.com/anchore/grype@v0.35.0/grype/pkg/package.go:127:34: undefined: pkg.RpmdbMetadata

# Expected behavior
A code should compile without error

# Actual Behavior
Error in grype package

# Additional context
correcting go.mod with latest version of grype resolved this issue
i.e. 
require (
	github.com/anchore/grype v0.50.0
        ..
)

**Comment by maheshsk28211** [comment]
Assign issue to me to fix this.

**Comment by Meyazhagan** [comment]
@maheshsk28211 try `go mod tidy`

**Comment by maheshsk28211** [comment]
go mod tidy didn't work as mod file has v0.35.0, that pull v0.35.0, that is mismatch with source.

**Comment by dwertent** [comment]
1. This issue should be opened in the Kubevuln repo
2. You should follow the README for [building locally](https://github.com/kubescape/kubevuln#build-kubevuln)
