### ISSUE TITLE
Request to add CLI option to pass in kubernetes impersonation

### ISSUE THREAD

**Issue by rajeeshckr** [kubescape/kubescape#852]
**Is your feature request related to a problem? Please describe.**</br>
 > For `kubescape scan` to work from my local machine, I wanted impersonation flags `--as` and `--as-groups` to be passed in to the CLI. Looks like it is not supported. Hence, it is not possible to run tool from my machine.

**Describe the solution you'd like.**</br>
 > Add  `--as` and `--as-groups` flags to the CLI. And pass that option to the kubernetes go client.

**Comment by dwertent** [comment]
Hi @rajeeshckr , can you please elaborate? Does Kubectl connect to your cluster but Kubescape does not? How will the flag help?

**Comment by dwertent** [comment]
I see, thank you for suggesting this. 
Unfortunately, we won't add the flags since it might be overwhelming.
