### ISSUE TITLE
--cluster-name flag does not accept "-" character

### ISSUE THREAD

**Issue by biacharj** [kubescape/kubescape#861]
# --cluster-name flag does not accept "-" character, I did not test it with any other character, because normally one would use the "-" character

```
+ kubescape scan framework nsa --verbose --cluster-name=my-cluster1-1-0
{"level":"info","ts":"2022-10-04T15:39:21Z","msg":"Kubescape scanner starting"}
{"level":"fatal","ts":"2022-10-04T15:39:21Z","msg":"custom cluster name cannot contain special characters"}
```

# Environment
OS:  Ubuntu 22.04 LTS

Your current version is:
v2.0.172

# Steps To Reproduce
1. Run this
kubescape scan framework nsa --verbose --cluster-name=my-cluster1-1-0

# Expected behavior
Scan should run

# Actual Behavior
Scan does not run

# Additional context

**Comment by anubhav06** [comment]
The issue regarding [adding a cluster-name feature](https://github.com/kubescape/kubescape/issues/613#issue-1346588073) said that special characters should not be allowed.

```
The cluster name should:

NOT include special characters
contain less than 256 characters
```

I can go ahead and make "-" an exception, if it's required.
Kindly let me know about it :)

**Comment by biacharj** [comment]
I think it definitely makes sense to have the "-" character included. Differentiation of stack becomes difficult without this. Let's proceed please.
