### ISSUE TITLE
YAML files syntax and security level checking

### ISSUE THREAD

**Issue by deepuyadav004** [kubescape/kubescape#864]
**Is your feature request related to a problem? Please describe.**</br>
 > Currently kubescape checks the security level of YAML files. Developer write whole YAML file and than check its security level. If YAML file is too large than it may become hectic for users to go through whole YAML files and make it secure.

**Describe the solution you'd like.**</br>
 > If we kubescape provide a code writing space where user can write their YAML file and with correct syntax  ( in case of wrong syntax user will see error message same as other code editiors shows ) and he can check security level at each step. This feature may helpful for many developers.

**Additional context.**</br>
 > for this work I found a go package github.com/goccy/go-yaml. This go package may help us to implement this feature we only need to add a code writing space

**Comment by XDRAGON2002** [comment]
@dwertent @yossi77 was this feature implemented regarding a code writing space? Or is providing like a VSC or Lens extension enough for this?
