### ISSUE TITLE
Jenkins HTML report shows garbled data after consuming Kubescape generated HTML file

### ISSUE THREAD

**Issue by biacharj** [kubescape/kubescape#865]
# Describe the bug
My Setup
Run Kubescape on jenkins and view the HTML report  by using 
`kubescape scan --format html --output report.html'

# Environment
OS: Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.172
```

# Steps To Reproduce
1. Go to `Jenkins`
2. Create `Job`
3. Scroll down to 'Pipeline' and select `Pipeline script`
4. Use the below stage

`publishHTML(
        [
            allowMissing: false, 
            alwaysLinkToLastBuild: false, 
            keepAll: true, 
            reportDir: '.', 
            reportFiles: 'report.html', 
            reportName: 'Report'
        ]
    )`

# Expected behavior
HTML report in Jenkins should not show garbled data

# Actual Behavior
HTML report shows unformatted data

# Additional context

**Comment by biacharj** [comment]
@dwertent

**Comment by dwertent** [comment]
@biacharj Can you please elaborate? How was Kubescape executed in the pipeline?

**Comment by biacharj** [comment]
switch to the context(cluster) and run ***kubescape scan --format html --output report.html'"****

@dwertent

**Comment by biacharj** [comment]
@Moshe-Rappaport-CA  Thanks for your time and looking into this. appreciate it. All good now!
