### ISSUE TITLE
[feature] Adding github actions to improve the contributor experience.

### ISSUE THREAD

**Issue by harshitasao** [kubescape/kubescape#867]
**Is your feature request related to a problem? Please describe.**</br>
 This is a feature request to enhance the contributor experience using github actions.
1. Through comments in issues and PRs:
    assign, unassign, close, open, retitle, hold, labels of priority, kind, area, etc.
2. lgtm and automatic PR merging.

_**If this is something you would like to include, I would be happy to work on it.**_

**Comment by dwertent** [comment]
@harshitasao Can you please elaborate? What is missing now? What do you propose we should do to approve the experience?

**Comment by dwertent** [comment]
Closing because we did not receive a response here
