### ISSUE TITLE
Use host-scanner deployment from an external source

### ISSUE THREAD

**Issue by shm12** [kubescape/kubescape#879]
**Is your feature request related to a problem? Please describe.**</br>
 > No. It's an improvement

**Describe the solution you'd like.**</br>
 > KS will use an external source for the host scanner deployment. I suggest the [host scanner repository](https://github.com/kubescape/host-scanner). This way we:
> - Can define a host-scanner image version (in the external source) to improve stability.
> - Don't need to update the deployment file for every host-scanner version update.
> Related discussion: https://github.com/kubescape/kubescape/pull/877#discussion_r1002930409

**Describe alternatives you've considered.**</br>
 > The current way is a good alternative but it has some downsides as I described.

**Comment by Bezbran** [comment]
Not sure about this one.
Host sensor isn't differ than any other external package. 
Just like any other package which requires rebuilding for each version upgrade - so the host sensor.

**Comment by craigbox** [comment]
Sounds like there's no action here, so closing this issue.  Please re-open if it's still relevant.
