### ISSUE TITLE
Kubescape Cloud: Can't select some Controls for filtering

### ISSUE THREAD

**Issue by suhasgumma** [kubescape/kubescape#889]
# Describe the bug
In the Kubescape Cloud, we can select only from the first 30 controls to filter.

![Filter Issue](https://github.com/suhasgumma/ImagesForGitHub/blob/master/filter%20issue.png?raw=true)

In the above scenario, we can't select C-0050 and many controls after that. In fact, this happens with all attributes whose values are more than 30. It happens with Control ID, Control Name, Resource Name, Namespace and Failed controls. 

# Steps To Reproduce

1. Scan the Cluster or Repository with more than 30 controls and go to Kubescape Cloud.
2. Observe if you can select every control, failed control, namespace for filtering.

# Expected behaviour
User should be able to select any control or set of controls to filter.

# Actual Behavior
User has a choice of selecting only from the first 30 controls.

**Comment by dwertent** [comment]
@amirmalka Is this because of the pagination?

**Comment by amirmalka** [comment]
@dwertent I wasn't aware of such limitation although it doesn't look like a bug:
https://github.com/armosec/cadashboardbe/blob/40a36d61112de479ad24fd930dc0722eebdb5613/httphandlerv2/httphandler.go#L29

I think @Bezbran would know better

**Comment by Bezbran** [comment]
Yes, this is not a bug, just we are showing only 30 entries in filters list.
@suhasgumma We are about to change the Kubescape Cloud filters look and feel, so this issue will be resolved
