### ISSUE TITLE
kubescape RBAC scan fails consistently on kind cluster

### ISSUE THREAD

**Issue by olcuhu** [kubescape/kubescape#895]
# Describe the bug
kubescape RBAC scan fails consistently on kind cluster, leading to a fatal error when running the `kubescape submit rbac` command and a blank canvas in the RBAC visualisation page in the portal.

# Environment
OS: Ubuntu 22.04 LTS
Version: v2.0.174

# Steps To Reproduce
1. Install kubescape locally (and in cluster)
2. Run `kubescape submit rbac --account XXXXX` or `kubescape scan --account XXXXX`
3. See error
```
[fatal] <nil>
failed to LIST resources, reason: the server could not find the requested resource
```

# Expected behavior
The RBAC scan succeeds and RBAC visualisation is visible in the kubescape SaaS portal.

# Actual Behavior
RBAC scan fails and the RBAC visualisation in the portal shows a white canvas, with the API request returning a 404 error.

# Additional context
I was testing kubescape out in a locally running `kind` cluster when I noticed this issue, all other kubescape functionality succeeded as expected.

**Comment by matthyx** [comment]
Hi @olcuhu thanks for the bug report.
I think this is because your kind cluster is of version 1.25 for which cronjobs have moved from v1beta1 to v1 group, causing the resource not found error.
I'll check how to solve this.

In the meantime you can use a 1.24 cluster with:
`kind create cluster --image=kindest/node:v1.24.6`

**Comment by matthyx** [comment]
@dwertent I think you need to bump to 1.25 here:
https://github.com/kubescape/k8s-interface/blob/master/go.mod#L20-L22

**Comment by matthyx** [comment]
> @matthyx I have no problem with bumping the k8s version, but it is hard to believe that this is the issue.

It is the issue, it fails to get `batch/v1beta1/cronjobs` because they no longer exist there in 1.25

**Comment by dwertent** [comment]
But the issue is opened on the RBAC, this is not related to the `batch/v1beta1/cronjobs` API

**Comment by matthyx** [comment]
I took the debugger, and after getting roles and bindings, kubescape gets all objects to see how they map.

**Comment by dwertent** [comment]
As it is now, Kubescape loads the kube APIs  from a [pre-defined mock](https://github.com/kubescape/k8s-interface/blob/master/k8sinterface/k8sdiscovery_mock.go#L19) and not dynamically.

Also, when running the `kubescape submit rbac` Kubescape should load only the RBAC related object and not any other, definitely not CronJobs.

@matthyx  Can you please share the debug log you see?

**Comment by matthyx** [comment]
![Screenshot at 2022-11-06 15-02-50](https://user-images.githubusercontent.com/20683409/200175284-2b337b10-6180-4e4a-bcbe-dde1fa82fe9b.png)

**Comment by dwertent** [comment]
Thanks @matthyx, I'll take a look, what cluster & version are you running?   

In any event, this does not seem related to the original issue because @olcuhu mentioned the issue only occurs with RBAC-related objects.

**Comment by matthyx** [comment]
Kind cluster 1.25.2 same as used in this issue.
