### ISSUE TITLE
DOCS link provided not working for failed CIS controls 

### ISSUE THREAD

**Issue by suhasgumma** [kubescape/kubescape#904]
# Describe the bug
The DOCS link provided after scanning is not working for CIS controls. 

# Steps To Reproduce
1. Scan Resources/Cluster with verbose flag
2. Click on the DOCS link provided for failed CIS controls

# Expected behavior
Should take user to the documentation page of CIS control.

# Actual Behavior
404 page not found. 

![Error Opening](https://github.com/suhasgumma/ImagesForGitHub/blob/master/cis%20doc%20link.png?raw=true)

# Reason:
* For cis-5.7.3 control, the link provided is `https://hub.armosec.io/docs/cis-5.7.3`. But the actual address is `https://hub.armosec.io/docs/cis-573`. This is the case with other CIS controls too.

**Comment by dwertent** [comment]
Hi, Thank you for reporting.

@YiscahLevySilas1 What is the link convention for the CIS controls?
We need to update the output. This issue might occur in the Kubescape cloud as well.

@yuleib

**Comment by YiscahLevySilas1** [comment]
Hi, thanks for bringing to our attention. 
We're currently changing the URL convention and will fix them both in Kubescape CLI and cloud.

**Comment by YiscahLevySilas1** [comment]
solved by [PR #909](https://github.com/kubescape/kubescape/pull/909)
