### ISSUE TITLE
Docker image for kubescape

### ISSUE THREAD

**Issue by yairyairyair** [kubescape/kubescape#921]
**Is your feature request related to a problem? Please describe.**</br>
 > Yes, wanted to run via docker and not install on my machine

**Describe the solution you'd like.**</br>
 > A way to run kubescape via docker

**Describe alternatives you've considered.**</br>
 > Built a docker image of ubuntu and installe kubescape there

**Additional context.**</br>
 > null

**Comment by yairyairyair** [comment]
it is for pr #926

**Comment by dwertent** [comment]
As I explained [here](https://github.com/kubescape/kubescape/pull/923#issuecomment-1315648513), Kubescape has an official docker image.
