### ISSUE TITLE
The Cluster delete option doesn’t work

### ISSUE THREAD

**Issue by ecarbonell-technisys** [kubescape/kubescape#936]
# Describe the bug
The Cluster Delete option doesn't work on [https://cloud.armosec.io/settings/assets/clusters](https://cloud.armosec.io/settings/assets/clusters)

# Environment
```
OS: Mac OS Ventura Version 13.0 (22A380)
Kubescape: v2.0.176
```

# Steps To Reproduce
1. Go to '[https://cloud.armosec.io/settings/assets/clusters](https://cloud.armosec.io/settings/assets/clusters)'
2. Click on 'delete'
3. Confirm action 'delete'
4. Nothing happened 

# Expected behavior
Cluster deletion

# Actual Behavior
Nothing happened

# Additional context
The code inspection
<img width="392" alt="Screenshot 2022-11-22 at 7 50 51 PM" src="https://user-images.githubusercontent.com/89481127/203438316-cca9043d-7510-48e0-bd3e-3b1e50931274.png">
 show an HTTP error code: 400

**Comment by ecarbonell-technisys** [comment]
After some minutes, the cluster was deleted from my account.

**Comment by dwertent** [comment]
@yossi77 Maybe we should add an indicator for deleted clusters.

**Comment by dwertent** [comment]
We have fixed this in the ARMO Portal.
