### ISSUE TITLE
HTTP Handler Support offline scanning

### ISSUE THREAD

**Issue by testwill** [kubescape/kubescape#937]
{"level":"warn","ts":"2022-11-23T09:03:27Z","msg":"failed to get policies from github release, loading policies from cache","error":"error getting: ControlID_RuleName from: 'https://github.com/kubescape/regolibrary/releases/latest/download' ,error: Get \"https://github.com/kubescape/regolibrary/releases/latest/download/ControlID_RuleName\": unexpected EOF"}
{"level":"info","ts":"2022-11-23T09:03:27Z","msg":"Downloading/Loading policy definitions"}
{"level":"error","ts":"2022-11-23T09:03:27Z","msg":"scanning failed","ID":"922ba1b8-8077-4686-8c38-b3e45866248a","error":"failed to scan. reason: 'unknown policy kind'"}
{"level":"info","ts":"2022-11-23T09:03:28Z","msg":"requesting results","scanID":"922ba1b8-8077-4686-8c38-b3e45866248a","api":"v1/results","method":"GET"}
{"level":"info","ts":"2022-11-23T09:03:28Z","msg":"requesting results","ID":"922ba1b8-8077-4686-8c38-b3e45866248a"}
{"level":"info","ts":"2022-11-23T09:03:28Z","msg":"scan result not found","ID":"922ba1b8-8077-4686-8c38-b3e45866248a"}

**Comment by testwill** [comment]
Downloaded/Loaded policy Is it necessary to be connected to the Internet in this step?

**Comment by testwill** [comment]
Is there any parameter modification that can not go through the network

**Comment by testwill** [comment]
Need to connect to the Internet?

**Comment by dwertent** [comment]
@testwill  I'm not sure I understand you.
When running the [Kubescape-Prometheus Integration](https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-prometheus-integrator/README.md) chart, you do not connect to the internet.

But then, the results will not be submitted to the [Kubescape Cloud](https://cloud.armosec.io/) so you will need to find a way of viewing the results.

Did I answer your question?

**Comment by testwill** [comment]
Thankyou.
I don't have time to change it to [Kubescape-Prometheus Integration](https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-prometheus-integrator/README.md) chart.
I have other ways to query scan results.
Can the configuration below be used without using the public network?
`	var (
	GlobalTrue  = true
	GlobalFalse = false
)

	cfg := utilsmetav1.PostScanRequest{
		Account:     "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
		HostScanner: &globalkey.GlobalFalse,
		Submit:      &globalkey.GlobalFalse,
		//TargetNames:        []string{"control"},
		TargetType:         "control",
		UseCachedArtifacts: &globalkey.GlobalFalse,
		KeepLocal:          &globalkey.GlobalTrue,
	}`

**Comment by dwertent** [comment]
Yes, but you should change the `UseCachedArtifacts` to `false`, this way Kubescape will not download artifacts from the internet.
Also, if you are not connected to the internet there is no need of adding the account ID.

It should look like this:
```
cfg := utilsmetav1.PostScanRequest{
	HostScanner: &globalkey.GlobalFalse,
	Submit:      &globalkey.GlobalFalse,
	UseCachedArtifacts: &globalkey.GlobalTrue,
	KeepLocal:          &globalkey.GlobalTrue,
}
```

> Notice, I removed the `TargetType` so it will run the default

**Comment by testwill** [comment]
thanks
