### ISSUE TITLE
#904 Issue with opening links within kubescape reports

### ISSUE THREAD

**Issue by oakgul1** [kubescape/kubescape#947]
# Describe the bug
As mentioned in an earlier issue #904  i still got the same issue using the latest image form quay.io 

# Environment
quay.io/repository/kubescape/kubescape:latest

Your current version is:
quay.io/repository/kubescape/kubescape:latest

# Steps To Reproduce
1. Pull quay.io/repository/kubescape/kubescape:latest
2. Scan cluster en print report in html 
3. Click on CIS link

# Expected behavior
 404 Page Not Found 

# Actual Behavior
 404 Page Not Found   https://hub.armosec.io/docs/cis-5.2.9  must be -> https://hub.armosec.io/docs/cis-5-2-9
.

**Comment by suhasgumma** [comment]
Hi @oakgul1 , 
#946 should fix the issue.

**Comment by dwertent** [comment]
@oakgul1  Does it reproduce when you explicitly use the tag `v2.0.176`: 
```
quay.io/repository/kubescape/kubescape:v2.0.176
```

**Comment by oakgul1** [comment]
@dwertent Yes it does

**Comment by dwertent** [comment]
@oakgul1 Thanks for reporting!
I see @suhasgumma [opened a PR](https://github.com/kubescape/kubescape/pull/946), it will be fixed next release :)

**Comment by oakgul1** [comment]
Thanks @dwertent
