### ISSUE TITLE
Excluding namespaces

### ISSUE THREAD

**Issue by alfrye** [kubescape/kubescape#95]
When running a cluster with v1.0..88 and using the flag --exclude-namepaces "kube-system,kube-public" the scan results are still showing this namespaces under the [control: Network policies] section.

`kubescape scan framework --exclude-namespaces "kube-system,kube-public" \
 -t 80 \
-o cluster-scan.log nsa`

**Comment by dwertent** [comment]
@Daniel-GrunbergerCA How is this possible? What is the Kubernetes object the rego returns when running this control?

**Comment by dwertent** [comment]
@Daniel-GrunbergerCA I found the issue. Should be fixed next release.

**Comment by alfrye** [comment]
@Daniel-GrunbergerCA  Thanks for the quick response of this.  Just to clarify I was seeing this mainly in the Network policy control. 

`[control: Network policies] failed
 [control: Network policies] failed

    Namespace - kube-system
    Namespace - default
    Namespace - kube-public
    Namespace - kube-node-lease
    Namespace - gatekeeper-system
`

**Comment by dwertent** [comment]
@alfrye Yes, we filtered out the namespace based on `metadata.namespace` so when the failed object was a namespace we did not filter it out (since we did not check the `metadata.name`).

This fix is waiting to be released, I will update the issue tag to `fixed` after it is released.

Have a nice day and thank you for your feedback :)

**Comment by danieljkemp** [comment]
```
ApiVersion:
Kind: ServiceAccount
Name: statefulset-controller
Namespace: kube-system

Controls: 9 (Failed: 1, Excluded: 0)

+----------+------------------+------------------------------------+-----------------------------------------+
| SEVERITY |   CONTROL NAME   |                DOCS                |          ASSISTANT REMEDIATION          |
+----------+------------------+------------------------------------+-----------------------------------------+
| Critical | Data Destruction | https://hub.armo.cloud/docs/c-0007 | relatedObjects[1].rules[4].resources[0] |
|          |                  |                                    | relatedObjects[1].rules[4].verbs[1]     |
|          |                  |                                    | relatedObjects[1].rules[4].apiGroups[0] |
|          |                  |                                    | relatedObjects[0].subjects[0]           |
|          |                  |                                    | relatedObjects[0].roleRef.name          |
+----------+------------------+------------------------------------+-----------------------------------------+
```

with the command 

`kubescape scan framework nsa,mitre,armobest,devopsbest --exclude-namespaces kube-system,kube-public`

looks like it is also not filtering service accounts

**Comment by iamhardikat11** [comment]
Hi, is this Issue still open, please guide me how to work on this, Thank you and kudos to your team.
