### ISSUE TITLE
--cluster-name flag is not working

### ISSUE THREAD

**Issue by biacharj** [kubescape/kubescape#952]
Previouis issue closed: https://github.com/kubescape/kubescape/issues/861 

@dwertent 

Scan does not start.

+ kubescape scan framework nsa --verbose --cluster-name my-cluster1-0-0
{"level":"info","ts":"2022-12-02T11:53:03Z","msg":"Kubescape scanner starting"}
{"level":"warn","ts":"2022-12-02T11:53:04Z","msg":"Kubernetes cluster nodes scanning is disabled. This is required to collect valuable data for certain controls. You can enable it using  the --enable-host-scan flag"}
{"level":"info","ts":"2022-12-02T11:53:08Z","msg":"Downloading/Loading policy definitions"}
{"level":"info","ts":"2022-12-02T11:53:08Z","msg":"Downloaded/Loaded policy"}
{"level":"error","ts":"2022-12-02T11:53:08Z","msg":"failed to discover API server information","error":"Get \"https://127.0.0.1:44/version?timeout=32s\": dial tcp 127.0.0.1:44: connect: connection refused"}
{"level":"info","ts":"2022-12-02T11:53:08Z","msg":"Accessing Kubernetes objects"}
{"level":"fatal","ts":"2022-12-02T11:53:08Z","msg":"failed to get resource: /v1,

**Comment by dwertent** [comment]
Hi @biacharj , can you please verify you have a running Kubernetes cluster and that the `kubeconfig` file is in the default path?

**Comment by dwertent** [comment]
Closed because I did not receive a response .
