### ISSUE TITLE
feature: Scan Remote repository - `GitLab`

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#953]
## Introduction

Currently, you can scan a remote repository hosted on `GitHub` as follows:
```
kubescape scan https://github.com/<org>/<repo>
``` 
In the [background](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L93), kubescape will clone the repository and scan it like scanning a local directory.

## Current behavior
This is true [only for repositories hosted on github](https://hub.armosec.io/docs/repository-scanning#scan-remote-repository)

## Desired behavior
Kubescape should support scanning public/private repositories hosted on `GitLab`

e.g.
```
kubescape scan https://gitlab.com/<org>/<repo>
``` 

### Additional information
Private repositories should be supported as well, the token should be passed using an environment variable

**Comment by anubhav06** [comment]
I would love to work on this and explore the GitLab API !

**Comment by rabbanimdrb** [comment]
I was **interested in contributing** and have come across this good first issue, I want to know **if there are any prerequisites to contribute to this particular issue**.
Any particular language I should know?

**Comment by ryuusama09** [comment]
> I was **interested in contributing** and have come across this good first issue, I want to know **if there are any prerequisites to contribute to this particular issue**.
> Any particular language I should know?

hey @anubhav06 , have you made any progress ? or would like to collaborate on thhis issue ?
