### ISSUE TITLE
feature: Scan Remote repository - `Azure`

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#954]
## Introduction

Currently, you can scan a remote repository hosted on `GitHub` as follows:
```
kubescape scan https://github.com/<org>/<repo>
``` 
In the [background](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L93), kubescape will clone the repository and scan it like scanning a local directory.

## Current behavior
This is true [only for repositories hosted on github](https://hub.armosec.io/docs/repository-scanning#scan-remote-repository).

## Desired behavior
Kubescape should support scanning public/private repositories hosted on `Azure`

e.g.
```
kubescape scan https://<>@dev.azure.com/<>/<>/_git/<>
``` 

### Additional information
Private repositories should be supported as well, the token should be passed using an environment variable

**Comment by anubhav06** [comment]
If it's still open and no one else is working on it, then I can take this. ( Since, this is similar to adding support for GitLab API )

**Comment by anubhav06** [comment]
I've pretty much completed adding this feature.
Only thing that is creating a problem is that, even for scanning **public** Azure Repos, I need to pass my Personal Access Token. 
When I pass my PAT, it successfully scans the repo. Without PAT, it shows an error that `authentication required`.

This seems to be a problem with [go-git](https://github.com/go-git/go-git). Should I go ahead and create a PR with what's ready ?

**Comment by matthyx** [comment]
thanks a lot @anubhav06 !
