### ISSUE TITLE
feature: Scan Remote repository - `Bitbucket`

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#955]
## Introduction

Currently, you can scan a remote repository hosted on `GitHub` as follows:
```
kubescape scan https://github.com/<org>/<repo>
``` 
In the [background](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/filesloader.go#L93), kubescape will clone the repository and scan it like scanning a local directory.

## Current behavior
This is true [only for repositories hosted on github](https://hub.armosec.io/docs/repository-scanning#scan-remote-repository)

## Desired behavior
Kubescape should support scanning public/private repositories hosted on `Bitbucket`

e.g.
```
kubescape scan https://<your_username>@bitbucket.org/<workspace_ID>/<repo_name>
``` 

### Additional information
* Private repositories should be supported as well, the token should be passed using an environment variable
* You will first need to add the `bitbucket` parser support to the [go-git-url](https://github.com/kubescape/go-git-url#supported-parsers) package.

**Comment by matthyx** [comment]
Do we want to also scan bitbucket enterprise?
One question regarding the current implementation, do we rely on `git clone` or the API to download a `.tgz` archive containing the repository at a certain revision? From experience the latter technique is way faster!

**Comment by vladklokun** [comment]
@matthyx We do, but this is not a hard requirement. Let’s start small, and move on step by step.

Regarding the implementation, we currently rely on a plain clone. So if you’re sure that we can speed up the cloning by working with `.tgz`, feel free to do it that way :)

**Comment by matthyx** [comment]
If you don't mind I'll check the `tgz` part after the end of the year holidays?
If the bitbucket feature cannot wait, please work on it in the meantime.
Thanks!

**Comment by Turuk3100** [comment]
Ок
