### ISSUE TITLE
Homebrew install does not work when proxy.golang.org is unreachable

### ISSUE THREAD

**Issue by jimmyraywv** [kubescape/kubescape#957]
# Describe the bug
Homebrew install does not work when `proxy.golang.org` is unreachable

# Environment
OS: the OS + version you’re running Kubescape on, e.g Ubuntu 22.04 LTS
Version: the version that Kubescape reports when you run `kubescape version`
```
MacOS arm64
```

# Steps To Reproduce
1. go env -w GOPROXY=direct
2. brew install kubescape-cli

```
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/credential.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/refs.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/reset.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/filter.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/transaction.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/stdint.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/commit.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2/refdb.h
-- Installing: /tmp/kubescape-cli-20221206-52362-83d1a0/kubescape-2.0.176/git2go/static-build/install/include/git2.h
go install --tags "static" ./...
go: github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.mod": dial tcp: lookup proxy.golang.org: i/o timeout
go: downloading golang.org/x/crypto v0.0.0-20201203163018-be400aefbc4c
go: github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.mod": dial tcp: lookup proxy.golang.org: i/o timeout
make[1]: *** [install-static] Error 1
make: *** [libgit2] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by dwertent** [comment]
Thank you for reporting.
@amirmalka Can you please take a look?

**Comment by amirmalka** [comment]
@jimmyraywv I tried reproducing this issue on my side but the process finished successfully.
Steps taken:
1. Clean modcache, build cache
2. Update GOPROXY env accordingly
3. Both building kubescape and brew install finished with success.

Could you please advise try again and advice if this is not a temporary issue?
If possible to run this also from a different machine just to be safe it would be great.

**Comment by jimmyraywv** [comment]
So, if you look at the original issue, you can see that the process is not honoring my local `go env -w GOPROXY=direct` setting and still trying to use `https://proxy.golang.org...`. I wiped my caches and tried again today; no joy. 

```
go: github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.mod": dial tcp: lookup proxy.golang.org: i/o timeout
go: downloading golang.org/x/crypto v0.0.0-20201203163018-be400aefbc4c
go: github.com/google/shlex@v0.0.0-20191202100458-e7afc7fbc510: Get "https://proxy.golang.org/github.com/google/shlex/@v/v0.0.0-20191202100458-e7afc7fbc510.mod": dial tcp: lookup proxy.golang.org: i/o timeout
make[1]: *** [install-static] Error 1
make: *** [libgit2] Error 2
```

Is there another way to use this without homebrew? Is there a way to set the GOPROXY inside the homebrew process?

**Comment by amirmalka** [comment]
@jimmyraywv  Depends on what you want to do. 

If you're looking to build from source you can follow the instructions in the README and set the GOPROXY according to your needs: https://github.com/kubescape/kubescape#build-on-linuxmacos

Alternatively, you can install Kubescape without building from source:
by running `curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash` in your terminal.
(https://github.com/kubescape/kubescape#install)

Regarding your question about setting the GOPROXY for the brew command, I suggest to ask the Homebrew team https://github.com/orgs/Homebrew/discussions
