### ISSUE TITLE
AKS cloud provider is not recognized correctly

### ISSUE THREAD

**Issue by amirmalka** [kubescape/kubescape#980]
# Describe the bug
Scanning an AKS cluster works fine, however, Kubescape fails to recognize it as an AKS cluster: the `clusterCloudProvider` field in the report summary is empty.

The existing logic for recognizing the cloud provider works well for GKE and EKS:
https://github.com/kubescape/kubescape/blob/master/core/pkg/policyhandler/handlenotification.go#L56
https://github.com/kubescape/kubescape/blob/master/core/pkg/policyhandler/handlenotification.go#L62

Unlike the other cloud providers, an AKS cluster will not contain a `gke`/`eks` string in the context. which is what the existing logic is looking for. As part of fixing this bug, Kubescape will have to use a better approach for filling up the cloud provider field properly.

# Environment
OS: Any
Version: 2.0.178

# Steps To Reproduce
1. Run `kubescape scan` on an AKS cluster, output the report to a JSON file.

# Expected behavior
`clusterCloudProvider` field should have the `aks` value.

# Actual Behavior
`clusterCloudProvider` field is empty 

# Additional context
N/A

**Comment by pwnb0y** [comment]
Hey @amirmalka is this issue is still open or not?

**Comment by dwertent** [comment]
@pwnb0y yes, it is still open since we did not release the fix

**Comment by DeeptanshuDas** [comment]
Hey  I want to work on this issue but could not understand the issue
