### ISSUE TITLE
Proposal: introducing linting to the kubescape codebase

### ISSUE THREAD

**Issue by fredbi** [kubescape/kubescape#985]
**Is your feature request related to a problem? Please describe.**</br>
 > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
 
When a code base grows, code readability becomes paramount.
There are quite a few places where the kubescape codebase departs from widely adopted go practice.
We have all been there and this is perfectly understandable at this stage.
Pure style notwithstanding, this results in some components being harder to grasp than strictly needed.

**Describe the solution you'd like.**</br>
 > A clear and concise description of what you want to happen.

I propose to introduce linting to the kubescape git repository and gradually address issues.

* Existing linting issues should not block PRs unless they introduce offending code.
* Enabling linting rules is a gradual process: we'd start with a few rules only and gradually raise our enforcement of coding standards.
* We won't introduce rules that would break existing interfaces because of some styling issues (e.g. initialisms, etc.)
* Linting fixes are not always trivial. We should limit the scope of such fixes to a series of rather small, reviewable PRs.

**Describe alternatives you've considered.**</br>
 > A clear and concise description of any alternative solutions or features you've considered.
 
I've also tried to run some static analysis linters manually, detect some issues, and fix them individually.
This is the approach followed by #982.

**Additional context.**</br>
 > Add any other context or screenshots about the feature request here.

**Comment by matthyx** [comment]
I think this one is done @fredbi ? If not please reopen it :-)
