### ISSUE TITLE
kubescape crashes without details inside pod

### ISSUE THREAD

**Issue by RomanTheLegend** [kubescape/kubescape#995]
# Describe the bug
When trying to run kubescape manually from pod, it crashes, and even debug information doesn't explain anything at all.
The process dies after random time. The very same build runs fine from my laptop.
This is a standalone run (i.e. not linked to SaaS)

# Environment
Version: v2.0.178
GKE:  1.23.12-gke.1600 
helm.sh/chart: kubescape-cloud-operator-1.8.10 
image: quay.io/kubescape/kubescape:v2.0.178

# Steps To Reproduce
1. Deploy to cluster using kubescape-operator helm chart
2. login to pod
3.  Set the variables:
```
export GOOGLE_APPLICATION_CREDENTIALS=/home/ks/auth.json
export GOOGLE_PROJECT=sandbox
export GOOGLE_REGION=us-east4
```
where `/home/ks/auth.json` is the key for GCP service account that was used to create cluster via terraform (i.e. should have all the necessary permissions)

4. Run the scan `kubescape scan --keep-local -l debug`

# Expected behavior
Get the scan results

# Actual Behavior
```
kubescape scan --keep-local -l debug
[info] Kubescape scanner starting
[debug] Kubescape Cloud URLs. api: api.armosec.io; auth: auth.armosec.io; report: report.armo.cloud; UI: cloud.armosec.io
[warning] current version 'v2.0.178' is not updated to the latest release: 'v2.0.179'
[warning] Kubernetes cluster nodes scanning is disabled. This is required to collect valuable data for certain controls. You can enable it using  the --enable-host-scan flag
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing Kubernetes objects
[success] Accessed to Kubernetes objects
[info] Requesting images vulnerabilities results
[debug] Collecting images vulnerabilities
[warning] failed to collect image vulnerabilities. error: credentials are not configured for any registry adaptor; Read more here: https://hub.armosec.io/docs/configuration-of-image-vulnerabilities
[success] Requested images vulnerabilities results
[info] Requesting Host scanner data
[debug] Collecting rbac resources
◐[debug] Collecting cloud data
[debug] cloud. cluster: sandbox; clusterName: sandbox; provider: gke
◑[info] Scanning. Cluster: sandbox
Killed
```

# Additional context

**Comment by dwertent** [comment]
Hi @RomanTheLegend , and thank you for reporting.

I have some questions:
1. Does the pod have any events? `kubectl describe -n kubescape kubescape-<>`
2. Is the containers restarting? If so, do you know why? 
3. What is the cluster size you are testing? (nodes/pods)
4. Why are you running the KS CLI from within the pod? By default, KS scans the cluster on installation 

FYI You can pass the GKE configurations using the [helm values](https://github.com/kubescape/helm-charts/blob/master/charts/kubescape-cloud-operator/README.md#values).

**Comment by RomanTheLegend** [comment]
No events for the pod, and container is running.

I'm running it manually from pod's shell to diagnose why scan is not working via REST API, and it's easier to manipulate settings and see what's happening this way. My suspicion falls on incorrect security settings/cluster settings.

The deployment done via terraform:

```
resource "helm_release" "kubescape" {
  name              = "kubescape"
  repository        = "https://kubescape.github.io/helm-charts/"
  chart             = "kubescape-cloud-operator"
  wait              = true
  atomic            = true
  namespace         = "kubescape"

  set {
    name  = "cloudProviderEngine"
    value = "gke"
  }
  set {
    name  = "gkeServiceAccount"
    value = "terraform@gcp-project-name.iam.gserviceaccount.com"
  }
  set {
    name  = "clusterName"
    value = "sandbox"
  }
  set {
    name  = "kubescape.submit"
    value = "false"
  }
  set {
    name  = "kubescape.skipUpdateCheck"
    value = "false"
  }
  set {
    name  = "kubescape.enableHostScan"
    value = "false"
  }
```
clusterName is the same as in the output of `kubectl config current-context`



What's more, when I ran Kubescape's container from local docker and passed kubeconfig + service account key it worked:

```
docker run -it --rm --name kubescape -v ~/terraform_key.json:/terraform_key.json:ro -v ${PWD}/sandbox_kubeconfig:/sandbox_kubeconfig --entrypoint "" quay.io/kubescape/kubescape:v2.0.178 /bin/sh


export GOOGLE_APPLICATION_CREDENTIALS=/terraform_key.json
kubescape scan --kubeconfig=/sandbox_kubeconfig --keep-local
```
The above produced the report just fine. But when I copy these very files to pod and run it just dies. The process dies regardless of whether kubeconfig file is provided or not

**Comment by RomanTheLegend** [comment]
After few more tests I decided to finally check the exit code and it was 137 - low memory *facepalm* 

With 1Gb it now runs fine, all is left is to properly mount service account key into container. Now all that's left is to pass the key to ksserver so that API scans will work too
